### PR TITLE
[Flash 2.0] - Added quotes screen above loading progress bar

### PR DESCRIPTION
**Pull request by GhaziTriki**
- Add loading quote.
- Update chat export format.

### CODE REVIEW

**Comment by GhaziTriki** [comment]
It needs some other updates before being merged.

**Comment by GhaziTriki** [comment]
Ready to be merged.

**Comment by capilkey** [comment]
Is there no way to turn these off?

**Comment by GhaziTriki** [comment]
Actually not. Good point, some customers would like to hide the loading quote. I will add an option to deactivate it.

**Comment by capilkey** [comment]
My issue with these is that they're preaching about teaching, but what if you're using BBB for internal meetings. And I definitely need to turn them off for my VM.

**Comment by GhaziTriki** [comment]
Added a new option to enable/disable quote display.

**Pull request merged**
