### PR TITLE
chore: Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
> Hi @naveensrinivasan
> Thank you for this contribution! Could you please confirm if you already sent in the signed Contributor License Agreement? See https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code . Thanks in advance!

I have done that. Thanks

**Comment by antobinary** [comment]
Hi @naveensrinivasan 

> I have done that. Thanks

I am afraid we are not spotting it. Any chance you could resend and add "15309" to the subject line? Thanks in advance!

**Comment by naveensrinivasan** [comment]
> Hi @naveensrinivasan
> 
> > I have done that. Thanks
> 
> I am afraid we are not spotting it. Any chance you could resend and add "15309" to the subject line? Thanks in advance!

I can do that.

**Comment by antobinary** [comment]
Apologies, we did not receive the CLA. We'll be closing this pull request. Thanks for bringing this to our attention!

**Pull request closed without merging**
