### PR TITLE
Playback Proc: The encoding speed incresed 5-6 times

### PR DESCRIPTION
**Pull request by caglaroflazoglu**
Explained in there: https://github.com/bigbluebutton/bigbluebutton/issues/8770

### CODE REVIEW

**Comment by baraci** [comment]
The average of 50 sessions per day has decreased from 5-6 days to 1 day. thanks

**Comment by basisbit** [comment]
@caglaroflazoglu could you please confirm if you already sent in the signed Contributor License Agreement? See https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code . Thanks in advance!

**Comment by caglaroflazoglu** [comment]
> @caglaroflazoglu could you please confirm if you already sent in the signed Contributor License Agreement? See https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code . Thanks in advance!

Yes, i did

**Comment by basisbit** [comment]
Regarding the change of concurrently used threads count from 2 to 4: For a server with maybe 8 CPU cores and with sessions currently in progress, hogging 50% of the CPU cores by the video processing would probably cause problems for users.
I'd suggest you change it back to 2 concurrent threads if you want this PR to be merged anytime soon.

Additionally, once this PR is merged, I'd suggest adding a section for adjusting the core count and maybe how to make it process only during the night (using all cores minus 1?) to the bbb docs at https://github.com/bigbluebutton/bigbluebutton.github.io/blob/master/_posts/2019-02-14-customize.md

**Comment by caglaroflazoglu** [comment]
i will add a section this. Default threads count decreased to 2.

**Pull request closed without merging**
