### PR TITLE
Quick web access dropdown

### LINKED ISSUE #10124: Quick website access dropdown (which you can screen-share if needed)
**Is your feature request related to a problem? Please describe.**
During presentation, you may want to share a website by screen share. For doing this, however, you need to open the browser, enter URL, and share the screen. It's tedious when you have many websites that you want to co-browse with students.

**Describe the solution you'd like**
Inspired by https://github.com/bigbluebutton/bigbluebutton/pull/9609 , I would like to have a quick website access dropdown. Any project ongoing?

**Describe alternatives you've considered**
It's also possible to directly screenshare the website that you have chosen from the dropdown list. But I'd prefer a simple solution of launching a new browser window, which you can share if needed. 

**Additional context**
I have written the PR. After a couple of testings, I will post it.

### PR DESCRIPTION
**Pull request by hiroshisuga**
### What does this PR do?
Reads the slide text, extracts URLs that are not from video sharing services, and creates a dropdown to quickly access to the website in a new browser window. The presenter can share the screen if necessary.

### Closes Issue(s)
close #10124 

### Motivation
Inspired from https://github.com/bigbluebutton/bigbluebutton/pull/9609 .
During presentation, you may want to share a website by screen share. For doing this, you need to open the browser, enter URL, and share the screen. It's tedious when you have many websites that you want to co-browse with students.

### More
The PR overlaps in part with the PR https://github.com/bigbluebutton/bigbluebutton/pull/9609 , but is not dependent on it.
It may also be possible to put the button in the presentation toolbar, not in the action bar.

In the screen capture below I merged the PR #9609 as well, so that one can choose quick external video share or quick website access when the slide has both types of addresses.
screenrecord

### CODE REVIEW

**Comment by antobinary** [comment]
Well done @hiroshisuga !!

**Comment by iSamof** [comment]
Thank you very much @hiroshisuga ... excellent contribution.

**Comment by matiasilva** [comment]
Looks absolutely fantastic.

**Comment by tylercopeland** [comment]
@hiroshisuga thank you for this contribution, fantastic work! 

In a perfect world, we would want to see the links within the slides themselves to be clickable, but I understand there is a lot of development efforts and moving parts that are required to full that off. 

If the goal is only to provide this as an option for a presenter, I recommend the place button in the presenter toolbar. That way, all the presenter actions for the presentation are grouped. 

We could also consolidate the two buttons to a single dropdown. 

[External Icon]
Videos
Link 
Link
Link
-----
URL's
Link
Link
Link

**Comment by alialic** [comment]
hi ,I want to customize the meeting page. But I can not access the session codes. Do you know the access path of the codes related to the session page?

**Comment by mrkeksi** [comment]
@hiroshisuga this PR can be closed for #10588 i think?

**Comment by hiroshisuga** [comment]
Hi @mrkeksi , thanks for letting me know. I will close it.

**Pull request closed without merging**
