### PR TITLE
fix: ui adjustments for large te and km locales

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

Makes small adjustments to icons and toggle buttons for locales Telugu (`te` and `te-IN`) and Khmer (`km` and `km-KH`)

#### before vs after (Telugu)

te-before te-after

#### before vs after (Khmer)

km-before km-after

### CODE REVIEW

**Comment by antobinary** [comment]
Is there a better way to fix this without mentioning `te` and `km`? If we add support for another locale with tall characters we would need to go back and edit the source...
Can we make the record indicator symmetrical rather than margin-top .5 rem?

**Comment by ramonlsouza** [comment]
> Is there a better way to fix this without mentioning `te` and `km`? If we add support for another locale with tall characters we would need to go back and edit the source...
> Can we make the record indicator symmetrical rather than margin-top .5 rem?

replaced locale-specific code with `align-items: center;` in 02057c7

**Comment by antobinary** [comment]
Awesome! Are the screenshots still relevant?

**Review by antobinary — APPROVED** [review]

**Comment by ramonlsouza** [comment]
> Awesome! Are the screenshots still relevant?

They can be left as an example, but now the changes are not limited to these 2 languages

**Pull request merged**
