### PR TITLE
Updated faulty PDF file conversion mechanism

### PR DESCRIPTION
**Pull request by GhaziTriki**
Updated faulty PDF file conversion mechanism. Now, we  go through the following process:

- Extract the PDF page to a single PDF file.
- Convert the PDF file to a PNG image.
- Conert the PNG image to a SWF file.

### CODE REVIEW

**Comment by ritzalam** [comment]
Is there no more PDF -> SWF conversion directly? 

Don't we loose clickable links on the SWF file if we first convert the PDF to PNG then to SWF?

**Comment by ffdixon** [comment]
The logic of PDF -> PNG -> SWF should not affect the normal conversion, but only be used if BigBlueButton detects there are too many objects in the slides (and thus may cause problems when rendered as SWF). (Need to verify that this conversion only kicks in where there are too many objects).

**Comment by ritzalam** [comment]
I am getting compile errors. Ghazi can you please check that you've committed everything?

ubuntu@ritz-1pt0-dev:~/dev/old-bbb/bigbluebutton/bigbluebutton-web$
| Compiling 10 source files

| Compiling 130 source files

| Compiling 126 source files.
| Error Compilation error: startup failed:
Compile error during compilation with javac.
/home/ubuntu/dev/old-bbb/bigbluebutton/bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Pdf2SwfPageConverter.java:29: error: cannot find symbol
import org.bigbluebutton.presentation.handlers.Pdf2PngPageConverterHandler;
                                              ^
  symbol:   class Pdf2PngPageConverterHandler
  location: package org.bigbluebutton.presentation.handlers
/home/ubuntu/dev/old-bbb/bigbluebutton/bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Pdf2SwfPageConverter.java:134: error: cannot find symbol
      Pdf2PngPageConverterHandler pbPngHandler = new Pdf2PngPageConverterHandler();
      ^
  symbol:   class Pdf2PngPageConverterHandler
  location: class Pdf2SwfPageConverter
/home/ubuntu/dev/old-bbb/bigbluebutton/bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Pdf2SwfPageConverter.java:134: error: cannot find symbol
      Pdf2PngPageConverterHandler pbPngHandler = new Pdf2PngPageConverterHandler();
                                                     ^
  symbol:   class Pdf2PngPageConverterHandler
  location: class Pdf2SwfPageConverter
Note: /home/ubuntu/dev/old-bbb/bigbluebutton/bigbluebutton-web/src/java/org/bigbluebutton/web/services/RedisStorageService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/ubuntu/dev/old-bbb/bigbluebutton/bigbluebutton-web/src/java/org/bigbluebutton/api/domain/Meeting.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

**Comment by ffdixon** [comment]
Fixes #2935

**Pull request merged**
