### PR TITLE
Changed the wording for "save current slide"

### LINKED ISSUE #15985: Change German wording for "save current slide" via ⋮
### Current Situation 

User can download the **current slide** of a presentation via the ⋮ [three vertical dots]-icon upper right corner in the presentation area: 

2022-11-10 13_56_16-BigBlueButton - Startraum - Chromium

The German Text is:
> Ausschnitt der aktuellen Folie

and the success message is:
> Aktuelle Präsentation wurde herunter[geladen]...

2022-11-10 13_56_21-BigBlueButton - Startraum - Chromium

What you get ist not the whole presentation as mentioned in the success message but only a single slide as `*.png` image: 

2022-11-10 13_57_00-Präsentation_Startraum_2022-11-10T12_56_27 569Z png ‎- Windows-Fotoanzeige

### Problem description

1. Both messages are not true! ;-) 
a) It is not a section **of the current slide** ("Folie"), it's a section of the current presentation, aka "a single slide". 
b) Success message is also wrong. Not the presentation is downlaoded but **a single slide from the current presentation only.** 
2. The text 
"Ausschnitt der aktuellen Folie"
is incomplete. **A verb is missing**. What is done with this, what can I get as user, can I see it -- would be my expectation without a verb, but it is downloaded. 

### Solution change wording

Change 
> Ausschnitt der aktuellen Folie
to
> Aktuelle Folie herunterladen

Change the success message
> Aktuelle Präsentation wurde herunter[geladen]...
to 
> Aktuelle Folie wurde herunter[geladen]...

### PR DESCRIPTION
**Pull request by Marius1501**
### What does this PR do?

Changes in the wording for the "save current slide" in English and German.

### Closes Issue(s)

Closes #15985

### CODE REVIEW

**Comment by MaximKhlobystov** [comment]
Hello @Marius1501,

For localization updates, we use `transifex` (https://explore.transifex.com/bigbluebutton/bigbluebutton-v26-html5-client/) instead of committing the changes directly on GitHub. You can update the values on Transifex, and then the changes will be pulled to GitHub at some point. You can find more details here in the docs: https://docs.bigbluebutton.org/dev/localization.html.

**Comment by Marius1501** [comment]
@MaximKhlobystov Ok, I made a join request on `transifex`. But I hasn't been assigned yet. Could you approve my join request, please? 😄

**Comment by Marius1501** [comment]
I changed the german part in transifex but I could not change the english part because I don't have the permission to do so. Is there something I can do? @MaximKhlobystov

**Comment by MaximKhlobystov** [comment]
When we need to change English locale, that's the exception, we change it directly on the GitHub repo (no Transifex). I'm not sure if it's a good idea to apply this particular change in English labels though. If you really need to have this applied, you can override it for your BigBlueButton deployment.

**Pull request closed without merging**
