### PR TITLE
fix: action buttons in audio selector - mobile

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

Hides the action buttons when audio selector is open in mobile devices

#### before

Screenshot from 2021-05-12 11-08-56

#### after

Screenshot from 2021-05-12 11-08-22

### CODE REVIEW

**Review by antobinary — APPROVED** [review]

**Comment by mariogasparoni** [comment]
@ramonlsouza @antobinary 
Wondering where this case applies, once selector is disabled in mobile by default.

Is this the case where user activates the "Desktop" mode in mobile browser ?

**Comment by ramonlsouza** [comment]
> @ramonlsouza @antobinary
> Wondering where this case applies, once selector is disabled in mobile by default.
> 
> Is this the case where user activates the "Desktop" mode in mobile browser ?

When you open a dropdown in mobile, it hides the trigger button, but only the trigger button of that dropdown.

This PR hides the presenter menu button (the "+" button) when any dropdown is open, preventing it from appearing in the audio selector dropdown

**Comment by mariogasparoni** [comment]
Thanks @ramonlsouza 
> ... preventing it from appearing in the audio selector dropdown
My point is, how would it appears in audio selector dropdown (once mobile users aren't able to see audio selector dropdown) ?

**Comment by ramonlsouza** [comment]
> Thanks @ramonlsouza
> 
> > ... preventing it from appearing in the audio selector dropdown
> 
> My point is, how would it appears in audio selector dropdown (once mobile users aren't able to see audio selector dropdown) ?

the "audio selector dropdown" in mobile devices is the full screen page that I've put the screenshots in PR description

**Pull request merged**
