### PR TITLE
Unmute viewers

### LINKED ISSUE #6814: Add server option to enable unmute of viewers by moderators
There are use cases in the HTML5 client where moderators need to be able to unmute other users.  See

  https://groups.google.com/d/msg/bigbluebutton-dev/HjkhYAeA6WU/TT4owN-uBQAJ

Add a server option in settings.yml to enable a moderator in the HTML5 client to unmute other users.

### PR DESCRIPTION
**Pull request by pedrobmarin**
Added `unmuteViewers` to the `create` meeting API call.

When `true`, moderators should be able to unmute viewers.

Tries to resolve #6814 and #7092

### CODE REVIEW

**Comment by capilkey** [comment]
I just realized that the original requests specified "unmute viewers", but does it make sense to restrict it to just viewers? It's probably an acceptable restriction, but it's not quite back to what it was pre-2.2. If it's going to stay as unmuting viewers only, the akka-apps message handler doesn't match the clients because there's no role check on the person being unmuted here, https://github.com/bigbluebutton/bigbluebutton/pull/7234/files#diff-412f7575b8231975d1722ab4899cf699R17.

**Comment by pedrobmarin** [comment]
Well, if you ask me I prefer to just add an extra control at akka-apps to mach the whole thing than rewriting all the other stuff

**Comment by capilkey** [comment]
Definitely the easier change. The amount of files to add or change one property is very large.

**Comment by pedrobmarin** [comment]
I'm closing this for reevaluation

**Pull request closed without merging**
