### PR TITLE
Adds possibility to give a name to breakout rooms

### PR DESCRIPTION
**Pull request by gustavotrott**
This PR solves #9871

- Possibility to set a NAME for breakout rooms

naming_breakoutrooms

### CODE REVIEW

**Review by antobinary — COMMENTED** [review]
Looks fine to me but I also asked Tainan to give it a look

**Comment by Tainan404** [comment]
I tested it and noticed that the room name is not translated when the name is default

**Comment by gustavotrott** [comment]
> 
> 
> I tested it and noticed that the room name is not translated when the name is default

You are right! Once the moderator can set a name manually, I changed the `List of rooms` behavior to always show the original Room name instead of generate it dynamically accordingly with user language.
I will include a Flag to know when moderator didn't change the default name and then generate this room name dynamically to users.

Thanks @Tainan404

**Review by jfsiebel — CHANGES_REQUESTED** [review]
If the name given to the breakout is extensive it is not possible to manually join.

image

Also a large name break the layout for breakout join modal:

image

**Comment by gustavotrott** [comment]
> If the name given to the breakout is extensive it is not possible to manually join.
> 
> image
> 
> Also a large name break the layout for breakout join modal:
> 
> image

Fixed in last commit!
Thanks @jfsiebel 

image

**Comment by antobinary** [comment]
@gustavotrott Could you also resolve the conflict pls `bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx` ?

**Comment by gustavotrott** [comment]
> @gustavotrott Could you also resolve the conflict pls `bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx` ?

Sure! No more conflicts now :smile:

**Pull request merged**
