### PR TITLE
Prevent text overflow on polling buttons

### PR DESCRIPTION
**Pull request by KDSBrowne**
fixes issue #5266.

### CODE REVIEW

**Comment by OZhurbenko** [comment]
Why wrapping it into `<Tooltip>` at all if we can just pass an ariaLabel?
Tooltip is already in the [Button](https://github.com/KDSBrowne/bigbluebutton/blob/b5a03684075f0fe14d300b21f228757634a1ff3f/bigbluebutton-html5/imports/ui/components/button/component.jsx#L127)

**Comment by KDSBrowne** [comment]
I think because right now we can't show the tooltip on Buttons unless the hideLabel flag is passed to the btn as well.. In the case of the poll buttons we still need the label to show. It was originally why I added a showTip prop, so we didn't have to wrap buttons with the tooltip component, if the case where we want the tooltips on buttons with visible labels comes up.

**Comment by oswaldoacauan** [comment]
@OZhurbenko Because adding stuff into a already pretty complex component just make the life harder. As you always said, our button already has options that we never use this will be just another one. Why add more complexity to another component if we can just compose them?

**Comment by OZhurbenko** [comment]
Wait, I'm confused now.
I thought there was no Tooltip shown, since there was no label passed to the Button.
But we do pass a label to each of the Buttons ([here](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/polling/component.jsx#L49)), why isn't Button component picking that up?

**Comment by OZhurbenko** [comment]
I guess we would rarely need to see the tooltip if the label is displayed.
That actually makes sense, never mind :-)

**Pull request merged**
