### PR TITLE
fixed  passiv xss

### PR DESCRIPTION
**Pull request by dragin96**
fixed  passiv xss

### CODE REVIEW

**Comment by ffdixon** [comment]
Hi there, got your pull request.  What is the issue that you are trying to fix. 

Also, could we get you to sign a contributor's agreement (see http://docs.bigbluebutton.org/support/faq.html#contributing-to-bigbluebutton) so we could review and, if it looks good, accept your pull request.

**Comment by dragin96** [comment]
when outputting an error, you can compose a get query so there is xss vulnerability

**Comment by dragin96** [comment]
I have no time to deal with signing agreements, you have a bug that affects the security of the application

**Comment by ffdixon** [comment]
> I have no time to deal with signing agreements, 

Understood -- we had one of our committers merge in the updates as https://github.com/bigbluebutton/bigbluebutton/pull/4379.

**Pull request closed without merging**
