### PR TITLE
Add messages for chat push notifications

### PR DESCRIPTION
**Pull request by Tainan404**
-Add the latest 4 messages to chat push notification.
- Changes the break point of the message grouping based on the time of the last message sent.
- Add specific message to public chat.
- Change the count of unread messages to count from the message groups.

print-toast

### CODE REVIEW

**Comment by MaximKhlobystov** [comment]
Tested it locally.
@tylercopeland Is it a good idea to modify chat counter this way? Before, when I saw 5 messages, I knew exactly what to expect - 5 messages. Now, it means there are 5 groups of messages somehow grouped by time. I find it a little confusing.
Also, chat counter change + break point change = HTML5 client's chat will look quite different from Flash client.

By the way, I believe, this may break the event listeners on chat scrolling that detect read messages, but it's not a big deal. Chat counter is broken anyways right now. I will fix it in my PR that's coming out soon :)

Last thing: in the issue #5470, it is mentioned that notifications would appear only when that particular chat is not visible. Do we need to see them all the time? Especially considering they cover the whiteboard controls on desktop.

**Comment by oswaldoacauan** [comment]
> Before, when I saw 5 messages, I knew exactly what to expect - 5 messages. Now, it means there are 5 groups of messages somehow grouped by time. I find it a little confusing.

Pretty sure this is unintentional. The way we group messages for display should be unrelated to the unread counter.

**Comment by MaximKhlobystov** [comment]
I believe, the change is here: https://github.com/Tainan404/bigbluebutton/blob/e59c8df71e1cca53912454c024b8f2bdcbb55fc9/bigbluebutton-html5/imports/ui/components/chat/service.js#L70. `GROUPING_MESSAGES_WINDOW` is 5 seconds now, instead of 60 sec.

**Comment by MaximKhlobystov** [comment]
Looks like this: 
chat

**Comment by MaximKhlobystov** [comment]
It seems to me that the first one is in public chat and the second one is in private chat.

**Comment by tylercopeland** [comment]
What's the benefit of grouping multiple messages in one notification versus having separate ones for "Hey guys" and "How are you?". I'm bringing this up because this doesn't seem like best practise in terms of chat notifications.

**Comment by MaximKhlobystov** [comment]
I'm testing it locally right now. And I'm not really sure how to reproduce the "Hey guys" and "How are you?" in the same notification. I can only see one notification with "Hey guys" and if I type "How are you?" within 5 seconds time limit, then I don't even get another notification with "How are you?"

**Comment by oswaldoacauan** [comment]
> @tylercopeland: What's the benefit of grouping multiple messages in one notification versus having separate ones for "Hey guys" and "How are you?". I'm bringing this up because this doesn't seem like best practise in terms of chat notifications.

The notification groups the messages on the same way we group them on the Chat Window, otherwise every message (from the same user) would be a new notification which would pollute the interface pretty quickly.

**Comment by tylercopeland** [comment]
@MaximKhlobystov let's merge this PR and test the functionality as a group.

**Pull request merged**
