### PR TITLE
Speedup getRecordings

### PR DESCRIPTION
**Pull request by pedrobmarin**
Some performance improvements made for getRecordings API call.
[testlog.txt](https://github.com/bigbluebutton/bigbluebutton/files/108172/testlog.txt)

### CODE REVIEW

**Comment by jfederico** [comment]
This is conflicting badly with the other pull request I did a few days ago. 

Should we merge somewhere else first and work together on testing the changes?

**Comment by ritzalam** [comment]
Yes. Push a branch where you tried to merged Pedro's changes and he can help fix conflicts.

**Comment by fcecagno** [comment]
It looks like most of the conflicts are in RecordingService.java. If you look at what we did there, it's not much, most of the work was to avoid reading from the file system multiple times the same information, and also we changed the way files are read from the file system. There's no change in terms of functionality. I'd recommend to start with your version, and then apply manually the modifications we did.

**Comment by jfederico** [comment]
There are other datatypes changes too.
I marged into getRecording-merged-enhancements, there are only three files with conflicts.

BUT, since I had done a clean up of the format (I run the formatting option provided by eclispe for removing tabs and unifying styles) it is now harder to identify the two changes.

I can work with Pedro to identify what we merge

**Comment by pedrobmarin** [comment]
Ok, I'll have a look

**Comment by jfederico** [comment]
Closing the pull request in order to open a new one with the merge of #2981 & #2987

**Pull request closed without merging**
