### PR TITLE
Problematic audio in some iOS devices

### LINKED ISSUE #8133: No sound on iPhone 6 / iOS 12.4.1, SE / 12.3.1
Hello!

Other hear me when I speak in micorophone, but I can't hear anybody.

In test sound window I don't hear myself too. When I choose "No" and click "Test your speaker volume" I hear test sound well.

iPhone 6, iOS 12.4.1
BBB 2.2. 703

Same issue was on HTML5 client in BBB 2.0 release.

### PR DESCRIPTION
**Pull request by mariogasparoni**
### What does this PR do?

Fixes audio problems listed in #8133 and #10388

### Closes Issue(s)

closes #8133 and  #10388

### Motivation
This started as an investigation of  a problem in some iOS devices, but i extended it to a full port of SIP.js library

### More
I have tested 4 different problematic devices (iPhone XS, XR, iPad air 2019 and some other iPad).
Also intensively did multiple tests in current Chrome, Firefox and Safari browsers, to avoid bringing regressions into current BBB's audio module.

### CODE REVIEW

**Comment by mariogasparoni** [comment]
thanks to @IBROF and @zagzam who have helped testing different iOS devices.

**Comment by mabras** [comment]
Thank you @mariogasparoni for this, we tested your soluction on a production and it's working.

We do a have a problem though. Some of our users get `1007` (We have turn server), `1004` and others get `Error: Connection error` error. We apply your patch on `2.2.25`. Before this, these errors do not happened.

Thanks,

**Comment by mariogasparoni** [comment]
Thanks for your info, could you send me some logs of your html5 app ?

mariogasparoni at gmail

**Comment by maychine-fatima** [comment]
> Thanks for your info, could you send me some logs of your html5 app ?
> 
> mariogasparoni at gmail

ERROR: clientLogger: Audio error - errorCode=1007, cause=ICE negotiation failed. Current state - disconnected

**Pull request merged**
