### PR TITLE
Skip echo test in breakout room 

### LINKED ISSUE #8387: Don't prompt for echo test when joining breakout room
When the user already has an active microphone and wishes to join a breakout room, we can short-circuit the echo test because they user has already tested their microphone on the server.

We can also do the same when they return to the main room.

### PR DESCRIPTION
**Pull request by Tainan404**
This PR implements a skip to echo test when the user is already in main room audio.

Closes #8387.

### CODE REVIEW

**Comment by olisb** [comment]
Would love to see this implemented asap ....

**Comment by decentral1se** [comment]
Yes, absolutely @olisb! We at https://www.org.meet.coop were discussing this possibility and are very happy to see this PR out already. Thanks for the good work @Tainan404 :rainbow: :+1: :rainbow:

**Comment by ownhardy** [comment]
I would very much like to see this implemented!

**Comment by eudinaesis** [comment]
Yes, please merge this in!

**Review by ramonlsouza — COMMENTED** [review]
conflicts resolved in #11381

**Pull request merged**
