### PR TITLE
refactor: connection status UX

### LINKED ISSUE #13231: Refactor Connection Status UX
@tylercopeland provided some refreshed designs for the Connection Status feature.The existing design suffered a bit when we started piling functionality on top of it, and a number of moderators reported lack of clarity on what the list of users meant...

**Screenshots**
Session Logs to be available only to moderators (like we do now)

Screenshot from 2021-09-15 12-51-58
Screenshot from 2021-09-15 12-52-04
Screenshot from 2021-09-15 12-52-14

Screenshot from 2021-09-15 12-52-19

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

This PR refactors connection status modal while implementing new UX.

Captura de tela de 2021-10-19 10-01-58

Captura de tela de 2021-10-19 10-02-01

Captura de tela de 2021-10-19 10-02-03

Captura de tela de 2021-10-19 10-10-45

### Closes Issue(s)

Closes #13231

### CODE REVIEW

**Comment by JoVictorNunes** [comment]
On mobile version, I was thinking of putting the button to open data saving options next to the "Copy statistics" button.

**Comment by pedrobmarin** [comment]
The other thing I had mentioned a couple of days ago was the close button. That looks off. It's collateral damage from a previous work done over this modal. How does the other modals display their close button on 2.5? They follow the same design?

**Comment by JoVictorNunes** [comment]
> What does it look like in RTL mode?

Some adjustments are still needed in RTL mode. I will share it with you as soon as it's done.

**Comment by prlanzarin** [comment]
I guess the less invasive approach would be to always display the data savings shortcut/link regardless of the user's connection status. But that's something that Tyler has to weigh in; as I mentioned, this is not a requirement, just an opinion.

**Comment by JoVictorNunes** [comment]
Hello guys!
I proposed the "Connection Stats" tab with a pretty simple pagination so that it's possible to show the connection status icon on mobile devices.

Captura de tela de 2021-11-23 09-06-47
Captura de tela de 2021-11-23 09-06-55
Captura de tela de 2021-11-23 09-07-11
Captura de tela de 2021-11-23 09-07-16
Captura de tela de 2021-11-23 09-09-19
Captura de tela de 2021-11-23 09-09-25

**Review by ramonlsouza — APPROVED** [review]

**Pull request merged**
