### PR TITLE
Bbb lock settings

### PR DESCRIPTION
**Pull request by tdj-br**
Added lockOnJoinConfigurable property to lock config

### CODE REVIEW

**Comment by capilkey** [comment]
(Continuing discussion from #561 )

The only advantage that I can see for sending that setting to the server is that all clients will have the same value no matter what is in their version of config.xml. But I don't really think that matters here because the value isn't actually changeable during the meeting.

config.xml.template also needs the new property added to it.

**Comment by tdj-br** [comment]
Updated the template. The advantage I see is to use same flow for all lock settings, so you don't have a different flow to this specific parameter. If in future we replace the way that lock settings are provided to the clients, it will affect all configs, with no special cases.

**Comment by tdj-br** [comment]
It's not a new message flowing to/from the server, it's only a new property in a map that's already flowing to/from server.

**Comment by capilkey** [comment]
The "allowModeratorLocking" property is included in config.xml, but not in the map already so there is already a setting that isn't included in the map. I can see your point about keeping it together though if we wanted to move the settings out of config.xml in the future.

**Comment by tdj-br** [comment]
That property was already there, but it's not used, so i removed it. Yes, in the future i think we will have no config.xml, due to multiple clients (html5/air/flash/whoknowswhat). IMHO, everything will be a message flowing from server to client.

**Pull request merged**
