### PR TITLE
Bbb lock settings fix

### PR DESCRIPTION
**Pull request by tdj-br**
Some fixes on Lock Settings. We will be working in QA entire week, please fix this and report any BUG you find. Thanks

### CODE REVIEW

**Comment by tdj-br** [comment]
Changes:
	-> Fixed bugs that was allowing locked user to share microphone and cleaned up the code;
	-> Viewers can be locked on Join and this is the default behavior;
	-> The "Lock On Join" option was added in the LockViewers dialog, it's checked by default;
	-> You can lock/unlock specific users
	-> Lock state is ignored when user is a presenter, so all locks are temporarily removed when a user become a presenter

**Comment by capilkey** [comment]
I just tried it out on my server and I couldn't find any way to break it. The only comment that I have is that it is hard for the viewers to tell what is and isn't locked.

**Comment by ffdixon** [comment]
-> The "Lock On Join" option was added in the LockViewers dialog, it's checked by default;

To keep the UI consistent, we can leave this true by default (which is what users expect), but hide the option behind a config setting in a default BigBlueButton install.  

That way, the option can be still made visible if needed for specific use cases.

**Comment by tdj-br** [comment]
Good point Fred. I'll add a parameter to hide this option. Tomorrow we will be doing more tests.

**Comment by tdj-br** [comment]
Chad, you are right. Any suggestion to make it easier?

**Pull request merged**
