### PR TITLE
Fix presentation upload drop zone showing red

### LINKED ISSUE #7087: Drag and dropping a presentation for upload shows red
In the latest build of BigBlueButton 2.2-beta, tried dragging a .pptx file over the drag-and-drop area and it showed red.

red

### PR DESCRIPTION
**Pull request by KDSBrowne**
Closes #7087

### CODE REVIEW

**Comment by capilkey** [comment]
Isn't it going red because it's being rejected? Just removing the red colour means that it's still being rejected.

**Comment by KDSBrowne** [comment]
It was showing red no matter what file type I used. If you do happen to try droping an unaccepted file type the error is shown in the toast.

**Comment by capilkey** [comment]
It's grey if I drag a text or PDF file.

**Comment by capilkey** [comment]
If I actually drop the PPT or PPTX file, it gets rejected so the block is still in place. It looks very similar to this issue, https://github.com/bigbluebutton/bigbluebutton/issues/6792, with the file selection. I'm not sure how the file type check is done for the drag-and-drop though.

**Comment by capilkey** [comment]
The reason that we have to use the extensions instead of the MIME types is because either the OS or the browser will filter out unknown types. This resulted in not being able to select Microsoft Office files if you didn't have Office installed on your computer.

**Pull request merged**
