### PR TITLE
Delay displaying altFlash div for the flash client wrapper.

### PR DESCRIPTION
**Pull request by GhaziTriki**

### CODE REVIEW

**Comment by capilkey** [comment]
What problem is this fixing?

**Comment by ffdixon** [comment]
Tested when joining using the HTML5 client, the page doesn't display to the user to "Launch the HTML5 client instead".  Rather, it just remains white.

**Comment by ritzalam** [comment]
Should we close this?

**Comment by GhaziTriki** [comment]
We don't need this anymore. However centring the HTML text will come later in a new pull request.

**Pull request closed without merging**
