### PR TITLE
Fix audio reconnect and button state on first state 2.2

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?

Fix of #9780, but  with some bugs fixes in the muted button state.

### Closes Issue(s)

#9905

### CODE REVIEW

**Comment by ethermammoth** [comment]
The "Fix mute button getting wrong state on first state" introduces bug on ~iOS12. 
Line 294: `if (voiceProp?.muteOnStart) this.isMuted = true;` produces Syntax error in Safari iOS 12
Changed to `if (voiceProp && voiceProp.muteOnStart)` seems to be better..

I could only test on iOS 12 (not 12.2) so if this is not an error in iOS 12.2 just ignore this msg

**Comment by rkul** [comment]
Hello everyone,

Appreciate your hard work on the product!
Could you tell me is there any chance this PR will be merged soon?

**Comment by antobinary** [comment]
Is this still needed? https://github.com/bigbluebutton/bigbluebutton/pull/10334 just got merged

**Comment by mariogasparoni** [comment]
@Tainan404,  thanks for the PR, but we can close it due to the recent audio changes
It already this functionality. For more info see #9016.

**Pull request closed without merging**
