### PR TITLE
fix some bugs and improve compatibility in the html5 client

### PR DESCRIPTION
**Pull request by zhu**

### CODE REVIEW

**Comment by antobinary** [comment]
@zhu has signed a contributor agreement in Oct 2018 https://github.com/bigbluebutton/bigbluebutton/pull/6122#issuecomment-426682089

**Comment by Tainan404** [comment]
Hey @zhu, do you tested the BBB on old browsers and got errors? because the latest babel version removes the trailing commas and change the `**` to `math.pow()`.
the latest version will be added with PR #6228.

screenshot from 2018-11-19 14-39-48

**Comment by zhu** [comment]
Hey @Tainan404, I tested BBB in the browser embeded in Wechat Android which powered by X5 engine. It's popular in China.
Solve this issue by update babel is good, but #6228 seems to take some time to complete.

**Comment by antobinary** [comment]
#6228 was merged. Is this still needed?

**Comment by Tainan404** [comment]
I don't think so, because the dropdown trigger bug are to be  fixed in @KDSBrowne's PR #6305

**Comment by antobinary** [comment]
Now that #6305 is merged we can close this PR

**Pull request closed without merging**
