### PR TITLE
Mute locked users instead of removing audio.

### LINKED ISSUE #7001: Locking microphones should mute (not disconnect) audio for viewers
Currently, in the HTML5 client when a student joins with two-way audio and a moderator locks the audio to listen only, the user gets disconnected from audio and rejoined as listen only.

While this is the optimal approach (the listen only stream will take less CPU), it's not ideal for the user when the moderator takes away the lock.  The student needs to leave the audio and rejoin again with their microphone.

Change this so when microphone lock is applied to viewers, the viewers who have joined with their microphone are muted and are unable to un-mute until the lock is removed.

### PR DESCRIPTION
**Pull request by Tainan404**
Closes #7001.

### CODE REVIEW

**Comment by Tainan404** [comment]
This issues are related with akka because the message requesting the user unmute is sent, but the akka isn't responding.

Unlock:
```
1) "pmessage"
2) "*"
3) "to-akka-apps-redis-channel"
4) "{\"envelope\":{\"name\":\"MuteUserCmdMsg\",\"routing\":{\"sender\":\"bbb-apps-akka\"}},\"core\":{\"header\":{\"name\":\"MuteUserCmdMsg\",\"meetingId\":\"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1552492953109\",\"userId\":\"w_yt20xnn51bs2\"},\"body\":{\"userId\":\"w_yt20xnn51bs2\",\"mutedBy\":\"w_yt20xnn51bs2\",\"mute\":false}}}"
1) "pmessage"
2) "*"
3) "to-voice-conf-redis-channel"
4) "{\"envelope\":{\"name\":\"MuteUserInVoiceConfSysMsg\",\"routing\":{\"sender\":\"bbb-apps-akka\"}},\"core\":{\"header\":{\"name\":\"MuteUserInVoiceConfSysMsg\",\"meetingId\":\"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1552492953109\"},\"body\":{\"voiceConf\":\"79712\",\"voiceUserId\":\"8\",\"mute\":false}}}"
1) "pmessage"
2) "*"
3) "from-voice-conf-redis-channel"
4) "{\"envelope\":{\"name\":\"UserMutedInVoiceConfEvtMsg\",\"routing\":{\"voiceConf\":\"79712\"}},\"core\":{\"header\":{\"name\":\"UserMutedInVoiceConfEvtMsg\",\"voiceConf\":\"79712\"},\"body\":{\"voiceConf\":\"79712\",\"voiceUserId\":\"8\",\"muted\":false}}}"
```


Lock: 
```
1) "pmessage"
2) "*"
3) "to-akka-apps-redis-channel"
4) "{\"envelope\":{\"name\":\"MuteUserCmdMsg\",\"routing\":{\"sender\":\"bbb-apps-akka\"}},\"core\":{\"header\":{\"name\":\"MuteUserCmdMsg\",\"meetingId\":\"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1552492953109\",\"userId\":\"w_yt20xnn51bs2\"},\"body\":{\"userId\":\"w_yt20xnn51bs2\",\"mutedBy\":\"w_yt20xnn51bs2\",\"mute\":false}}}"

```

**Comment by capilkey** [comment]
Good catch. There's a bug in the akka-apps message handler for the mute/unmute of unlocked viewers.

**Comment by jfsiebel** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/master/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/MuteUserCmdMsgHdlr.scala#L38

**Comment by capilkey** [comment]
Yup. Just needs a check for `requester.locked` in the preceding if

**Pull request merged**
