### PR TITLE
Services run as starting PID

### PR DESCRIPTION
**Pull request by MarcelWaldvogel**
The starting scripts now `exec` the main service instead of starting it as a subprocess, avoiding the need for an (unnecessary) parent shell hanging around. Also in line with docker-entrypoint recommendations.

### CODE REVIEW

**Comment by antobinary** [comment]
@MarcelWaldvogel  Thank you for your contribution! Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

**Comment by MarcelWaldvogel** [comment]
Indeed, I have (I just sent it to Fred)

**Comment by antobinary** [comment]
Thank you - we received it!

**Comment by MarcelWaldvogel** [comment]
I had deleted my fork in the meantime, after which even recreating the fork does not allow to update the PR again. So I had to create an new PR, #11884, replacing this one.

**Pull request closed without merging**
