### PR TITLE
Reduce freeswitch log level

### PR DESCRIPTION
**Pull request by fireba11**
disables the freeswitch log levels console and debug by default
this prevents the logfile from growing to several GB really fast, defaults shound not log in debug mode

### CODE REVIEW

**Comment by fireba11** [comment]
Helps with #10065
Adresses #9471

**Comment by fireba11** [comment]
Fixes #7236 (log rotation due to age aka daily doesn't seem to be an option. i would have prefered to rotate daily with 14 files ...)

**Comment by danimo** [comment]
Also, I would suggest that freeswitch logs to the systemd journal by default (e.g. via stderr). That way, sysadmins have more choice over retention. To comply with GDPR, one has to state retention times independent of log size. Everything that logs to the journal pretty much automatically can be made compliant by configuring journalling policies.

**Comment by fireba11** [comment]
@danimo sounds like a good idea but i found no hint in the freeswitch docs on how to do that. feel free to improve if you know a way :-)

**Pull request merged**
