### PR TITLE
refactor: Removed configXML from bbb-web

### LINKED ISSUE #11861: Bbb-web: Remove config.xml from BigBlueButton 2.3
**Describe the bug**
BigBlueButton 2.3-beta-2 still attempts to load `config.xml` as shown in the nginx error logs

```
open() "/var/www/bigbluebutton-default/client/conf/config.xml" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: bbb.my.site, request: "GET /client/conf/config.xml HTTP/1.1", host: "bbb.my.site"
```

**To Reproduce**
1. Install 2.3-beta-2
2. Launch the BigBlueButton client
3. Check the nginx error logs

**Expected behavior**
The server should not attempt to load `config.xml`

### PR DESCRIPTION
**Pull request by antobinary**
### What does this PR do?

Removes obsolete `config.xml` references - remnant of the Flash client, not supported since BBB 2.2.x-2.3.x

### Closes Issue(s)

Closes #11861

### Motivation
Cleanup

### More:
1. Do I need to remove `setPollXML` ?
2. Do I need to remove ClientConfigService
`/var/bigbluebutton/configs`

### CODE REVIEW

**Comment by antobinary** [comment]
Related to #12426 but for Milestone 2.4

**Review by pedrobmarin — APPROVED** [review]
I think this covers up all config.xml related content from bbb-web and common-web. I ran it locally and looks stable too.

Still something config.xml related at bbb-demo but I don't think we need to worry about it.

**Comment by pedrobmarin** [comment]
Regarding `setPollXML` and `ClientConfigService`, not sure about that either. Can't remember if I used any one of them ever.

**Comment by antobinary** [comment]
Created a separate issue for `ClientConfigService` #12458 
About `setPollXML` - I will wait.

**Pull request merged**
