### PR TITLE
Bump to 2.2-beta-21

### PR DESCRIPTION
**Pull request by ffdixon**

### CODE REVIEW

**Comment by mkpelletier** [comment]
I'm looking forward to the release, Fred!  There are quite a number of changes in this cycle. Thanks for all the hard work!

**Comment by ffdixon** [comment]
Thanks @mkpelletier -- we're now running a candidate for beta-21 on [https://demo.bigblubutton.org/](https://demo.bigblubutton.org/).  If you can try finding a bug there, that would be helpful as we can look at fixing it before beta-21 is released.

**Comment by german2209** [comment]
Hi Fred,
It seems that demo server is not working.
Regards,
German Acevedo
[image: image.png]

**Comment by GhaziTriki** [comment]
@german2209 The demo server is working, there is a just a typo in the URL. The correct URL is https://demo.bigbluebutton.org/

**Comment by ffdixon** [comment]
Fixed typo :-)

**Pull request merged**
