### PR TITLE
fix(userdata): consistent breakout room userdata

### PR DESCRIPTION
**Pull request by frankemax**
### What does this PR do?
Found a more consistent space in bbb-web to merge the userdata, without relying 
on queries and iterations over MongoDB on user join.

### Closes Issue(s)

Closes https://github.com/bigbluebutton/bigbluebutton/issues/14139

### CODE REVIEW

**Comment by antobinary** [comment]
Nice!!
I see three experienced developers worked on this. Does it need additional testing on 2.4?

**Comment by frankemax** [comment]
> Nice!! I see three experienced developers worked on this. Does it need additional testing on 2.4?

I've tested it with some userdatas that we use normally. Maybe it's nice for someone else (who wasn't involved with the task) to take a look.

**Comment by pedrobmarin** [comment]
The trained eye can notice the part I screwed over at the first commit was fixed. So at least one round of shame already happened in this refactor.

**Review by antobinary — APPROVED** [review]
Worked well locally! Thanks!

**Pull request merged**
