### PR TITLE
feat(camera): set camera brightness

### LINKED ISSUE #15572: Increase/Decrease camera brightness
**Is your feature request related to a problem? Please describe.**
Camera brightness.

**Describe the solution you'd like**
It would be cool to be able to increase and decrease camera brightness by using a slider.

**Describe alternatives you've considered**
n/a

**Additional context**
I think HTML Canvas API allows to do it without much work.

Feature proposed by @TiagoJacobs.

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

Implements configuration of brightness for webcams.

**High brightness (only on camera)**

**Low brightness (only on camera)**

**High brightness (including virtual background)**

**In Visual Effects modal**

### Closes Issue(s)

Closes #15572

### Motivation

n/a

### More

You can disable it through `enableCameraBrightness` in `Settings.yml`.

### CODE REVIEW

**Comment by antobinary** [comment]
Very nice! Looks like @TiagoJacobs suggested / encouraged the idea :mango:

**Review by ramonlsouza — APPROVED** [review]

**Comment by prlanzarin** [comment]
This pull requests runs the segmentation code + background worker even if brightness is not altered and no camera effect is applied from a cursory reading.
If that reading is correct, consider:
  - Segmentation code is _expensive_. Don't run it if not necessary.
  - This probably will break camera sharing in Safari. If that's the case, add Safari to the ignore list as it's done for virtual background effects.

**Comment by prlanzarin** [comment]
^ verified that both of the items above are issues.

**Comment by JoVictorNunes** [comment]
@prlanzarin

To address both items we can block brightness configuration when no background is selected.

**Comment by prlanzarin** [comment]
Does it make sense to couple brightness to background effects? If it does, then yes, that's one way of tackling the regressions.

**Pull request merged**
