### PR TITLE
Feat(whiteboard): Selectable annotations, which can be moved, removed, brought back and forward

### LINKED ISSUE #2351: Move/edit whiteboard objects
Originally reported on Google Code with ID 1599

```
Currently, when the presenter draws on the whiteboard, the object is fixed.  For example,
they can't move/resize the square after it is drawn, nor can they edit a text field.

Add editing of objects to the whiteboard.
```

Reported by `ffdixon` on 2013-07-28 14:24:37

### PR DESCRIPTION
**Pull request by hiroshisuga**
### What does this PR do?

Enables users to select annotations by clicking. Selected annotations can be moved, removed, and brought back and forward. 
I constructed this PR upon a couple of other PRs, thus it may need some more work if we want a "pure" version by removing the other PRs (<s>I will do it when necessary</s> edit: done in #14540). Sorry for the inconvenience, but that's how I did it... for testing the concept, this form of PR should be good enough.
"The other PRs" include #11021, #11018, #11776, #10737 (already merged for 2.5), #11629, #13674 (already merged for 2.5), and #13728 (already merged for 2.5). 
To select multiple annotations, you click them with the control key down. For selecting all, Alt+Shift+A is the shortcut, although you can select only your annotations on the multi-user mode. To remove, push BackSpace or Delete key after the selection. To bring annotations forward and backward, ']' or '[' (square brackets) does the job.

### Closes Issue(s)

Closes #2351, #6026, #10770(?).

### Motivation

Whiteboard enhancement is one of the most demanded features. 

### More

As I stated in #2351, I am not keen to implement scaling and rotating functions (although not difficult), as they are not so useful for teaching as other functions. I believe reinventing Adobe Illustrator is not the way to go. 
For tablets, currently <s>only moving an annotation is possible</s>, unless the  user has a keyboard. It's more about the philosophy of UI design, so I leave this immature (update: removing function has been implemented).  
Recording and playback should also work properly, but for playing back eraser and marker pen, you need to modify the player (see https://github.com/bigbluebutton/bbb-playback/pull/129).

Below is an example of how the selection, moving, and removing functions work. For selection, you click exactly on the shape, not on the area of bounding box, although I allow a margin for a very thin line.
142139123-7936831b-d33a-4328-910f-3d2e3a542328

Below is another example showing how the bringing back and forward function works on multi-user mode. You will see that the movement of annotation is only transmitted to non-presenters when the presenter finishes the operation, so the network traffic should not be so heavy. In this example, I used the isolated whiteboard function (#11776) (BTW this is very useful for making a small exam). So you see a 'B' letter of a non-presenter (top-left screen) is not displayed for the other non-presenter (bottom-left screen) who drew 'C' letter, although both B and C are displayed for the presenter (right), who drew the 'A' letter. Once exited from the isolated multiuser mode, the presenter can edit everything.
select

Here is another example. This PR includes the eraser (#11018) and the marker pen (#11021) function, to show my idea of whiteboard enhancement. Even with the removing selected annotation function implemented, I think we still need the eraser function to precisely remove a part of drawing. #11018 does the job by drawing a rectangle with background texture. #11021 is originally a marker pen, but by choosing white color, you can use it as an eraser pen (but it's CPU-intensive for the presenter). You can select and move/remove/reorder the erasers as well (when moved, it erases where it is settled, bearing the destination texture).
eraser

My design policy is to implement these functions as simple as possible (i.e. respecting the original design) so that the user's confusion and the maintenance effort would be minimised. As seen in the discussion in #2351 and #13634, there are a couple of other projects which look very promising. I'd be happy anyway, if the BBB bears a better whiteboard in the end, regardless of which one is "selected and brought forward" by the community.  

Update: [TODO] probably the whiteboard-overlay directory is the better place to put the main codes than the presentation-overlay. 
  -> I think presentation-overlay is still a reasonable place because this PR re-uses the pan tool for annotation selection and the pan tool is implemented in the presentation-overlay

Update: implemented the annotation removal function on a touch panel, you flick after selecting annotations.

### CODE REVIEW

**Comment by ffdixon** [comment]
This is an impressive bit of work Hiroshisuga.   Thank you for submitting this pull request!

**Comment by czange** [comment]
@hiroshisuga do you consider this ready for production - or what is needed to make it production ready?

**Comment by hiroshisuga** [comment]
@czange , this PR is based on version 2.4b4, but should be compatible to the latest 2.5b5. For installing it, please refer to https://docs.bigbluebutton.org/2.4/dev.html . In short, you upgrade your server to 2.4b4 or more, and then download the source code, and deploy the html5-client, bbb-web, and akka-apps, following to the instruction.

**Comment by hiroshisuga** [comment]
I reverted akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/SendWhiteboardAnnotationPubMsgHdlr.scala, because #13803 removed the condition of annotation.annotationType to be PENCIL_TYPE or MARKER_TYPE.

**Comment by hiroshisuga** [comment]
Update: fix a bug of unmovable drawings on a touch panel.

**Comment by hiroshisuga** [comment]
Adaptation to 2.4.0 official release. I would be grateful if someone reports if it works.

**Comment by hiroshisuga** [comment]
A bug in recording fixed

**Comment by hiroshisuga** [comment]
A strange race condition solved. It happened only in production mode.

**Comment by hiroshisuga** [comment]
Update: added removing annotations by a flick on a touch panel.

**Comment by hiroshisuga** [comment]
Some cosmetic modifications and fixing a hidden bug in flicking on a touch panel.

**Comment by antobinary** [comment]
Thank you @hiroshisuga ! We will be closing this pull request as we are way past the point of merging features into BBB 2.4. More about the current state of the whiteboard on 2.6: https://github.com/bigbluebutton/bigbluebutton/issues/14976#issuecomment-1337642764

Thanks again!

**Pull request closed without merging**
