### PR TITLE
Switch from PNG to SVG image generation for HTML5 client.

### PR DESCRIPTION
**Pull request by gthacoder**
- Starts serving HTML5 client with SVG images.
- Speeds up the total time to convert presentation (by reducing the time of additional image generation for HTML5 client).

### CODE REVIEW

**Comment by ritzalam** [comment]
When you join with the Flash client, is the default presentation showing up? And when you upload a PPT presentation, does it get converted?

I'm testing it and I don't see the default presentation when joining using Flash and I get logged out when I upload a PPT presentation.

I'm tracking if there's an exception in Red5 handing the presentation conversion.

**Comment by ritzalam** [comment]
Do we need to install dependencies? pdftocairo?

**Comment by gthacoder** [comment]
Yes, we need to install Poppler: sudo apt-get install poppler-utils.

**Comment by ritzalam** [comment]
Yes I have that. 

I think the problem is in bbb-commons-message. Need to create a new jar file.

**Pull request merged**
