### PR TITLE
feat: Fill shape in whiteboard

### LINKED ISSUE #9076: Filled shapes in the whiteboard
Previously in the Flash client it was possible to draw filled shapes, it is useful for masking some parts of the text live. Currently the HMLT5 client only draws shapes with an outline but with a gap inside.

### PR DESCRIPTION
**Pull request by hiroshisuga**
### What does this PR do?

enables filling shapes in whiteboard with ctrl key down.

### Closes Issue(s)

closes #9076
related to #6026 

### Motivation

Filling shapes in whiteboard would be useful. It can also be used as an eraser with a white filling. 

### More

Cannot be used on a smart phone which does not have ctrl key. Compatible with a pen tablet if you have a keyboard as well. Recording also works.

screen

### CODE REVIEW

**Comment by hiroshisuga** [comment]
A bug fixed. Compatibility with 2.3a3 confirmd.

**Review by KDSBrowne — APPROVED** [review]
Tested, and it works great! Code looks good, it's actually really neat to have the fill functionality. We will still need a way to inform the user of this feature, at the moment it's basically hidden.

**Comment by GhaziTriki** [comment]
@KDSBrowne This feature was present in the old Flash client, a lot of users are expecting it back.

**Comment by KDSBrowne** [comment]
@GhaziTriki This was already approved.

**Comment by mrkeksi** [comment]
Hey hiroshisuga you are doing great work to improve the whiteboard. Since a paint bucket (fill tool) like in Photoshop is probably impossible to do, I can understand your decision to add the fill directly when drawing. However, I find solutions that are not obvious (hidden) problematic for the end user. How about an extra toggle to turn on and off that only appears when you select one of the three tools (rectangle, triangle, circle)? Then the whole thing would also work on mobile devices. 
Good work. Keep it up.

image
*Paint Bucket from Bootstrap Icons 

I don't know if you should put the icon in the color dropdown? And when the toggle is on the bucket is filled with the color or black.

**Comment by mrkeksi** [comment]
You're right about that. Tooltips are also read through the fewest, right? I think, so important tools will be implemented in the course of 2.3 (or 2.4 when it comes as the next major version). To avoid the problem of a too big dropdown menu you can also split these tools into 2 columns. Also with regard to the eraser and highlighter the bar would have to be adapted anyway. How about extra icons for each tool with a background then (not like I did quickly now).

image

```
this an small outer css changes:
.toolbarList {
    display: grid;
    grid-auto-flow: row;
    grid-template-rows: var(--toolbar-button-height) var(--toolbar-button-height);
    grid-template-columns: var(--toolbar-button-height) var(--toolbar-button-height);
    position: absolute;
    right: var(--toolbar-button-height);
    top: 0;
    box-shadow: var(--toolbar-box-shadow);
}
```

**Comment by hiroshisuga** [comment]
Update for adapting the PR #11224

**Comment by antobinary** [comment]
Hi @hiroshisuga 
Thanks for this feature!

@jfsiebel just tested it against branch `develop` (which is the base for the upcoming BBB 2.5)

**Review by jfsiebel — COMMENTED** [review]
Didn't find any problem in html5 client while testing, ~~the only problem found was in recordings, where the shape wasn't filled~~. (events.xml was correctly marked with fill property)

EDIT
Recording is working fine.

**Review by jfsiebel — APPROVED** [review]

**Comment by hiroshisuga** [comment]
Hi @jfsiebel @antobinary , thanks for notification. What was the problem of recording?

**Comment by hiroshisuga** [comment]
Sorry, I haven't noticed your edit. Great to hear that the recording is also working!

**Comment by danielpetri1** [comment]
@hiroshisuga @jfsiebel The problem arises with older recordings where the fill property is not present. Calling `text` on a nil XPATH fill value fails. I would suggest something like

```ruby
fill = event.at_xpath('fill')
fill = fill.nil? ? fill.text : "false"
shape[:fill] = fill =~ /true/ ? true : false
```

**Comment by hiroshisuga** [comment]
Hi @danielpetri1 , thanks for pointing it out. Agreed. Would you mind posting it as a new PR?

**Comment by danielpetri1** [comment]
@hiroshisuga sure, I'll include it in #13836.

**Pull request merged**
