### PR TITLE
Fix bbb-conf (indent)

### PR DESCRIPTION
**Pull request by BaseMax**
### What does this PR do?

- Fix bbb-conf (indent)
- bbb-conf: remove extra line inside check_state func

### Related PR

#14288 #14287

### Motivation

Happy by helping BBB team
And would like to do more, just looking to know what needed.

Sorry, I am new here. I have to add a row inside **Changelog** comments?

### CODE REVIEW

**Comment by BaseMax** [comment]
Hey, Did I work on the wrong branch?

**Comment by antobinary** [comment]
Just to confirm -- your pull request is targeting `v2.4.x-release` branch, i.e. BigBlueButton 2.4
Given the scope of the changes, this is the appropriate branch!

**Comment by BaseMax** [comment]
> Could you please confirm if you already sent in the signed Contributor License Agreement? 

Hey Anton @antobinary
Yes agreed, I am a new contributor but I did a small merged commits in `bbb-install` too. Thanks

**Comment by BaseMax** [comment]
> but for BigBlueButton core we do need a CLA.

Hi Fred, Thank you. I printed and signed the papers and send to you. @ffdixon

**Comment by BaseMax** [comment]
Still pending?

**Comment by antobinary** [comment]
@ffdixon please confirm if we have the CLA

**Comment by antobinary** [comment]
Hi @BaseMax 
I will be closing this PR. The changes are whitespace only, the destination is a branch which is (at this point) essentially only meant for fixes/patches, the CLA process is proving inefficient in this case (out of your or my control)... I don't feel comfortable asking you to re-send again only to have indentation tweaked.
This is not intended to be a discouraging action... I hope you have good experience with BBB as a product and you'd still consider contributing in the future whether it's bbb-install or BBB itself

**Comment by ffdixon** [comment]
Ditto!

**Pull request closed without merging**
