### PR TITLE
Draft: Deletion of whiteboard annotations with react-selecto and react-moveable

### LINKED ISSUE #2351: Move/edit whiteboard objects
Originally reported on Google Code with ID 1599

```
Currently, when the presenter draws on the whiteboard, the object is fixed.  For example,
they can't move/resize the square after it is drawn, nor can they edit a text field.

Add editing of objects to the whiteboard.
```

Reported by `ffdixon` on 2013-07-28 14:24:37

### PR DESCRIPTION
**Pull request by MW360**
### What does this PR do?

Delete whiteboard objects with integration of [react-selecto](https://www.npmjs.com/package/react-selecto) and 
[react-moveable](https://www.npmjs.com/package/react-moveable) library. 
For selection, an extra tool gets added to the whiteboard toolbar.

### Closes Issue(s)

Partially resolves #2351

### Motivation
Improve the teaching experience with the whiteboard as part of my bachelor thesis. 

### More

This is just a draft PR as it is still work in progress. 

There are still some aspects missing which get implemented in near future: 
- [x] Selection tool needs to be decoupled from other tools
- [ ] Introduce unique icon and mouse pointer for selection tool
- [x] Selection needs to be updated after deletion 
- [x] Akka Apps component needs to be adjusted to handle undo after delete -> in collaboration with @Gigate #13987
- [x] Restrict deletions and edits of annotations to their creators -> postponed and moved to #14065
- [x] Update of common message interface accordingly
- [ ] Check implications for recording system -> related to #13987
- [x] Implement SelectByClick
- [x] Add keyboard shortcut for deleting
- [x]  Clear whiteboard on delete button when no item is selected and merge delete buttons

### CODE REVIEW

**Comment by hiroshisuga** [comment]
Congratulations to your first successful integration of react-selecto and react-movable modules! I am looking forward to the upcoming works. 
I haven't tested your code yet, but I just wonder what would happen on the multi-user whiteboard mode. Can everybody move and delete whatever annotations he wants? Or only the annotation drawer can manipulate what he draws?

**Comment by MW360** [comment]
Hi @hiroshisuga,
Thank you! 
The plan is to only allow deletions and edits of your own annotations.
However, I have not implemented it, yet.
I forgot to add it to the above todo list.

**Comment by MW360** [comment]
Hi all,
although there are two items remaining on task list, I am marking this issue as ready for review. 

This PR is tightly coupled to #13987 and does rely on its common-message interface and apps akka implementation.
Therefore, it is pending on it before it can be merged.

However, core feature is developed and can be reviewed.

**Comment by KDSBrowne** [comment]
The UI functionality allows you to click and select a given annotation or drag to select 
multiple. Once an annotation is selected a delete option is displayed to allow for removal.
(we may want to improve the UI for this). There is also a UI bug where the selection outline
overlaps the toolbar on smaller screens.
selection_over_toolbar


Notes:
1) The selection state has been updated with a cleaner approach:
https://github.com/MW360/bigbluebutton/tree/reactive_selection_state


2) The react-movable issue with the presentation overlay consuming events was addressed 
with a new whiteboard architecture which wraps the overlays around the whiteboard’s SVG:
https://github.com/MW360/bigbluebutton/tree/svg_inside_of_overlay_approach

**Comment by KDSBrowne** [comment]
After Discussing with @tylercopeland  the expected behavior for the delete button should be as follows:
Only display 1 delete button.
1 - If an annotation is selected and I clicked the delete icon, it would delete the selected annotation
2 -  If no annotation is selected and I clicked the delete icon, it would delete all previously created

**Comment by MW360** [comment]
@KDSBrowne  thank you for the feedback! 
>  There is also a UI bug where the selection outline overlaps the toolbar on smaller screens. selection_over_toolbar

Should now be fixed.
Further an issue is fixed that caused rendering / selection bugs when toggling to full screen mode.
There was also a problem with switching the current slide which is now fixed.

Fixes mentioned above are only in https://github.com/MW360/bigbluebutton/tree/reactive_selection_state at the moment.

> After Discussing with @tylercopeland the expected behavior for the delete button should be as follows: Only display 1 delete button. 1 - If an annotation is selected and I clicked the delete icon, it would delete the selected annotation 2 - If no annotation is selected and I clicked the delete icon, it would delete all previously created

Good idea!
I added it to the todo list above.

**Pull request closed without merging**
