### PR TITLE
fix(user-list): center icons on safari

### LINKED ISSUE #18763: Userlist icons are misaligned on Safari/IOS and Safari/macOS
**Describe the bug**
The icons indicating the presenter and the joined audio mode are misaligned in the user list when using the Safari browser on IOS and macOS.

**Screenshots**
- Safari/iOS
misalignment

- Safari/macOS
misalignment macos

**BBB version:**
v2.6.x-release

### PR DESCRIPTION
**Pull request by Arthurk12**
### What does this PR do?

Centers icons indicating presenter, audio state and whiteboard access in the user list.

### Closes Issue(s)
Closes #18763

### CODE REVIEW

**Review by ramonlsouza — CHANGES_REQUESTED** [review]
is works well for safari, but not for chrome in ios (and possibly other browsers in ios)

**Comment by Arthurk12** [comment]
> is works well for safari, but not for chrome in ios (and possibly other browsers in ios)
> 
> 

When attempting to join a meeting using Chrome I see this warning:
unsup

It seems that Safari is the only supported browser on IOS devices.

**Comment by ramonlsouza** [comment]
> > is works well for safari, but not for chrome in ios (and possibly other browsers in ios)
> > 
> 
> When attempting to join a meeting using Chrome I see this warning: unsup
> 
> It seems that Safari is the only supported browser on IOS devices.

Ok! Looks like our browser detection is not working well, but that's a different issue then (I did not see this message in chrome 117 for ios)

**Review by ramonlsouza — APPROVED** [review]

**Comment by ramonlsouza** [comment]
upon further investigation, looks like we do support Chrome (see https://github.com/bigbluebutton/bigbluebutton/pull/13635 and https://github.com/bigbluebutton/bigbluebutton/pull/13562) - and possibly other browsers too, as long as they are recent versions (https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/bigbluebutton-html5/private/config/settings.yml#L977-L1001)

**Comment by Arthurk12** [comment]
> upon further investigation, looks like we do support Chrome (see https://github.com/bigbluebutton/bigbluebutton/pull/13635 and https://github.com/bigbluebutton/bigbluebutton/pull/13562) - and possibly other browsers too, as long as they are recent versions (https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/bigbluebutton-html5/private/config/settings.yml#L977-L1001)

Yeah, but this doesn't apply to iOS devices because there's a line of code that specifically forces iOS devices to use Safari. See:
https://github.com/bigbluebutton/bigbluebutton/blob/32d6532308f3ac9a6596f445049be80eb6b3eb63/bigbluebutton-html5/imports/ui/components/legacy/component.jsx#L158

**Comment by ramonlsouza** [comment]
> > upon further investigation, looks like we do support Chrome (see #13635 and #13562) - and possibly other browsers too, as long as they are recent versions (https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/bigbluebutton-html5/private/config/settings.yml#L977-L1001)
> 
> Yeah, but this doesn't apply to iOS devices because there's a line of code that specifically forces iOS devices to use Safari. See:
> 
> https://github.com/bigbluebutton/bigbluebutton/blob/32d6532308f3ac9a6596f445049be80eb6b3eb63/bigbluebutton-html5/imports/ui/components/legacy/component.jsx#L158

This line will only by checked if legacy component is rendered, and it is only rendered if browser version is less than the one listed in `minBrowserVersions`... for ios chrome it will only trigger for < 94. I have latest chrome on ios 17 (chrome 117) and legacy component does not appear when I join

**Review by ramonlsouza — APPROVED** [review]

**Pull request merged**
