### PR TITLE
implement anonymous polls option

### PR DESCRIPTION
**Pull request by schrd**
### What does this PR do?

Sometimes it is desirable to have an option for anonymous polls - think
of "How did you like my presentation?".

This patch changes three components in the HTML5 client:

* add anonymous option to poll creation form
* do not display user responses in live result for anonymous polls
* indicate whether poll is anonymous to users

In the poll creation form there is a text explaining what is going on.
It changes together with the toggle: I don't know if this is a problem
for accessibility if texts change if a switch is toggled. Should this be
the case, this has to be changed.

### Screenshots

Poll creation:
poll_anonymous

Live results:
poll-liveresult

Polling:
polling

### Closes Issue(s)

none

### Motivation

Students may hesitate to give honest feedback if they know that instructors can see who voted for which option.

### More

I added the anonymous flag to the akka-apps messages. I don't know if this is desirable or not.

This adds new messages that have to be translated.

### CODE REVIEW

**Comment by pedrobmarin** [comment]
Anything wrong with this https://github.com/bigbluebutton/bigbluebutton/pull/12430?

**Comment by schrd** [comment]
uh ehrm, no. I missed this one while I was working on my patch.

**Comment by pedrobmarin** [comment]
Either way, thanks for you contribution, @schrd . I'll leave it to @germanocaumo decide the one he likes the most.

**Comment by antobinary** [comment]
Hi @schrd, could we focus the remaining efforts on #12430 by closing this pull request?
https://github.com/bigbluebutton/bigbluebutton/pull/12430#issuecomment-847794876

Thank you for this work!

**Comment by schrd** [comment]
> Hi @schrd, could we focus the remaining efforts on #12430 by closing this pull request?
> [#12430 (comment)](https://github.com/bigbluebutton/bigbluebutton/pull/12430#issuecomment-847794876)
> 
> Thank you for this work!

sure

**Pull request closed without merging**
