### PR TITLE
Add ability to hide viewers in the user list from each other

### LINKED ISSUE #7896: Add create property to mask viewers from other viewers
For some classes, the instructor may want to prevent a student from seeing other students in the class.  An example might be students who are incarcerated who are taking an online class.

Add parameter, such as`filterViewersInUsersList`, so each viewer only sees themselves and other moderators in the Users list.

### PR DESCRIPTION
**Pull request by capilkey**
This PR adds a new lock setting to hide viewers from each other. In order to do the filtering I had to do the refactor work in https://github.com/bigbluebutton/bigbluebutton/pull/7908 first. Once that is merged this PR will be easier to read.

Fixes #7896

### CODE REVIEW

**Comment by antobinary** [comment]
Closes #7099

**Comment by antobinary** [comment]
Looks like the requirement is for a visual hiding of the users, while the alternative implementation of filtering users before they are sent to the clients would introduce some challenges we'd like to avoid for as long as we could (cross viewer chat while temporarily promoted to moderator, acl to prevent direct communication api attempts, etc)

**Comment by soheilrahsaz** [comment]
It would also be great if we could hide only one person. For example, we have a lot of classrooms and then the site admin wants to check the classes to see whether they're running ok and teachers are teaching the way they should or not. It would be great if the admin could do this anonymously.

**Comment by iSamof** [comment]
@soheilrahsaz - good idea but as this thread is closed you may want to contribute to a similar one about dropping in to a room without being listed. I saw it a few weeks ago.

**Pull request merged**
