### PR TITLE
Fix bigbluebutton/bigbluebutton#2710

### PR DESCRIPTION
**Pull request by tdj-br**
Fix bigbluebutton/bigbluebutton#2710

### CODE REVIEW

**Comment by ritzalam** [comment]
Hey @capilkey, are you able to do a quick test and merge Tiago's PR? Thanks.

**Comment by capilkey** [comment]
Newly joined clients are getting the last pushed layout as expected, but when I first load up the client (before a layout has been pushed) there is no layout applied at all. See the attached screenshot for an example.

image

You can see that the windows are in the incorrect positions and no layout has been applied (should be the default instead).

**Comment by tdj-br** [comment]
That's true! Will fix it right now.

**Comment by capilkey** [comment]
Looks good. The default layout is applied if no layout has been pushed and if the layout has been pushed new users will get the layout.

**Pull request merged**
