### PR TITLE
refactors Learning Dashboard and add new functionalities

### LINKED ISSUE #13507: Learning dashboard enhancements
### Highlighted Card
Screen Shot 2021-10-17 at 2 18 43 PM

With this approach, we are looking to provide users with a clear understanding of the data detailed below the series of cards. Furthermore, since we are already displaying the light on the cards (left accent), we can repurpose this style as the lighted card.  

- Remove the left border colour by default
- If/when a user selects a card item, a border colour appears to the left, indicating that the content type will is selected
- We can repurpose the left border as the hover state as well. 

### Polls Empty State
Learning Dashboard - Polls Empty State

### Last Update / Download Session Details

Learning Dashboard - 12

### Dim Offline Students
To make it more obvious who are offline students versus online students, we can reduce the opacity of offline students' data to 0.75. All but the Offline status pill. 

Screen Shot 2021-10-17 at 2 28 57 PM

### LINKED ISSUE #13570: Learning Dashboard timeline experience
### **Current implementation**
Screen Shot 2021-10-25 at 8 36 26 PM

### **Goal**
Extend our current "Raise Hand" experience to provide teachers with an overview of student interactions within a class in context of the presenter's slides.

### **Overview**
This feature has a few different pieces that would be new to the overall experience. 

**1) Display Tile**

Screen Shot 2021-10-25 at 8 51 34 PM
- This tile container displays the total number of emojis used during a session.  
- To the right of the title, we will display the different emojis used. If/when more than 3 emojis are used throughout a session, we will display the top three used throughout the session. 

**2) Table Header**
Screen Shot 2021-10-25 at 9 16 14 PM
- For the table header, we will keep it consistent with the other tables. Since we will only filter users within the table, the header should only display "Users."

**3) Slides**
Screen Shot 2021-10-25 at 9 16 40 PM
- The second row of the table will consist of slides presented during the session. A new slide will display within the row when a new slide changes. 
- Display an image of the slide and a timestamp

**4) User**
Screen Shot 2021-10-25 at 9 17 05 PM

- Following the slides row, we will display all the users who participated in a session
- Since we don't have avatar images today, we can simply use the same treatment under "Active Users"
- We will display their name 

**5) Timeline**
Screen Shot 2021-10-25 at 9 19 43 PM

- To the right of their name and under each slide, we will display a line representing their timeline during the session. 
- The beginning of the line will represent when the user joined the session, and the end of the line will be when they left 
- Whenever a user engages with an emoji or raises their hand, it will display a mark on the timeline. 
- The timeline mark will consistent with the icon representing the emoji in a purple circle
- Since this is a timeline experience, we will need to incorporate a horizontal scrolling experience.

### LINKED ISSUE #13598: Downloading information from the Learning Dashboard
As part of the latest updates to the Learning Dashboard, we'd like to provide our users with the ability to download the information captured during the session. 

The action of downloading the information would be a simple button at the bottom of the screen, which will download a .csv file storing all the information captured during the session.

Screen Shot 2021-10-28 at 10 17 55 AM

The .csv will contain all the information captures across all our tables and grouped together per user. It should look like the following screenshot.

Screen Shot 2021-10-28 at 10 16 59 AM

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

**Highlighted Card**

- Cards distributed in new order.
- Left border appears on the selected card.
- Left border repurposed as hover state as well.
- Smaller card icons.
- New timeline card.

Captura de tela de 2021-11-03 10-20-50-c

**New Polls Empty State**

Captura de tela de 2021-11-03 10-21-24-c

**New Footer**

- Global timestamp for when the session data was last updated.
- Global button for downloading the entire session data.

Captura de tela de 2021-11-03 10-21-04-c

**Offline Students**

- Opacity of offline students' data reduced to 0.75. All but offline status pill.

Captura de tela de 2021-11-03 10-20-50--c

**Timeline experience**

**1)** Card:

- Total number of emojis used during the session will be displayed to the left.
- The top three emojis will be displayed to the right.

Captura de tela de 2021-11-03 10-21-57-c

**2)** Timeline

Captura de tela de 2021-11-03 11-10-08-c

Captura de tela de 2021-11-03 11-14-34-c

### Closes Issue(s)
Closes #13507 
Closes #13570 
Closes #13598

### CODE REVIEW

**Comment by gustavotrott** [comment]
The new functionalities is amazing! Good work @JoVictorNunes!

**Comment by gustavotrott** [comment]
Can you make some tests using some RTL direction language?
You can include param `&lang=fa-IR` in the Url to make the tests.

timeline_rtl

**Comment by gustavotrott** [comment]
I didn't spend much time in the `Download session data` button once a new issue was opened to it #13598.
So it will be changed soon anyway.

**Comment by JoVictorNunes** [comment]
@gustavotrott, I have just pushed the updates, if you could try it out again would be nice!

Captura de tela de 2021-11-12 11-14-16

**Comment by JoVictorNunes** [comment]
Speaking about the Download button, yeah it will be changed soon, I am already working on it.

**Comment by gustavotrott** [comment]
Can you test the timeline with the attached Json? the timeline drawing is weird sometimes..
[learning_dashboard_data.zip](https://github.com/bigbluebutton/bigbluebutton/files/7546424/learning_dashboard_data.zip)
timeline_problems

**Comment by JoVictorNunes** [comment]
I fixed the error mentioned above. It was a minor logic error.

Captura de tela de 2021-11-18 10-20-36

**Comment by gustavotrott** [comment]
> I fixed the error mentioned above. It was a minor logic error.
> 
> Captura de tela de 2021-11-18 10-20-36

Cool! Not it works like a charm. Good work.

**Comment by gustavotrott** [comment]
The CSV is exported with all content in only one line.
image
image

Take a look in this topic.
https://stackoverflow.com/questions/38888534/r-n-characters-in-csv-file-not-treated-as-line-breaks

Consider using `encodeURIComponent()`.
Consider using `\r\n` instead of `\n` for better Windows compatibility.

Try to open the file to LibreOffice or MS Office to be sure it will be in the correct format.

Besides, what do you think about changing the file name to `LearningDashboard_$meetingName_$meetingDate(yyyy-mm-dd).csv`, instead of `session_data.csv` ?

**Comment by JoVictorNunes** [comment]
Thanks for the advice @gustavotrott. I will take a look at all of that.

**Comment by JoVictorNunes** [comment]
@gustavotrott I implemented the suggested changes. I think this will work properly this time.

Captura de tela de 2021-11-23 16-50-47

**Review by gustavotrott — COMMENTED** [review]
LGTM!

Great job @JoVictorNunes 👏

**Comment by JoVictorNunes** [comment]
Thanks you @gustavotrott

**Pull request merged**
