### PR TITLE
Adds compatibility with Electron Chromium to choose one screen to share

### PR DESCRIPTION
**Pull request by gustavotrott**
When using the screen share, Chrome and Firefox implements a functionality to choose which screen it should share.
In Electron it needs to be implemented manually. This code is to verify when the user is using Electron as client and then intercept the screen chooser with the Electron app implementation.

### CODE REVIEW

**Comment by forvim** [comment]
Test with https://github.com/wexond/desktop.git,  return err:
permission to access screen wasn't granted

**Comment by benjaminLedel** [comment]
Any example, how to use this with electron?

**Comment by abrantes01** [comment]
@benjaminLedel did you manage to use it with electron ?

**Comment by benjaminLedel** [comment]
@abrantes01 not really, we decided to not build an electron app.

**Comment by prlanzarin** [comment]
I also intend to drop support to whatever Electron code remains in the screen sharing module soon (ref #11025), so I'd suggest not relying on it.

**Pull request merged**
