### PR TITLE
refactor: Introduces user.raiseHand and user.away flags

### PR DESCRIPTION
**Pull request by gustavotrott**
Add new props `user.raiseHand` and `user.away` to the User collection:

````
{
    "_id" : "oBDopzCswyag7PaFS",
    "name" : "student 1",
    "emoji" : "happy",
    "emojiTime" : 1686228378070.0,
    "raiseHand" : false,
    "raiseHandTime" : 0,
    "away" : true,
    "awayTime" : 1686228378089.0
}
````

Both props used to be stored within `user.emoji` prop, but it became confusing (in special with the introduction of the feature Reactions).

This PR also:
- Add reactions to Learning Dashboard json (_TODO: missing UI changes to make use of it_)
- Handle user-notification differently when set or remove away status (instead of treating it as an Emoji)
- Include Reactions to the Userlist sorting
- Improve code of Reactions applying Lint rules and removing unnecessary imports

Closes (and motivation description): #18053

### CODE REVIEW

**Comment by Scroody** [comment]
If you don't mind I would like to add an extra emoji to the list of reactions, I think this one will be very useful for the community and also completes the columns, because depending on the resolution the list lacks and emoji at the end making it un-aesthetic. The emoji would be the: '1F920'.

**Comment by antobinary** [comment]
>'1F920'

https://emojipedia.org/cowboy-hat-face/
Totally unexpected @Scroody

**Comment by gustavotrott** [comment]
> Maybe we could use the same field for both since there's so much code overhead on akka / bbb-messages and html5 for adding a new field. But I'm ok if you guys think it's a good idea to keep it as two separate fields.

Hey, thanks for the review!
Yes, I understand your concern and I agree.
On the other hand, I created two different props in order to facilitate future maintenances (by developers that doesn't know it's used by two different things).
Each feature has a different behavior and store different type of data in `user.emoji`.
Reactions expire after 60 seconds.. EmojiStatus is handled depending of its content whereas EmojiReaction just show it's content.

I think separating things we will avoid problems!
For example, Reactions expire after 60 seconds.. let's say in the future we will move this "expire-process" to akka-apps, and the developer doesn't know about the existence of the legacy emojiStatus... and will make BBB always clear the `user.emoji` after 60 seconds.
Then we would have a bug!

For clarity, I think it makes sense to have two different props even if it costs us two more fields!

**Comment by lfzawacki** [comment]
Another thing about the current behavior. The raiseHand and away status do actually obscure the reaction emoji and this was by design, if the user is away or with a raised hand this should be shown instead of the emoji. We could change this but I think we might need a little redesign

**Comment by gustavotrott** [comment]
> Another thing about the current behavior. The raiseHand and away status do actually obscure the reaction emoji and this was by design, if the user is away or with a raised hand this should be shown instead of the emoji. We could change this but I think we might need a little redesign

Yes! The refactor keep this behavior!
But now it is a design option and not a technical limitation anymore... so it is an option to change it soon!

**Comment by gustavotrott** [comment]
Can we merge it @lfzawacki ?
Just checking if you are done with the review

**Comment by lfzawacki** [comment]
Merge away

**Pull request merged**
