### PR TITLE
fix: sharing external video does not stop screenshare

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

- Fixes an issue where sharing an external video in new layouts would not end screenshare
- Moves screenshare notifications from media container to screenshare component

### CODE REVIEW

**Comment by antobinary** [comment]
I am not sure if this is the best approach for solving the issue.
If we agree that we can only play one of [ external video, screenshare ] at a time, I would prefer if akka-apps was the one stopping screenshare, rather than bbb-html5 client deciding not to play it...
If we want to allow both to play simultaneously, we'd need to rethink layouts (and more).

Either way, unless I am missing some key point here, I am not sure about this client side decision

**Comment by prlanzarin** [comment]
> I am not sure if this is the best approach for solving the issue.
> If we agree that we can only play one of [ external video, screenshare ] at a time, I would prefer if akka-apps was the one stopping screenshare, rather than bbb-html5 client deciding not to play it...

I agree with akka-apps being the one ejecting it.

That being said: this PR restores the functionality as it was in 2.0/2.2/2.3 (essentially fixing a regression), so I'd treat re-doing the rejection control as a separate PR/issue.

**Comment by antobinary** [comment]
> I'd treat re-doing the ejection control as a separate PR/issue.

Created https://github.com/bigbluebutton/bigbluebutton/issues/12803

**Comment by erpsolns** [comment]
Instead if the settings for the meeting having an option in apps menu to disable and enable stop screenshare when external video initiated - that would not be regression - that is moving forward

**Pull request merged**
