### PR TITLE
Fix clipped username in chat and user list

### LINKED ISSUE #5287: Bug: Username displayed cut out in chat area

### PR DESCRIPTION
**Pull request by Tainan404**
- Add a padding for text overflow.

dev2: 
dev2-clip

PR:
pr-clip

closes #5287.

### CODE REVIEW

**Comment by OZhurbenko** [comment]
What happened to the message time?

**Comment by Tainan404** [comment]
I needed tweak the width to solve the problem, I talked to tyler and he said that this okay the time stay like this.

**Comment by jfsiebel** [comment]
image
In this case the user name overflow the chat message a little, should we consider Zalgo text @antobinary ?

`H͙̝͝ͅe̯̲͡ ͈̙̭ͅw̙͈̼͈̥̫̦͝h͉̩͓̲o̝̘̭̙͝ ̝͖̥̱ͅW̖̺̳͉͇̣ͅa̛͉̱̫į͇̯̦͚t̫͚̪̖͍͙͈͟s̜̤̗̗̳͝ ͏B̫̠͉ͅé̹͙͇͙h̼̻̝̖͚̮͠ͅi͔̪̟̣̗̦̤n̹̮̪̩d̰͉̤̹̪ͅ ̟̖͟T̝̭͍h̯̤́e̩̠̖̼̤ ͏͖̪͚̹̪W̸̭̣̣̟̝a͙̫͡l͏͍̮̦̤͉̭l̛͍.͍̣͙̗̦ͅ`

**Comment by jfsiebel** [comment]
image

The style isn't applied in messages where the user is offline

**Comment by jfsiebel** [comment]
image
Because of italic text there is a little clip in right, maybe change `font-style` or add a `padding-right`

**Comment by KDSBrowne** [comment]
Could you apply these changes to the clipping that happens in the open messages list as well?

ul-ss

**Pull request merged**
