### PR TITLE
Show 'To be uploaded...' toast upon breakout notes capture

### PR DESCRIPTION
**Pull request by danielpetri1**
### What does this PR do?
Displays a "To be uploaded..." toast in the main meeting while the shared notes of breakout rooms are being captured.

### Motivation
Previously, the instructor only got notified once the conversion of the captured notes began in the backend. This PR makes them aware that their request to bring back breakout slides is being processed as students come back from the breakout rooms.

### Video demonstration
https://user-images.githubusercontent.com/33319791/199790619-ac942e8b-b8c7-4215-8bf7-6bcb3225b167.mov

### CODE REVIEW

**Review by GuiLeme — APPROVED** [review]
LGTM!

**Comment by danielpetri1** [comment]
Before merging, please note that this PR depends on https://github.com/bigbluebutton/bbb-pads/pull/17 to function correctly.

**Comment by prlanzarin** [comment]
> Before merging, please note that this PR depends on [bigbluebutton/bbb-pads#17](https://github.com/bigbluebutton/bbb-pads/pull/17) to function correctly.

cc @danielpetri1 https://github.com/bigbluebutton/bigbluebutton/pull/15974

**Comment by danielpetri1** [comment]
Thank you @prlanzarin, all good to go then!

**Pull request merged**
