### PR TITLE
Fix wrong path in settings for audio constraints

### PR DESCRIPTION
**Pull request by mariogasparoni**
Using now 'application' instead of old 'audio' path

### CODE REVIEW

**Comment by mariogasparoni** [comment]
Thanks to @pedrobmarin  for pointing this out.

**Comment by maychine-fatima** [comment]
for safari 14.0.3 it gives an error Sip.sessionDescriptionHandler.... : Invalid Constraint

**Comment by daminebenq** [comment]
Just tested it on our 2.2 server:
image
image
No problems encountred.

**Comment by mariogasparoni** [comment]
Thanks @maychine-fatima  and @daminebenq.

All these changes went to 2.2.31. Upgrading to 2.2.32 should make no difference.

@maychine-fatima are you using any special config for audio constraints in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` ?  or the problem started after you upgrade to 14.0.3 ?

**Comment by maychine-fatima** [comment]
thank you, in first i didn't use any audio constraints in settings but after that i tested with the commented constrains in settings , and it gives me the same error, i tested directly with this version 14.0.3 as the last version that i got from the updates of Mac

**Comment by mariogasparoni** [comment]
I tested Safari 14.0.3 on iOS 14.4. No problem found. Seems to be related to macOs's Safari

**Comment by daminebenq** [comment]
I'm realizing the macOs tests on browserstacks available list, and the most recent version available i have in the list in 14.0.1
sorry, can't test on other newer versions.

**Comment by maychine-fatima** [comment]
thank you for your tests i will try with the BBB v.2.2.32

**Comment by maychine-fatima** [comment]
thank you all for your tests, iwill test in the same version as yours.

**Pull request merged**
