### PR TITLE
chore: bump bbb-presentation-video to 4.0.0-beta.4

### PR DESCRIPTION
**Pull request by antobinary**
### What does this PR do?
Adds a file to pull bbb-presentation-video and more importantly,
to pin the version of bbb-presentation-video that corresponds to the specific BBB
version.

### Closes Issue(s)

Closes # none

### Motivation
Also this allows us to list the change of version in the release notes.

### More

- [ ] More work needs to be done to actually include bbb-presentation-video into the CI, etc

### CODE REVIEW

**Comment by antobinary** [comment]
Hi @cod3r0k 
The link is in getRecordings response, I believe Greenlight should also list the video format like it does `presentation` in case you're using GL

**Comment by cod3r0k** [comment]
> Hi @cod3r0k The link is in getRecordings response, I believe Greenlight should also list the video format like it does `presentation` in case you're using GL

Dear @antobinary , Thank you for your message. 
That's great. Additionally, if the playback interface had a download button, it could be better. Due to the fact that the mp4 video is related to each playback URL.

Furthermore, I check the latest revision and I don't find any downloadable link in the `getRecordings` response. As before, it only has a playback URL.
image

**Comment by hostbbb** [comment]
this is what RC3 getRecordings returns  2 formats. seperate metadata.xml for the presentation and the video when video format configured.

Also the the downloaded does not have chat or captions with this new format.

I need to see if its possible to skip the presentation format as a step.

<playback>
<format>
<type>video</type>
<url>https://xxxxxxxx/playback/video/55ec9e9896860c97a26d6ecfcebbbbf8713d5c01-1676038177771/</url>
<processingTime>0</processingTime>
<length>8</length>
<size>0</size>
</format>
<format>
<type>presentation</type>
<url>https://xxxxxxxx/playback/presentation/2.3/55ec9e9896860c97a26d6ecfcebbbbf8713d5c01-1676038177771</url>
<processingTime>188295</processingTime>
<length>8</length>
<size>18865883</size>
</format>
</playback>

**Comment by cod3r0k** [comment]
> this is what RC3 getRecordings returns 2 formats. seperate metadata.xml for the presentation and the video when video format configured.
> 
> Also the the downloaded does not have chat or captions with this new format.
> 
> I need to see if its possible to skip the presentation format as a step. `<playback> <format> <type>video</type> <url>https://xxxxxxxx/playback/video/55ec9e9896860c97a26d6ecfcebbbbf8713d5c01-1676038177771/</url> <processingTime>0</processingTime> <length>8</length> <size>0</size> </format> <format> <type>presentation</type> <url>https://xxxxxxxx/playback/presentation/2.3/55ec9e9896860c97a26d6ecfcebbbbf8713d5c01-1676038177771</url> <processingTime>188295</processingTime> <length>8</length> <size>18865883</size> </format> </playback> `

Dear @hostbbb , Thanks, That's really cool!

But I try to test it in RC3 (I updated my server from RC2 to RC3) and don't see any *video* format in the *getRecordings* response. Do I need to change any parameters for that to appear?

**Comment by hostbbb** [comment]
This is what i did to get it working for RC3,  
1) apt install bbb-playback-video
2) edited bigbluebutton.yml replace the steps:
`steps:
  archive: 'sanity'
  sanity: 'captions'
  captions:
    - 'process:presentation'
    - 'process:video'
  'process:presentation': 'publish:presentation'
  'process:video': 'publish:video'`
3) systemctl restart bbb-rap-resque-worker.service
Note the playback URL in video metadata.xml has http and not https, i reported issue to antoine, not not bother fixing the ruby code as this will all be packaged here shortly.

do a bbb-conf --rebuild on one of your recordings,  should see both formats appear.

**Comment by cod3r0k** [comment]
> 

Hi @hostbbb , I follow the bellow step as you said in one fresh BBB 2.6.0 installation, but it occurs an error.

Step1:
```
apt install bbb-playback-video
```

Step2: Use `nano /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml` and replace the below code:
```
steps:
  archive: "sanity"
  sanity: "captions"
  captions: "process:presentation"
  "process:video"
  "process:presentation": "publish:presentation"
  "process:video": "publish:video"
```

Step3:
```
systemctl restart bbb-rap-resque-worker.service
```

Step4:
The `bbb-record --list` has some problem which referred to `"process:video"` line in step 2.

**Comment by khalooei** [comment]
Dear @cod3r0k and @hostbbb 

You can use the following guidelines which have been tested successfully:

Step1: Install `bbb-playback-video` package with `apt install bbb-playback-video` command.

Step2: Change `/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml` configuration file as below:

```
steps:
  archive: "sanity"
  sanity: "captions"
  captions:
    - 'process:presentation'
    - 'process:video'
  'process:presentation': 'publish:presentation'
  'process:video': 'publish:video'
```

Step3: Use  `systemctl restart bbb-rap-resque-worker.service` to restart `bbb-rap-resque-worker.service` service.

Now, you can see that everything is OK. 

Step4: In the API, the video link appeared as 
```https://xxxxxxx/playback/video/bfcf97b87fdb019192d33b86f2f9c51f47e1785a-1679966791164/``` 
and I think we can provide a link or button for downloading it in the BBB video player (a proper suggestion for future updates @hostbbb). But if you want to download your video, you can add `video-0.m4v` at the end of your video link like below 
```https://xxxxxxx/playback/video/bfcf97b87fdb019192d33b86f2f9c51f47e1785a-1679966791164/video-0.m4v```

Hopefully, this will help you :)

Also, I suggest @antobinary and @hostbbb describe these notes in the documentation which could be useful for new readers.

**Pull request merged**
