### PR TITLE
Most recent freeswitch config

### PR DESCRIPTION
**Pull request by alangecker**
### What does this PR do?
Replaces the 5 years old freeswitch config in this repository with the newest one which got shipped with [`v2.3-alpha-6`](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-6) 

### Motivation
During developing [bigbluebutton-docker](https://github.com/alangecker/bigbluebutton-docker/) I had the obstacle, that some of the code used for building the ubuntu packages was not publicly available.
To be able to reuse parts of it and also track changes in that, I created the [bbb-packages](https://github.com/alangecker/bbb-packages) repo, which is still used in the docker project.

I would like to get rid of this dependency and build bbb-docker exclusively on official repositories. Bringing back the freeswitch config is one of the last steps for that goal :)

Additionally it would allow enable the community to contribute to the freeswitch config as well :)

### More
- [ ] Clarify whether to rename the path? `/bbb-voice-conference/config/freeswitch/conf` -> `/bbb-freeswitch/conf` ?
- [ ] Clarify whether everything is GPLv3 in there?
- [ ] Use this for ubuntu packaging, so that it is clear `state here == state shipped`

### CODE REVIEW

**Comment by antobinary** [comment]
@alangecker Thank you for your contribution!
I have seen your username in relation to quite a few areas of BBB but I also spot this is the first official PR contribution you have sent personally.
Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

**Comment by basisbit** [comment]
cc @schrd. Afaik, this PR is kind of redundant with the other packaging rewrite?

**Comment by schrd** [comment]
> cc @schrd. Afaik, this PR is kind of redundant with the other packaging rewrite?

Yes, the current packaging does not use configuration from the bigbluebutton repo. Config files are in the package repo.

**Comment by alangecker** [comment]
@antobinary I finally managed to sign the CLA ;)

@schrd
1. Does that mean that having the config files in this repo here is redundant and we could also remove them here or vice versa?
2. Would be great if the packaging repo could also be accessible! :) any plans on making it open source as well? :)

**Pull request merged**
