### PR TITLE
feat(chat): Add ability to edit and delete messages

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

Add UI support for deleting and editing chat messages.

https://github.com/user-attachments/assets/d7eef2c4-6698-4662-88e8-89e3fa098552

### Closes Issue(s)

n/a

### More

Built on top of https://github.com/bigbluebutton/bigbluebutton/pull/21335, so I'll open this PR as draft.

### CODE REVIEW

**Comment by antobinary** [comment]
@JoVictorNunes do we currently satisfy the requirements in https://github.com/bigbluebutton/bigbluebutton/issues/21357#issuecomment-2392474187 ? Do you have any written requirements somewhere?

**Comment by gustavotrott** [comment]
The target message should keep highlighted somehow to avoid confusing!

image

**Comment by gustavotrott** [comment]
IMO the delete button should require a confirmation step!

**Comment by JoVictorNunes** [comment]
TODO:

- [ ] Add disabledFeatures handling.
- [ ] Do not allow moderators to delete in Breakouts.

**Review by ramonlsouza — CHANGES_REQUESTED** [review]
attempting to copy or save the chat from the chat menu causes an error if any message has been deleted

Screenshot from 2024-10-14 14-40-56

**Review by ramonlsouza — APPROVED** [review]

**Pull request merged**
