### PR TITLE
External video events propagated through akka-apps

### LINKED ISSUE #11444: bbb 2.3 alpha 7 - shared video: playing position and pause are not passed on to other users
**Describe the bug**
When sharing a video, the presenter can usually change the playing position or pause the video for all members of the conference. In bbb 2.3 alpha 7 this doesn't work. The presenter can only pause playback or change the video position for himself.
**To Reproduce**
1. Share an external video.
2. Click on the pause button.
3. The video pauses on the presenters screen, the video keeps playing on all other screens.
or
1. Share an external video.
2. Click on the playing position bar.
3. The video jumps to the selected position on the presenters screen, the video keeps playing on all other screens.

**BBB version (optional):**
2.3 alpha 7 

**Desktop (please complete the following information):**
 - OS: Windows, Mac, Linux
 - Browser Chrome, Firefox

### PR DESCRIPTION
**Pull request by antobinary**
### What does this PR do?

Register external video playback events to Redis , so that we can create events for reproducing videos in the recordings and we can propagate changePosition and pause events for externalVideos

### Closes Issue(s)

closes #11444
I believe with this merge #10349 will merge automatically
I believe with this merge #7484  will be closed

### Motivation

This work was initially done by @lfzawacki in #7484  and then continued by @amguirado73 in #10349
I cherry-picked @amguirado73 's pull request and resolved all conflicts + one bug where presenter change would not stop video sharing

### More

Initially when I was working on merging #10349 via #11317 it seemed to me that the external video changes were not necessary for multiple nodejs instances since I could start/stop videos but #11444 got me to re-test fully and, my bad, yes, the changes are indeed needed.

Thanks @lfzawacki and @amguirado73

P.S. in #10349 it seems like the change presenter event does not cause external video stop (we check for current presenter Id). In https://github.com/bigbluebutton/bigbluebutton/commit/740a3a9db9366ba52f8153094cd3b19b008fe283 I reworked the logic so that system calls to stop external video are handled separately from client calls. In future it would be better if akka-apps initiates the external video stop due to [ presenter change , presenter left, screenshare start ]

### CODE REVIEW

**Comment by pedrobmarin** [comment]
Hi @antobinary ,

Regarding #7484, this is missing the whole event recording part. Not sure if this was intended, if it was it does not close the former pull request.

**Comment by antobinary** [comment]
Hi @pedrobmarin,
You are right, I have left out the recording messages. I should either tweak the description or reach some decision about

1. Including the recording events and making sure they are indeed working
2. The permission check work that Chad brought up. The way it works in this PR is that there are some checks prior to publishing into redis. And when we receive the events from redis, we simply trust them. This setup includes bbb-html5 triggering external video stop on  [ presenter change , presenter left, screenshare start ] (with a made up requesterId ). Ideally bbb-html5 should not be in charge of this, and it should be moved to akka-apps. It would involve a bit of work though, so maybe best is to keep it separate from this PR.

What do you think?

**Comment by pedrobmarin** [comment]
If I remember that conversation with Chad, the problem with including the permission check at that point was that the presenter validation wasn't something that fit the scenario where an external video was being shared and the presenter changed for some reason.

Akka-apps was more restrictive at that time and would probably kick users on cases like this. The other point that didn't make much sense is that Meteor do not wait for akka-apps response to start/stop/update an external video, so you would have to build the response control at Meteor to follow akka-apps' redis response and avoid short-circuiting.

**Comment by antobinary** [comment]
Merged the recording work from #7484 into this branch.

Note that the `state` was of type `Boolean` in #10349 but of type `Int` in #7484. I spoke with @lfzawacki and he clarified that typically video players do not have binary state but the values can include [ stopped, paused, playing, loading, etc] and this is the type of values we expect from `react-player`... This is the reason why I overwrote the state to be `Int`.

I tested recording external video events locally, these are the relevant `events.xml` events:

```
  <event timestamp="1284613137" module="EXTERNAL-VIDEO" eventname="StartExternalVideoRecordEvent">
    <timestampUTC>1614284934489</timestampUTC>
    <date>2021-02-25T20:28:54.489Z</date>
    <externalVideoUrl>https://www.youtube.com/watch?v=fzD6S1dMhrw</externalVideoUrl>
  </event>
  <event timestamp="1284614876" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614284936228</timestampUTC>
    <state>0</state>
    <date>2021-02-25T20:28:56.228Z</date>
    <status>presenterReady</status>
    <time>0.0</time>
  </event>
  <event timestamp="1284615363" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614284936715</timestampUTC>
    <state>0</state>
    <date>2021-02-25T20:28:56.715Z</date>
    <status>play</status>
    <time>0.0</time>
  </event>
  <event timestamp="1284621475" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614284942826</timestampUTC>
    <state>0</state>
    <date>2021-02-25T20:29:02.826Z</date>
    <status>stop</status>
    <time>212.0</time>
  </event>
  <event timestamp="1284622265" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614284943617</timestampUTC>
    <state>0</state>
    <date>2021-02-25T20:29:03.617Z</date>
    <status>play</status>
    <time>212.0</time>
  </event>
  <event timestamp="1284627811" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614284949163</timestampUTC>
    <state>0</state>
    <date>2021-02-25T20:29:09.163Z</date>
    <status>stop</status>
    <time>218.0</time>
  </event>
  <event timestamp="1284635453" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614284956804</timestampUTC>
    <state>0</state>
    <date>2021-02-25T20:29:16.804Z</date>
    <status>play</status>
    <time>360.0</time>
  </event>
  <event timestamp="1284640206" module="EXTERNAL-VIDEO" eventname="StopExternalVideoRecordEvent">
    <timestampUTC>1614284961557</timestampUTC>
    <date>2021-02-25T20:29:21.557Z</date>
  </event>
```

**Comment by antobinary** [comment]
Looking deeper, seems like react-player sends the state as Boolean now... contrary to expectations. I adapted the PR.

This is the kind of events we have now in events.xml

```
  <event timestamp="1296957085" module="EXTERNAL-VIDEO" eventname="StartExternalVideoRecordEvent">
    <timestampUTC>1614297278436</timestampUTC>
    <date>2021-02-25T23:54:38.436Z</date>
    <externalVideoUrl>https://www.youtube.com/watch?v=fzD6S1dMhrw</externalVideoUrl>
  </event>
  <event timestamp="1296958925" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614297280276</timestampUTC>
    <state>false</state>
    <date>2021-02-25T23:54:40.276Z</date>
    <status>presenterReady</status>
    <time>0.0</time>
  </event>
  <event timestamp="1296959408" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614297280759</timestampUTC>
    <state>false</state>
    <date>2021-02-25T23:54:40.759Z</date>
    <status>play</status>
    <time>0.0</time>
  </event>
  <event timestamp="1296961156" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614297282507</timestampUTC>
    <state>false</state>
    <date>2021-02-25T23:54:42.507Z</date>
    <status>stop</status>
    <time>190.0</time>
  </event>
  <event timestamp="1296962170" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>1.0</rate>
    <timestampUTC>1614297283522</timestampUTC>
    <state>true</state>
    <date>2021-02-25T23:54:43.522Z</date>
    <status>playerUpdate</status>
    <time>191.0</time>
  </event>
  <event timestamp="1296962295" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614297283647</timestampUTC>
    <state>false</state>
    <date>2021-02-25T23:54:43.647Z</date>
    <status>play</status>
    <time>191.0</time>
  </event>
  <event timestamp="1296963936" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614297285287</timestampUTC>
    <state>false</state>
    <date>2021-02-25T23:54:45.287Z</date>
    <status>stop</status>
    <time>415.0</time>
  </event>
  <event timestamp="1296964882" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614297286233</timestampUTC>
    <state>false</state>
    <date>2021-02-25T23:54:46.233Z</date>
    <status>play</status>
    <time>415.0</time>
  </event>
  <event timestamp="1296965531" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>0.0</rate>
    <timestampUTC>1614297286882</timestampUTC>
    <state>false</state>
    <date>2021-02-25T23:54:46.882Z</date>
    <status>stop</status>
    <time>415.0</time>
  </event>
  <event timestamp="1296967257" module="EXTERNAL-VIDEO" eventname="UpdateExternalVideoRecordEvent">
    <rate>1.0</rate>
    <timestampUTC>1614297288609</timestampUTC>
    <state>false</state>
    <date>2021-02-25T23:54:48.609Z</date>
    <status>playerUpdate</status>
    <time>415.0</time>
  </event>
  <event timestamp="1296968642" module="EXTERNAL-VIDEO" eventname="StopExternalVideoRecordEvent">
    <timestampUTC>1614297289994</timestampUTC>
    <date>2021-02-25T23:54:49.994Z</date>
  </event>
```

Note the repeated `<state>false</state>`. This is caused by us inserting unnecessarily `state` in `UpdateExternalVideoPubMsg` in `methods/emitExternalVideoEvent.js`

This is what is being triggered from client side:

```
Feb 25 23:54:40 anton systemd_start_frontend.sh[6287]: playerStatus--- { playerStatus: {} }
Feb 25 23:54:40 anton systemd_start_frontend.sh[6287]: info: UpdateExternalVideoEvtMsg received for user w_wtjvix8jdtfb and meeting 6e35e3b2778883f5db637d7a5dba0a427f692e91-1614297208459 event:presenterReady
Feb 25 23:54:40 anton systemd_start_frontend.sh[6287]: playerStatus--- { playerStatus: { time: 0 } }
Feb 25 23:54:40 anton systemd_start_frontend.sh[6287]: info: UpdateExternalVideoEvtMsg received for user w_wtjvix8jdtfb and meeting 6e35e3b2778883f5db637d7a5dba0a427f692e91-1614297208459 event:play
Feb 25 23:54:42 anton systemd_start_frontend.sh[6287]: playerStatus--- { playerStatus: { time: 190 } }
Feb 25 23:54:42 anton systemd_start_frontend.sh[6287]: info: UpdateExternalVideoEvtMsg received for user w_wtjvix8jdtfb and meeting 6e35e3b2778883f5db637d7a5dba0a427f692e91-1614297208459 event:stop
Feb 25 23:54:43 anton systemd_start_frontend.sh[6287]: playerStatus--- { playerStatus: { rate: 1, time: 191, state: true } }
Feb 25 23:54:43 anton systemd_start_frontend.sh[6287]: info: UpdateExternalVideoEvtMsg received for user w_wtjvix8jdtfb and meeting 6e35e3b2778883f5db637d7a5dba0a427f692e91-1614297208459 event:playerUpdate
Feb 25 23:54:43 anton systemd_start_frontend.sh[6287]: playerStatus--- { playerStatus: { time: 191 } }
Feb 25 23:54:43 anton systemd_start_frontend.sh[6287]: info: UpdateExternalVideoEvtMsg received for user w_wtjvix8jdtfb and meeting 6e35e3b2778883f5db637d7a5dba0a427f692e91-1614297208459 event:play
Feb 25 23:54:45 anton systemd_start_frontend.sh[6287]: playerStatus--- { playerStatus: { time: 415 } }
Feb 25 23:54:45 anton systemd_start_frontend.sh[6287]: info: UpdateExternalVideoEvtMsg received for user w_wtjvix8jdtfb and meeting 6e35e3b2778883f5db637d7a5dba0a427f692e91-1614297208459 event:stop
Feb 25 23:54:46 anton systemd_start_frontend.sh[6287]: playerStatus--- { playerStatus: { time: 415 } }
Feb 25 23:54:46 anton systemd_start_frontend.sh[6287]: info: UpdateExternalVideoEvtMsg received for user w_wtjvix8jdtfb and meeting 6e35e3b2778883f5db637d7a5dba0a427f692e91-1614297208459 event:play
Feb 25 23:54:46 anton systemd_start_frontend.sh[6287]: playerStatus--- { playerStatus: { time: 415 } }
Feb 25 23:54:46 anton systemd_start_frontend.sh[6287]: info: UpdateExternalVideoEvtMsg received for user w_wtjvix8jdtfb and meeting 6e35e3b2778883f5db637d7a5dba0a427f692e91-1614297208459 event:stop
Feb 25 23:54:48 anton systemd_start_frontend.sh[6287]: playerStatus--- { playerStatus: { rate: 1, time: 415, state: false } }

```

I assume this was done to make the format consistent, but it's still a detail to note.

**Pull request merged**
