### PR TITLE
Remove ACL from client

### PR DESCRIPTION
**Pull request by jfsiebel**
Remove ACL from client, leaving to `akka-apps` to handle any permission problem.

### CODE REVIEW

**Comment by Tainan404** [comment]
The user can watch the meeting after be ejected.

peek 2018-11-08 10-41

**Comment by Tainan404** [comment]
I don't understand whats happen here.

peek 2018-11-08 11-28

**Comment by capilkey** [comment]
In 2.2 moderators can't unmute other people. The HTML5 UI still hasn't been updated to match the new restriction so the client can still send messages it shouldn't be able to. The request is received by akka-apps and it's flagged as failing the permission check and a response is sent back to kick the client.

It looks like when the kick request is received on the HTML5 server-side the user is removed from the user list, but they still show in the meeting. It would interesting to know if they still receive updates or not.

**Comment by Tainan404** [comment]
@capilkey, the removed user receives the updates.

peek 2018-11-08 14-10

**Comment by antobinary** [comment]
The unmute in will be removed in 2.2, see #6208 
Looks like we should revisit the user eject in a different PR.

I confirm that both issues are outside of the scope of this PR

**Pull request merged**
