### PR TITLE
feat(audio): add a new button for selecting audio device 

### PR DESCRIPTION
**Pull request by mariogasparoni**
This PR adds a new small button over the "Phone/audio" button. Currently
this button pops up the device audio selector, which contains the "Leave audio"
option. This commit brings back the "Leave audio" behavior to the phone
button, using a new smaller button to switch between audio devices.

This issue address the problem reported by #12320 and complements the work done
for #9723.

#### Screenshot
screen

### CODE REVIEW

**Comment by mariogasparoni** [comment]
Just updated my develop, will update the code according to the recent conventions

**Review by ramonlsouza — CHANGES_REQUESTED** [review]
the `.icon-bbb-device_list_selector` icon is not appearing correctly for me on chrome/ms edge (ubuntu)

Firefox:
Screenshot from 2021-07-02 16-31-06

Chrome/Edge:
Screenshot from 2021-07-02 16-30-20

**Comment by mariogasparoni** [comment]
Thanks @ramonlsouza ... I am using chrome on ubuntu and i can't reproduce it (the screenshot was taken using chrome)
Wondering if it could be related to the chrome version, here's mine: 91.0.4472.77 (Official Build) (64-bit)

I will try to reproduce it in a different machine

**Comment by ramonlsouza** [comment]
> Thanks @ramonlsouza ... I am using chrome on ubuntu and i can't reproduce it (the screenshot was taken using chrome)
> Wondering if it could be related to the chrome version, here's mine: 91.0.4472.77 (Official Build) (64-bit)
> 
> I will try to reproduce it in a different machine

My chrome version is: 91.0.4472.114 (Official Build) (64-bit)

I also noticed that the code for the new icon does not follow the same pattern as the others... All other icons have a "content" starting with `\e` and the new one is `\02c5` (not sure if related).

I replaced a random button in whiteboard actions bar to see if it was something with the new button, but it had the same behavior:
In firefox it looks like a very small `v`, but in chrome it looks like a regular size `V`
Screenshot from 2021-07-05 08-33-07 Screenshot from 2021-07-05 08-33-16

**Comment by antobinary** [comment]
Closes https://github.com/bigbluebutton/bigbluebutton/issues/12320
Closes https://github.com/bigbluebutton/bigbluebutton/issues/12089

**Comment by mariogasparoni** [comment]
> > Thanks @ramonlsouza ... I am using chrome on ubuntu and i can't reproduce it (the screenshot was taken using chrome)
> > Wondering if it could be related to the chrome version, here's mine: 91.0.4472.77 (Official Build) (64-bit)
> > I will try to reproduce it in a different machine
> 
> My chrome version is: 91.0.4472.114 (Official Build) (64-bit)
> 
> I also noticed that the code for the new icon does not follow the same pattern as the others... All other icons have a "content" starting with `\e` and the new one is `\02c5` (not sure if related).
> 
> I replaced a random button in whiteboard actions bar to see if it was something with the new button, but it had the same behavior:
> In firefox it looks like a very small `v`, but in chrome it looks like a regular size `V`
> Screenshot from 2021-07-05 08-33-07 Screenshot from 2021-07-05 08-33-16

That's true. This icon belongs to the same font file, but not to the 'default' set used in bbb-icons (those from unicode e900 to e954).
I will try using one of these default icons.

**Comment by mariogasparoni** [comment]
The smells seem to be unrelated to this PR

**Review by ramonlsouza — APPROVED** [review]

**Comment by ant0nwax** [comment]
please re-open

the small button is not displayed
chrome on android
Screenshot_20220318-130511_Chrome

**Pull request merged**
