### PR TITLE
[Flash 2.0] - General imporvements to buttons

### PR DESCRIPTION
**Pull request by GhaziTriki**
- Update screen-sharing switch display button style.
- Update Alert default button width.

image

### CODE REVIEW

**Comment by capilkey** [comment]
Shouldn't you be triggering "PopUpUtil.initAlert();" when the locale switches?

**Comment by GhaziTriki** [comment]
I am not sure what other languages than Japanese have a Yes, No, OK or Cancel label, so I set all alert buttons width to 100 once for all to avoid any additional surprise in other languages.

**Comment by capilkey** [comment]
The button width and height never need to be changed, but what happens when someone changes the language and opens an Alert. If I'm reading correctly the text of the answers will always be in whatever language the client loads with rather than adapting to what the user chooses.

**Comment by GhaziTriki** [comment]
I have updated it to change labels when locale changes.

**Pull request merged**
