### PR TITLE
Fix video sharing bugs on V1.1.x release to support app on iOS and Android devices.

### PR DESCRIPTION
**Pull request by dfeng99**
Hi,

I've developed an app as a bbb client for both iOS and Android devices. It also includes some community features (described in the attached user guide). It based on bbb release 1.1 that I found video sharing wouldn't work when connections are from the iOS devices. I make some modifications to fix that bugs and would like it to be merged to the upstream.

The client app is called DapiAir which can be found in the GooglePlay and AppStore. A quick demo can be tried by creating a conference at https://dapi03.bzcentre.com (an instance of bbb 1.1 server) and launch the mobile app then select server "Yang Huan" from the drop down list on the app's front page after register/login, hit the "Dapi The Genie" button then follow the instruction on the page to join the conference.

I am not sure would it be possible that to have bbb's official demo server be included in the app's server list so that I don't have to make my developing server as a demo?😊

PS. the uploaded user guide has not yet been updated to the latest version, about 95% match。

Regards,
David
[DapiAir_userGuide_en.pdf](https://github.com/bigbluebutton/bigbluebutton/files/2986809/DapiAir_userGuide_en.pdf)

### CODE REVIEW

**Comment by ffdixon** [comment]
Wow David!  This looks like a lot of work on BigBlueButton 1.1.  Thanks for sharing this with the project.

Since 1.1, we've moved to BigBlueButton 2.0 and are now working on BigBlueButton 2.2 with the HTML5 client.

In BigBlueButton 2.2, the HTML5 client is going to be the same code that runs on desktop, laptop, chromebook, and mobile devices.  There are still some advantages to running a native app, but with the support of WebRTC in Safari, you can send/receive audio and video on iOS 11+ (released on September 2017).  

All to say I'm not sure we're going to be able to review and merge this into the 1.1 branch, which we've not done any development on since 2017.  

Have you checked out the latest builds of the HTML5 client on our test servers at https://test.bigbluebutton.org/.  We are interested to hear what you think of the experience in the HTML5 client relative to the work you did on DapiAir.

**Comment by dfeng99** [comment]
Exactly, there are a lot of work and that's why I didn't catch up the BBB upgrade plan 😅. The simple idea is to add different values on bbb client which base on the main service logic of the bbb server.  I've not evaluate bbb 2.2 and  the html5 client yet, are they still Red5 based app? Are there a lot of change on the message/stream interaction between the server and clients? It sounds like if people would like to try DapiAir, the best idea is to download the server from my v1.1 fork, actually I do mentioned it in DapiAir's description. Anyway, I'll get some idea on v2.2. Looking forward to be in sync.

**Comment by dfeng99** [comment]
In addition, as I've mentioned, DapiAir support multiple servers, user can select the server that he/she would like to connect. Is it possible that to make bbb demo server to be one of the server in the list? i.e., alliance program. I understand that the current demo server is v2.2, I'll make some estimation on the work of version compliance.

**Comment by ffdixon** [comment]
> In addition, as I've mentioned, DapiAir support multiple servers, user can select the server that he/she would like to connect. Is it possible that to make bbb demo server to be one of the server in the list?

Can you send me an e-mail to ffdixon .at. bigbluebutton .dot. org

**Comment by dfeng99** [comment]
> > In addition, as I've mentioned, DapiAir support multiple servers, user can select the server that he/she would like to connect. Is it possible that to make bbb demo server to be one of the server in the list?
> 
> Can you send me an e-mail to ffdixon .at. bigbluebutton .dot. org

Please check your email.

**Comment by ffdixon** [comment]
Flash has been good to use -- but we're moving to the pure HTML5 client and don't need ActionScript going forward.

**Pull request closed without merging**
