### PR TITLE
feat(Dashboard): a new modal for displaying user details

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

- Implements a new modal for displaying user details in a more visual way.
- The modal is centred to the right.

Captura de tela de 2022-02-15 13-03-12

Captura de tela de 2022-02-15 13-03-23

Captura de tela de 2022-02-15 13-03-30

### More

The 'Talks' row in the 'Activity Score' table and the 'Most Common Answer' column in the 'Polls' table are pending items, as currently we don't have such information available in the JSON file for implementing them.

### CODE REVIEW

**Comment by gustavotrott** [comment]
Hey @JoVictorNunes,
I'm facing some problems related to time location and meetings that is not ended.

image

**Comment by gustavotrott** [comment]
I think this part should not be shown for Moderators!
image

Once Activity Score column ignores Moderators.
image

**Comment by gustavotrott** [comment]
Poll with multiple responses is not separating the answers.
image

Ideal would be:
image

**Comment by gustavotrott** [comment]
- **Activity Score / Talks:** I think this item should be called "Talk time" and show the "Total of minutes talked", once `talk.totalTime` is used to calculate the User Score:
image
The same source should be used in this table:
image

**Comment by gustavotrott** [comment]
- **Polls / Most Common Answer:** I'm not sure if it worth to include this information in the Json, once the Json contains the answers of all users. So it is possible to find the Most common answer in the Dashboard. 

Let's discuss where this logic must be placed at.

**Comment by gustavotrott** [comment]
- Anonymous poll: It should hide this line or alert that this is an anonymous poll!

image

**Comment by JoVictorNunes** [comment]
Hi @gustavotrott, thanks for the comments!

I've fixed all of the bugs cited above. As there are many changes, I'm going to summarize all of them in order to speed up your review:

### Fixes

The problem related to time locale:
Captura de tela de 2022-02-23 13-54-57

An "Online" label will be displayed for users who hasn't left:
Captura de tela de 2022-02-23 14-06-54

For moderators, only the "Overview" card will be shown (Since both Activity Score and Polls don't apply to moderators):
Captura de tela de 2022-02-23 14-09-23

Polls with multiple answers:
Captura de tela de 2022-02-23 14-15-34

A new icon for indicating anonymous polls:
Captura de tela de 2022-02-23 14-21-46

### New

Implemented the "Most Common Answer" feature:
Captura de tela de 2022-02-23 14-28-40

The "Talks" row has became "Talk Time" and will show the total talk time:
Captura de tela de 2022-02-23 14-32-15

**Comment by gustavotrott** [comment]
Woow, great job @JoVictorNunes 👏👏👏👏

**Comment by gustavotrott** [comment]
I found a problem in Emojis activity score graphic:

In this scenario there are two users:
- user 1: 1 emoji
- user 2: 2 emojis

I think this graphic should be 100% for user 2, right?
image

**Comment by gustavotrott** [comment]
I think the 100% indicator have a problem.
Sometime the user has the highest value and don't have 100% in the graphic:

Eg:
- user 1: 1 message
- user 2: 2 messages

User 2 should have 100% in Messages graphic, but has less.

image

I think the percentage should be calculated using the Activity Points.
eg:
0,0 = 0%
0,5 = 25%
1,0 = 50%
1,5 = 75%
2,0 = 100%

**Comment by JoVictorNunes** [comment]
Not really. The graphic is percentage of the total. So if 'user 1' sends 1 emoji and 'user 2' sends 2 emojis, there are 3 emojis in total. So, the graphic for 'user 2' would be `2 / 3 * 100` = `66.66%`.

**Comment by gustavotrott** [comment]
> Not really. The graphic is percentage of the total. So if 'user 1' sends 1 emoji and 'user 2' sends 2 emojis, there are 3 emojis in total. So, the graphic for 'user 2' would be `2 / 3 * 100` = `66.66%`.

Alright, I was thinking in a different way.
- You are showing the percent compared to the total.
- I was thinking the percentage to achieve the maximum score.

I don't know what was the initial idea. So it seems to not be a bug.

**Comment by gustavotrott** [comment]
About the "Most Common Answer":

Options: A, B, C, D
- User 1: A
- User 2: D

**Most common: D**

image

**Review by gustavotrott — APPROVED** [review]
LGTM!

Great job @JoVictorNunes.

**Pull request merged**
