### PR TITLE
Fix guest icon

### LINKED ISSUE #7843: Icon not round (guest management approval)
When testing guest management, the user's icon under "Pending Guest Users" is not round

image

### PR DESCRIPTION
**Pull request by pedrobmarin**
Fixes #7843 and includes missing localization.

guest-avatar

### CODE REVIEW

**Comment by daminebenq** [comment]
there is a bug !!
**this is only reproduceable when the webcam stats/focus button is enabled**
Peek 2020-01-13 17-10

to reproduce: 

1) share webcam from a mobile device
2) tap on focus button
3) **#TADAAAAA** image

**Comment by pedrobmarin** [comment]
@daminebenq is this issue related with the guest icon fix?

**Comment by daminebenq** [comment]
no, the issue is related to the webcam stats/focus button on mobile only

**Comment by daminebenq** [comment]
> @daminebenq is this issue related with the guest icon fix?

no, the issue is related to the webcam stats/focus button on mobile only

**Pull request merged**
