### PR TITLE
Multiple cameras

### PR DESCRIPTION
**Pull request by pedrobmarin**
Removed some stuff from video-provider component, added some stuff to video-provider service, removed some more old code that we shouldn't be using anymore.

Disabled as default.

DEVELOPED ON A 2.2 ENVIRONMENT

multiple-cameras

### CODE REVIEW

**Comment by pedrobmarin** [comment]
#6503 

And I believe this fixes #8367

**Comment by prlanzarin** [comment]
Disclaimer: needs https://github.com/mconf/bbb-webrtc-sfu/pull/169/commits/eff84c8d1501368f97ef89755d311c7a566e04c1 to be backported into SFU 2.3.x in order for recordings to work properly (otherwise the filename might be problematic).

**Comment by antobinary** [comment]
Tested - works well! :clap: 

A few notes:
- video pausing on when switching to a different browser tab is intentionally removed as it no longer functions (bbb-webrtc-sfu 2.4.x+ )
 - Autoshare webcam still functions and it causes the default (first choice) webcam to be shared on page load. Additional webcams will have to be shared manually (and explicitly)
 - Lock settings - locking webcam sharing for viewers causes lock of all webcams shared, unlocking allows sharing multiple webcams if settings.yml has `enableMultipleCameras: true`
 - The UX will likely evolve, there are some ambiguities right now, for example if a user shares their non-default webcam unsharing it is non quite intuitive - select the webcam sharing button, _select the shared webcam from the dropdown by guessing which name corresponds to the webcam you shared_ and then press on Stop

 - The en.json strings from video stats are not used anymore but since we may be in the process of adding a different stats implementation we are keeping them. This way if there are useful strings, we won't need to re-request transifex translators' help for already existing translations

**Comment by pedrobmarin** [comment]
An extra:
 - mobile users won't be able to share multiple webcams

**Comment by daminebenq** [comment]
there is a bug !!

**THIS IS A MOBILE ONLY BUG !!!**
**this is only reproducible when the webcam stats/focus button is enabled**
72288410-c2ea9780-3627-11ea-81c7-7bce18bb791c


to reproduce: 

1) share webcam from a mobile device
2) tap on focus button
3) **#TADAAAAA** 
72288226-57a0c580-3627-11ea-87b4-5a4cae101c28

**Comment by gittester2017** [comment]
Hi Pedro,

I am not sure 100%, did you include the logic of cam only for Moderator?
I did not find the code, and the setting for "user management" can not be applied.

Best Regards.
Yang.

**Comment by pedrobmarin** [comment]
Hi @gittester2017 . you are correct and there is already a fix for that here https://github.com/bigbluebutton/bigbluebutton/pull/8888.

**Comment by gittester2017** [comment]
I see, thanks.

**Comment by vitovt** [comment]
Can this feature (Multiple cameras) be backported to next 2.2 release ? For example to 2.2.6 ?

**Comment by mcferdev** [comment]
> Can this feature (Multiple cameras) be backported to next 2.2 release ? For example to 2.2.6 ?

I would like to test this function as well. I have received a require... I am lucky that you have already developed. 
Thank you so much.

**Comment by ruymanbr** [comment]
Did BBB remove this functionality? We just installed 2.3 and I don't see this working.

Also I can see the multiple-video-provider folder was erased from @pedrobmarin repo in ui/components

Any news about this and why it's not working?

**Comment by prlanzarin** [comment]
> Did BBB remove this functionality

No, we didn't.

> Also I can see the multiple-video-provider folder was erased 

That folder never existed in a build branch. It was a transition step self contained in this PR.

> We just installed 2.3 and I don't see this working [...] Any news about this and why it's not working?

It's still working. Just tried it on test.bigbluebutton.org (reference 2.3).

Check: 
  - enableMultipleCameras must be true in settings.yml
  - the feature is not enabled in mobile endpoints (and it never was)
  - you must have more than one valid input video device for the feature to trigger
  
For further inquiries, please prefer the mailing lists (bigbluebutton-setup).

**Pull request merged**
