### PR TITLE
docs: Additional method to setup a custom favicon.ico

### PR DESCRIPTION
**Pull request by AlphaDE**
### What does this PR do?

Documentation update with a second method to setup a custom favicon.ico for both Greenlight (v3) and BBB 2.6+

### Closes Issue(s)

None

### Motivation

Did not found a proper way to achieve this with Greenlight v3/BBB 2.6.x

### CODE REVIEW

**Comment by antobinary** [comment]
Hi @AlphaDE 

Thank you for this contribution! Could you please confirm if you already sent in the signed Contributor License Agreement? See https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code
Thanks in advance!

**Comment by AlphaDE** [comment]
@antobinary cla sent.

**Comment by antobinary** [comment]
Hi @AlphaDE 

> @antobinary cla sent.

I am afraid I am not seeing your mail. Any chance you could resend it/forward it again to  cla at bigbluebutton dot org ? Ideally put 17768 in the title line... Much appreciated!

**Comment by AlphaDE** [comment]
I wonder.. I did resent it and the message was delivered... 

Well... if it is impossible to get a simple pdf over... there is nothing I can do.

**Comment by antobinary** [comment]
Hi @AlphaDE ,
@ffdixon was able to track it down and it looks good! Thank you again for your contribution!

**Pull request merged**
