### PR TITLE
Draggable webcams grid improvements

### PR DESCRIPTION
**Pull request by vitormateusalmeida**
part of #7598

### CODE REVIEW

**Comment by vitormateusalmeida** [comment]
In this PR I fixed the webcams area to 20% of media area, automatically the presentation will occupy 80%.
On next PR I will try to make the webcams area resizable.

**Comment by capilkey** [comment]
Do the webcams take the full space when the presentation is hidden?

**Comment by capilkey** [comment]
I thought this was supposed to have been tested on mobile? This doesn't look right to me.

image

**Comment by prlanzarin** [comment]
Also, although I guess it's a know issue, the loading/spinning animation is still stretched thin. Just registering.

**Comment by capilkey** [comment]
Found another one. If you have multiple webcams and drag them off the top of the client they will be floating over the presentation again. When you drag them off the bottom of the screen they snap to the bottom.

**Comment by capilkey** [comment]
The behaviour of the drag and drop also doesn't work if you have multiple webcams and then go back down to one webcam. The dragging is completely broken and if you drop the single webcam you'll lose the webcam completely.

**Comment by capilkey** [comment]
Screenshot of the previous issue. I'm sharing my webcam, but it's gone from the screen. If I hide the presentation I can see the large webcam, but if I show the presentation the webcam is still missing.

image

**Comment by capilkey** [comment]
A screenshot of the drag and drop issue a few comments above.

image

**Pull request merged**
