### PR TITLE
Add bbb_show_public_chat_on_login as a join (co-) parameter

### PR DESCRIPTION
**Pull request by mantridereso**
Very trivial addition:

If bbb_show_participants_on_login is true (or unset) then setting **bbb_show_public_chat_on_login=false** causes the public chat component (div) to be initially hidden on login (until user expands it).

---

Only thing that needs to be changed is in
greenlight/app/controllers/concerns/bbb_server.rb
and add join_opts["userdata-bbb_show_public_chat_on_login"] = false
to the block with
join_opts = {}
join_opts[:userID] = uid if uid
join_opts[:join_via_html5] = true
join_opts[:guest] = true if options[:require_moderator_approval] && !options[:user_is_moderator]
<<add it here>>

### CODE REVIEW

**Comment by mantridereso** [comment]
umm sorry... I should perhaps better have made a pull request to the 'develop' branch or so...?

**Comment by antobinary** [comment]
Thank you for this contribution @mantridereso  !
Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

**Comment by martbeck** [comment]
Hi @antobinary :)
yes, confirmed! 
Martin

**Comment by mantridereso** [comment]
pardon me, confirmed it from a different user identity.

From mantridereso once again, yes, confirmed :)

**Comment by mantridereso** [comment]
... have noticed in the meantime that PR #9292 by @weeman1337 conflicts with my PR #9658.
Posted another PR to combine both. @antobinary : please can you consider this as a solution replacing/integrating both of the above mentioned singular PRs into one PR? :)

**Pull request merged**
