### PR TITLE
Adak tivan

### PR DESCRIPTION
**Pull request by TivanDev**
please add my name to bbb contributors list

### CODE REVIEW

**Comment by basisbit** [comment]
what contributors list are you referring to? What did you contribute? Did you sign the [Contributor License Agreement](https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code)?

**Comment by TivanDev** [comment]
I will send bbb contributor license agreement
this is not spam

**Comment by basisbit** [comment]
then please explain what this pull request is supposed to do? You created a pull request of actually nothing. You created a Contributors.md file (which is not necessary for this project because there is the git timeline), then you added some name, and then you deleted the file again. Whatever might have been your intention, that did not work. Maybe some video tutorials on how to use git could help.

**Comment by antobinary** [comment]
Invalid pull request

**Pull request closed without merging**
