### PR TITLE
Emojis added for applause, thumbsUp and thumbsDown

### PR DESCRIPTION
**Pull request by kristinfjola**
This is a PR for issue #2940 as discussed in the [google forum thread](https://groups.google.com/forum/#!topic/bigbluebutton-dev/jnBloQYoNao). 
Like we mentioned in the thread these are only placeholder images. We noticed that some whitespaces are deleted in the commit, is that a problem?

by TU Delft SWA team :sunglasses: 
@MikeAnas, @PietroFrigo, @mvallet91, @kristinfjola

### CODE REVIEW

**Comment by GhaziTriki** [comment]
Great job. Compiled and all is working fine.I think we can provide images, their size needs to be 16x16. And now worries about the white spaces.

**Comment by MikeAnas** [comment]
Good to hear, will you provide us with the images so that we update the pull request or you will do it?

**Comment by GhaziTriki** [comment]
We will provide with the new images and you can update the pull request after that.

**Comment by GhaziTriki** [comment]
Please use the icons from this archive https://www.dropbox.com/s/2ucepuzk7obqj6y/icons.zip?dl=0

**Comment by kristinfjola** [comment]
Thanks for the icons @GhaziTriki , we have replaced them

**Comment by ritzalam** [comment]
We will be merging this PR after 1.0 release (soon).

**Pull request merged**
