### PR TITLE
 Format conference numbers

### PR DESCRIPTION
**Pull request by ritzalam**
- add dashes to conference numbers so it is easier to read

### CODE REVIEW

**Comment by hbruch** [comment]
Here in Germany, phone number blocks are usually separated using spaces, e.g. six-per-em (0xE2).

**Comment by ritzalam** [comment]
Suggestions welcome on how to improve it that  would be useful for the majority of users.

**Comment by hbruch** [comment]
Perhaps introducing (yet another) configurable property, e.g. `phonenumberSeparator` which could default to hyphen and be changed for different locales to e.g. period (e.g. PL) or space (e.g. DE) or even none?

**Comment by ritzalam** [comment]
We'll take a  look. 

Maybe this can provide pointers on how to do it.

http://zetcode.com/java/numberformat/

**Pull request merged**
