### PR TITLE
chore: upgrade tldraw to 1.27.0 to include accessibility improvements

### LINKED ISSUE #16147: Missing tooltips from certain tldraw tools
**Describe the bug**
Both for accessibility context and for pure informative reasons. The conrols that have a red arrow point to them in the below image are missing tooltips.

Screenshot from 2022-12-15 12-12-45

### PR DESCRIPTION
**Pull request by antobinary**
### What does this PR do?
Upgrades tldraw to 1.27.0 to include accessibility improvements

### Closes Issue(s)

Closes #16147

### Motivation
Upgrading tldraw to include changes made in https://github.com/tldraw/tldraw/pull/1106 and https://github.com/tldraw/tldraw/pull/1095

### CODE REVIEW

**Comment by antobinary** [comment]
P.S. I spot one more familiar name in the this tldraw release! https://github.com/tldraw/tldraw/pull/1104 Nice job @hiroshisuga !! :smiley_cat:

**Review by ramonlsouza — APPROVED** [review]

**Comment by padaliyajay** [comment]
I want to modify tldraw 1.27.0. but there is no tag existing of 1.27.0 version. how did you found this version?

**Comment by antobinary** [comment]
There was such a tag back then. Since then the tldraw v1 project was renamed and archived (without tags) and moved to this other repository: https://github.com/tldraw/tldraw-v1 
What remains in tldraw/tldraw is v2 which we use on BBB 3.0, but be careful as the license of tldraw v2 changes when they were switching from alpha to beta. We use the alpha version.

**Comment by padaliyajay** [comment]
Thank you response. i found it. :)

But there is now only latest version 1.29.2 available in that v1 repo. So if i use that version in bbb v2.7 then will it work or any known issue?

**Comment by antobinary** [comment]
https://www.npmjs.com/package/@tldraw/tldraw/v/1.27.0

If you're really keen on finding a live repository with 1.27.0, maybe try looking for someone's fork or npmjs packages. Here's one for 1.29 https://www.npmjs.com/package/@gip-recia/tldraw-v1

**Comment by antobinary** [comment]
To benefit from our testing on BBB 2.7, please use the version we've tagged there: https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/bigbluebutton-html5/package.json#L42 1.27.0
We have not tested BBB 2.7 with a newer tldraw.

**Comment by padaliyajay** [comment]
Thank you. What i want is to decrease stroke width of line. so i want to fork tldraw 1.27 and then modify code and install back to bbb 2.7. But unfortunately source code of v1.27.0 not available anymore. not even in npm. it is compiled code

So i have to use tldraw 1.29

**Comment by antobinary** [comment]
@padaliyajay try something like this https://github.com/karolstawowski/tldraw/tree/55a8831a6b036faae0dfd77d6733a8f585f5ae23 
The commit is for 1.27.0 renaming. It might be a few commits off from the actual release but it's the best I spot at the moment. Fork it and browse locally... Hope it helps!

**Comment by padaliyajay** [comment]
@antobinary  Thank you so much for finding me repo. But i already tried tldraw 1.29 and it is working without any problems in BBB 2.7. and i also modified it to decreased thickness of line and it is also working. once again thank you so much for help

**Pull request merged**
