### PR TITLE
docs: Update url for GL migration path

### LINKED ISSUE #17350: 404 Page Not Found when upgrading greenlight
**Describe the bug**
404 Page Not Found when upgrading greenlight while downloading the file at [path](https://raw.githubusercontent.com/bigbluebutton/greenlight/master/lib/tasks/migrations/migrations.rake)

**Installation type**
While upgrading greenlight from the documentation of 2.5

**Firewall and IP address type**
Yes it has own IPv4

**Additional context**
This seems to be a [documentation ](https://docs.bigbluebutton.org/greenlight/v3/migration)problem. When checked with v2.6 the path is quite different.
Documentation for 2.5
Documentation for 2.6

### PR DESCRIPTION
**Pull request by sripathroy**
### What does this PR do?

migrations.rake file at the given path doesnt exist. Modified the path.

### Closes Issue(s)

Closes #17350 

### Motivation

Documentation issue in v2.5

### More

- [ ] Added/updated documentation

### CODE REVIEW

**Comment by antobinary** [comment]
Hi @sripathroy 

Thank you for this contribution! Could you please confirm if you already sent in the signed Contributor License Agreement? See https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code 
Thanks in advance!

**Comment by sripathroy** [comment]
Hi @antobinary 

I have submitted the Contributor Agreement to the email given in the document.

> Hi @sripathroy
> 
> Thank you for this contribution! Could you please confirm if you already sent in the signed Contributor License Agreement? See https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code Thanks in advance!

**Comment by sripathroy** [comment]
Hi @antobinary 

Is there anything else to be done from my end to close this PR?

**Comment by ffdixon** [comment]
We've updated the contributors agreement so the submission email is now cla@bigbluebutton.org.  Can you resubmit to that address -- thanks!

**Comment by sripathroy** [comment]
> We've updated the contributors agreement so the submission email is now [cla@bigbluebutton.org](mailto:cla@bigbluebutton.org). Can you resubmit to that address -- thanks!

Done.... Submitted.

**Comment by antobinary** [comment]
Thank you!

**Comment by antobinary** [comment]
I tried to propagate this to branch v2.6.x-release but looks like the info was correct there https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.x-release/docs/docs/greenlight/v3/migration.md

**Pull request merged**
