### PR TITLE
Fix missing leading zeros in conference number for 2.2.x

### LINKED ISSUE #9769: Conference PIN number is displayed without leading zeros
**Describe the bug**
If the randomly generated voiceBridge has less digits than the configured number of digits, then in the welcome message leading zeros are not displayed. Example: 6 digits configured, the random number generator produces 12345. The %%CONFNUM%% in the welcome text is replaced by "12 345", it should be "012 345". Freeswitch expects 012345 as conference number.

**Expected behavior**

Welcome message should be:

    To join this meeting by phone, dial:<br>  +1234567890<br>Then enter 012 345 as the conference PIN number

**Actual behavior**
Welcome message currently is:

    To join this meeting by phone, dial:<br>  +1234567890<br>Then enter 12 345 as the conference PIN number

### PR DESCRIPTION
**Pull request by symptog**
### What does this PR do?

Fix missing leading zeros in conference number
Rewrite conference number formating to use only string manipulation as converting to Int removes leading zeros.

### Closes Issue(s)

fixes #9769

### CODE REVIEW

**Comment by antobinary** [comment]
Hi @symptog,

Thank you for this contribution!
Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

**Comment by symptog** [comment]
@antobinary not yet. will send it this evening.

**Comment by symptog** [comment]
@antobinary: @ffdixon confirmed my CLA :)

**Comment by schrd** [comment]
@antobinary @ffdixon  what prevents merging this fix into the next patch release? It is really confusing a lot of users here.

**Pull request merged**
