### PR TITLE
Add data saving tab and webcam disable button.

### PR DESCRIPTION
**Pull request by Tainan404**

### CODE REVIEW

**Comment by antobinary** [comment]
I think the file `en.json' should not be linted like this. I believe it's more important to have the key and value on the same line regardless of line length. I am also not sure if adding line endings will impact Transifex. Are there any different opinions on the subject (I'd be happy to read them)?

**Comment by antobinary** [comment]
It would be nice if we could call https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/imports/ui/components/video-dock/component.jsx#L434-L439 to unshare webcam (if shared). Right now the code there is not very easy to link to

**Comment by antobinary** [comment]
Fixes #5028

**Comment by gutobenn** [comment]
The interface seems good, but it's not really saving data because the websockets aren't being closed. In fact, it seems to be using even more data, because every time you reenable it new websockets are opened.
As @antobinary said, unshareWebcam must be called to close them.

**Comment by antobinary** [comment]
Depends on #5100

**Pull request merged**
