### PR TITLE
Fix for posJoinMessage as undefined

### LINKED ISSUE #11528: [2.3] Cannot read property 'posJoinMessages' of undefined
Switching between private and public chat gives `Cannot read property 'posJoinMessages' of undefined`, with a client crash (audio remains connected).

image

**PS:** This happens inconsistently, and it should be retested.

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?

This PR adds an optional-chaining operator for all the posJoinMessage uses.

### Closes Issue(s)
closes #11528

### CODE REVIEW

**Comment by daminebenq** [comment]
I couldn't reproduce it anymore using this PR. All good.

**Comment by GyR4uk** [comment]
The problem remained

**Comment by daminebenq** [comment]
Hi @GyR4uk 
Can you please describe us how you could reproduce it ? a video recording or some screenshots or steps to reproduce will help us so much. Thanks !

**Comment by GyR4uk** [comment]
image
I have already described how this error is reproduced, my actions have not changed
https://github.com/bigbluebutton/bigbluebutton/issues/11704

**Comment by GyR4uk** [comment]
Peek 2021-03-24 01-15

**Comment by ffdixon** [comment]
Thanks -- the video was helpful.

**Pull request merged**
