### PR TITLE
Add event IDs for webhooks to filter out un-needed messages.

### PR DESCRIPTION
**Pull request by NaNgets**
### What does this PR do?

Adds the ability to filter out un-needed messages in web hooks.

### Motivation

Web hooks send a lot of data and messages, while not all messages are needed. After this change, when registering a hook, it is optional to add an eventID parameter with comma-separated event IDs, so only those will be sent.

### More

- [ ] Needs to update bbb-webhooks doc (currently they are not updated to the current situation).

### CODE REVIEW

**Comment by NaNgets** [comment]
Hi,

Is there anything I can do to push this forward and get it merged?

Thanks.

**Comment by antobinary** [comment]
@pedrobmarin could we transfer this to bigbluebutton/bbb-webhooks?

**Comment by NaNgets** [comment]
> @pedrobmarin could we transfer this to bigbluebutton/bbb-webhooks?

done: https://github.com/bigbluebutton/bbb-webhooks/pull/3

**Comment by antobinary** [comment]
Thank you @NaNgets 
I will close this PR and we can focus on merging https://github.com/bigbluebutton/bbb-webhooks/pull/3

**Pull request closed without merging**
