### PR TITLE
feat(presentation): new presentation menu and snapshot of the current presentation

### LINKED ISSUE #14380: Snapshot of current slide (including annotations)
**Is your feature request related to a problem? Please describe.**
We have made some preliminary tests with different client side libraries to "snapshot" / take a screenshot of the whiteboard area. This approach is meant as a complement of the (significantly larger and different) project of downloading an entire presentation with annotations. The snapshot is done entirely on client side, by the browser. It is quite similar to tools available at browser or OS level where you can take a screenshot [of an area] but we'd like to make it more readily available.

**Describe the solution you'd like**
* Turn the existing controls into a menu (see the paragraph below) and add a menu item `Snapshot of current slide`
* Handle `oldMinimizeButton` as described below
* Use https://github.com/bubkoo/html-to-image (@JoVictorNunes  already tried https://html2canvas.hertzen.com/ but hit issues with images within SVG)

(Please ignore the `_` minimize button, I am pretty sure we'll be proceeding with Minimize menu item if `oldMinimizeButton: true` https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/bigbluebutton-html5/private/config/settings.yml#L601 ) and I think we'll exclude the menu item if `oldMinimizeButton: false` which is the default

Screenshot from 2022-02-16 10-15-56

**Describe alternatives you've considered**
Downloading entire presentation with annotation is in the works. It's not a competitor for this.
We tried two different libs and the one we proceed with produced great results in all browsers we tried

**Additional context**
Design by @tylercopeland

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

Implements presentation's new modal and a new option to take a snapshot of current presentation as a PNG image.

Captura de tela de 2022-02-18 17-21-35

- **Replaces the old fullscreen button with a new dropdown menu and a new option for the snapshot.**
Captura de tela de 2022-02-18 17-21-45

- `oldMinimizeButton`: when it's `true`, a new menu option is going to be added for it.
Captura de tela de 2022-02-18 17-26-55

### Example

- Presentation:
Captura de tela de 2022-02-18 17-25-06

Captura de tela de 2022-02-18 17-25-13

- Resulting snapshot:
Presentation_random-9650393_2022-02-18T20_25_11 919Z

### Closes Issue(s)

Closes #14380 

### More

The https://github.com/bubkoo/html-to-image lib was used in the implementation.

### CODE REVIEW

**Review by ramonlsouza — CHANGES_REQUESTED** [review]
Not working in Safari browser (macOS/iOS). 
No error messages displayed, looks like it is a [known issue](https://github.com/bubkoo/html-to-image#browsers).

**Review by ramonlsouza — APPROVED** [review]

**Comment by antobinary** [comment]
@SamuelWei I tried this on the latest 2.5 and could not reproduce. I used pencil shapes only, wrote "1" on slide1, "2" on slide2, ...up to 4. I went back and forth and downloaded a snapshot of slide 2 -> worked, saw "2", slide 3 snapshot contained "3".
In your use case did you use a specific shapes? are you able to reproduce it on test25.bigbluebutton.org ?

**Comment by SamuelWei** [comment]
@antobinary Yes, I have the same issue on test25.bigbluebutton.org 
I'll record my screen and attach it asap

**Comment by SamuelWei** [comment]
https://user-images.githubusercontent.com/4281791/162014684-d7015c74-c129-4c20-8035-f1043027efc1.mov

**Comment by antobinary** [comment]
Thanks @SamuelWei ! I will export this into an issue for 2.5

**Pull request merged**
