### PR TITLE
Add a maximum allowed length to chat message

### PR DESCRIPTION
**Pull request by GhaziTriki**

### CODE REVIEW

**Comment by ritzalam** [comment]
Can't we disable the chat box if the message is too long?

**Comment by GhaziTriki** [comment]
We are disabling the send button, if we disable the whole chat box then the text area can't be edited. Did I understand you correctly?

**Comment by capilkey** [comment]
You could potentially reject any additional text input after the limit has been reached. Then the Send button wouldn't need to be disabled.

**Comment by ritzalam** [comment]
Yes, reject the text input. I did not notice that the Send button got  disabled until you mentioned it :)

Seems to also reject Ctrl-S and ENTER to send the message which is good.

**Comment by capilkey** [comment]
It looks like there is a maxChars property on TextArea, http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/controls/TextArea.html#maxChars. Would using that simplify the client logic or is there an issue with it?

**Comment by GhaziTriki** [comment]
Using maxChars of TextArea is a good idea and another way to handle it. Whatever happens the user needs to be notified that the maximum allowed message length has been attained.

**Pull request merged**
