### PR TITLE
Added Kannada (kn) locale

### PR DESCRIPTION
**Pull request by yogiks**
I've wired in kn locale for [Kannada](https://en.wikipedia.org/wiki/Kannada) language to include in HTML5 client. They have been uploaded from [Transifex](https://www.transifex.com/bigbluebutton/bigbluebutton-v22-html5-client/language/kn/). Please let me know for any changes.

Would be great if the locale can be included in the next release. Thanks in advance! :)

### CODE REVIEW

**Comment by yogiks** [comment]
Hi @antobinary, kindly see if this needs any changes. Thank you! :)

**Comment by antobinary** [comment]
@yogiks well done! This is exactly what had to be done for a language supported by LangMap! I am including your two commits in my locale pulling on branch v2.2.x-release, from which the commits will be propagated to branch develop, merging this PR.

Thank you for your contribution! I am not asking for signing a CLA for this pull request since it is pulling the content from Transifex and simply including the `kn` locale in the list.

**Comment by yogiks** [comment]
Thank you @antobinary for including my two commits. I see that the `kn` locale has been included in latest [v2.2.10 release](https://github.com/bigbluebutton/bigbluebutton/compare/v2.2.9...v2.2.10) now. 

So should I just follow [this documentation](https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22) to upgrade my instance of BigBlueButton to include Kannada locale? I'm currently running v2.2.3.

image

**Comment by yogiks** [comment]
Thank you for all the help and support! :) Will refer to the google group if I have any further questions on upgrade. Will close this PR now.

**Pull request closed without merging**
