### PR TITLE
ci: add minimum GitHub token permissions for workflow

### PR DESCRIPTION
**Pull request by boahc077**
### Description
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).

The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/bigbluebutton/bigbluebutton/actions/runs/3169919638/jobs/5162154087#step:1:19

After this change, the scopes will be reduced to the minimum needed for the following workflow:

- check-merge-conflict.yml

### Motivation and Context

- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token) defining minimum GITHUB_TOKEN permissions.
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions as a high-risk issue. This change will help increase the Scorecard score for this repository.

Signed-off-by: Ashish Kurmi <akurmi@stepsecurity.io>

### CODE REVIEW

**Comment by MaximKhlobystov** [comment]
Hi boahc077,

Thank you for this contribution! Could you please confirm if you already sent in the signed Contributor License Agreement? See https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code. Thanks in advance!

**Review by TiagoJacobs — COMMENTED** [review]
This looks like a good thing, so the action will just be able to write on pull requests 
( https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs )

PS: let's wait for the CLA as @MaximKhlobystov mentioned

**Comment by ffdixon** [comment]
Can you email it to cla at bigbluebutton ..dot.. org.

**Comment by MaximKhlobystov** [comment]
@boahc077 thanks!
@ffdixon can you confirm that it was received at the correct email address?

**Comment by ffdixon** [comment]
Confirmed that CLA received -- thanks!

**Comment by MaximKhlobystov** [comment]
@TiagoJacobs do you think we can go ahead and merge this?

**Pull request merged**
