### PR TITLE
Add Yandex browser to the list of supported browsers

### LINKED ISSUE #8101: incompatibility with Yandex Browser
Hi BBB,

**browsers market share in Russia:** [source](https://gs.statcounter.com/browser-market-share/all/russian-federation)
image

and after testing BBB on it, sadly we don't support it
image

### PR DESCRIPTION
**Pull request by Tainan404**
Closes #8101.
[webrtc test](https://test.webrtc.org/)
image

### CODE REVIEW

**Comment by daminebenq** [comment]
**Problems on iPad and iPhone, it doesn't redirect into the meeting at all after the login page !**
Image from iOS
Image from iOS (1)

**Comment by idemxa** [comment]
@Tainan404 Hi! Could you tell me when this change is supposed to be released?

**Comment by mikhailnov** [comment]
It has been released in v2.3 beta

**Comment by ffdixon** [comment]
You can try it on https://test23.bigbluebutton.org/.

**Pull request merged**
