### PR TITLE
Upgrade to JDK11, library upgrades, upgrade of Scala and SBT.

### PR DESCRIPTION
**Pull request by longliveenduro**
Removed Red5 references from bbb-common-message and fixed sl4j dependency and test fixture errors there.
Improved code in bbb-common-message.
Deleted bbb-fsesl-client/pom.xml because of sbt replacement.
Minor code improvements.
Upgraded bbb-common-message, bbb-common-web, bbb-fsesl-client, akka-bbb-fsesl & akka-bbb-apps build tools, JVM version and dependencies.

### What does this PR do?

Upgrade to JDK11, library upgrades, upgrade of Scala and SBT. Based on the unfinished work here: https://github.com/bigbluebutton/bigbluebutton/pull/8401

### Closes Issue(s)

Closes #

### Motivation

JDK 8 is old and out of (free) support. An upgrade is necessary.

### More

- Based on the unfinished work here: https://github.com/bigbluebutton/bigbluebutton/pull/8401

### CODE REVIEW

**Comment by antobinary** [comment]
Thank you for continuing the work on JVM8 to JVM11, @longliveenduro !
Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

**Comment by longliveenduro** [comment]
@antobinary Cheers, I have sent a copy to Fred Dixons email. I am contracting/freelancing currently for a company, so I told them they should fill this out as well.

**Comment by ffdixon** [comment]
CLA received -- looks good.

**Comment by antobinary** [comment]
@longliveenduro What's your planned timeline for this? We are planning items like https://github.com/bigbluebutton/bigbluebutton/issues/12431 and would like to time it so that it does not cause conflicts /complications with the JVM 11 upgrade...

**Comment by longliveenduro** [comment]
Hi @antobinary, 
I will start to work on this soon. I am currently adding some functionality to bbb-docker to make it better usable for local development.

With that in place my plans were to work on this issue than whilst leveraging bbb-docker for my local development.

**Comment by longliveenduro** [comment]
Hi @antobinary, 
see https://github.com/bigbluebutton/docker/pull/121

**Comment by antobinary** [comment]
Awesome!

**Comment by longliveenduro** [comment]
@antobinary @ffdixon @GhaziTriki Unfortunately I cannot continue working on this ticket. I am very sorry. All the best, Chris

**Comment by GhaziTriki** [comment]
@longliveenduro thank you for all your efforts. What us the status if the PR so we can continué working on it ?

**Comment by iMonZ** [comment]
What about Java 17? It's the next LTS and should come out next week.
There will be still enough time to test the version 17 with BBB 2.5.

**Pull request closed without merging**
