### PR TITLE
Checksum Hash Algorithm Updates

### PR DESCRIPTION
**Pull request by paultrudel**
### What does this PR do?

Adds support for SHA384 and SHA512 checksums. A new property, checksumHash, has been added to the bigbluebutton properties file which allows a user to set what hash algorithm should be used to validate checksums. If no algorithm is defined it defaults to using SHA1.

### CODE REVIEW

**Comment by bwildenhain** [comment]
After upgrading to BBB 2.5.7, I could not authenticate using Greenlight or mconf/api-mate anymore, always got checksum errors (invalid secret for GL). Could this be related to this change?

**Comment by ffdixon** [comment]
Hi @bwildenhain -- check the release notes.  The default calculation is now SHA256, but it's easy to restore support for SHA1 with a configuration change.  See Release Notes for 2.5.7

  https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.5.7

**Comment by AlphaDE** [comment]
@ffdixon I ran into the same problem and wonder why devs break current installations. Yes, the release notes mention this, but there is no relation to greenlight. In my eyes, a minor relase should stay backwards compatible and the default should stick with sha1. I had to dig into the logs and find some strange checksum errors pointing me the way why Greenshield suddenly reported the BBB secret as invalid.

**Comment by kaystrobach** [comment]
This should never happen according to semver.

* adding a new hash algorithm is fine
* changing the default is not

Changing the default for 2.6 is also strange according semver, but still acceptable.

**Comment by defnull** [comment]
This is a breaking change that can not be reverted through configuration. The old behavior was auto-detecting the algorithm based on hash size. This functionality was removed. If you have multiple clients using different algorithms then some of them will stop working, regardless of configuration.

**Pull request merged**
