### PR TITLE
fix(whiteboard): Lower min zoom to 25 percent for infinite whiteboard

### LINKED ISSUE #21103: Infinite whiteboard not handling mouse scroll zoom
**Describe the bug**
When I have enabled infinite whiteboard, have the hand tool and try to zoom out, the whiteboard re-scales to only show the original slide, hides the margins.

**To Reproduce**
1. Enable inifinte wb
2. Draw something in the margin
3. With the margin visible try to zoom out further via mouse wheel scroll

**Expected behavior**
The slide appears even smaller, more room in the margins for annotations.

**Actual behavior**
The margins disappear, the slide is now taking the entire wb space.

**Screenshots**
[Screencast from 2024-09-04 09:21:04 PM.webm](https://github.com/user-attachments/assets/0acce0f8-e57a-4037-9d29-fe1608cf715e)

**BBB version:**
BigBlueButton 3.0.0-beta.1 build 677 circa Sept 4, 2024

### PR DESCRIPTION
**Pull request by KDSBrowne**
### What does this PR do?
This PR updates the zoom functionality on the infinite whiteboard by lowering the minimum zoom level to 25%. This enhancement allows users to zoom out beyond the slide boundary

zoom-out-25

### Closes Issue(s)

Closes #21103

### CODE REVIEW

**Comment by germanocaumo** [comment]
Just an odd behaviour I noticed when zooming out and then back in:
[Tab-1729619191602.webm](https://github.com/user-attachments/assets/f667924b-7228-4246-80af-82e992277594)

I think It would be better if when zooming out via the toolbar, the slide stays centered on the screen

**Review by germanocaumo — CHANGES_REQUESTED** [review]
It's a bit easy to "get lost" in empty space when zooming with mouse wheel and panning, and the "Reset Zoom" don't bring back to center, I think it would be nice to always to back to where the slide is.

https://github.com/user-attachments/assets/f6951ad1-8685-4782-a378-a6ca56c26232

Also, do we really need the infinitewhitebaord as key for tldraw? it makes it reload completely
```
      <Tldraw
        autoFocus={false}
        key={`tldrawv2-${presentationId}-${animations}-${isInfiniteWhiteboard}`}
   ```

**Comment by padaliyajay** [comment]
Can you implement this zoom out feature for BBB version 2.7?

**Comment by padaliyajay** [comment]
It's ok. we only need zoom out below 100% without Infinite feature

**Pull request merged**
