### PR TITLE
Fix unintetionally drawing while using an active pencil

### LINKED ISSUE #11084: Handwriting on Virtual Whiteboard is Impaired by Palm and Finger Artifacts
**Describe the bug**
We use BigBlueButton's HTML5 client since its early beta stages in order to enable handwriting sessions on the virtual whiteboard (by providing empty or checkered slides), especially in mathematics and engineering subjects of our courses. Giving our students (most of them have tablet computers like iPads) the ability to do handwriting using their tablet computers remarkably improved the outcome in our distance-teaching courses. 

While this feature is widely accepted, the user experience is still impaired due to artifacts produced whenever a not-so-trained user touches the whiteboard with his or her palm. Of course, this more often happens to our students because most of our teachers know that they should not let their palms rest on the virtual whiteboard while writing or while explaining in writing breaks.
Almost all modern tablet computers and web browsers are able to distinguish between finger input, mouse input, and pencil input. Unfortunately, BigBlueButton does not seem to evaluate this piece of information. All kinds of pointer events are treated equally and can possibly produce annoying and unwanted drawings. 

It is not uncommon that untrained users try to remove the erroneously produced artifact by clicking the reverse arrow symbol. While doing so, they might also remove their intentionally written pieces - sometimes even worse: they might also press the trash bin symbol and delete everything...

Such a great feature (like a distributed virtual whiteboard) should not come with this kind of usability impairment.

**To Reproduce**
1. Start BigBlueButton's HTML5 client on a tablet computer, e.g. an iPad Pro
2. Open an empty slide
3. Activate the pencil function
4. Write to the virtual whiteboard by using, for example, an Apple Pencil 2. While doing so, let your palm or parts of your hand rest on the tablet.
5. Sooner or later you'll see artifacts produced by the pencil jumping to the position where your palm has touched the tablet, especially when lifting the pencil.

**Expected behavior**
When being in pencil mode and writing with a real pencil device, other inputs should be ignored, at least on a user's demand.

**Actual behavior**
All input devices contribute to the drawing/writing on the whiteboard, also unintentionally.

**Screenshots**
You'll find a screenshot attached.

**BBB version (optional):**
BigBlueButton Server 2.2.31 (2310)

**Tablet, desktop, or smartphone client (please complete the following information):**
 - Device: e.g. iPad Pro 11-inch, Model number: MTXN2FD/A
 - OS: e.g. Apple iPadOS 14.3
 - Browser: (Mobile) Safari
 - Version: 14.0.2

**Additional context**
I am fully aware that it is hard for BigBlueButton to decide upon itself and automatically which kinds of input devices should be ignored in which situation. For this reason, I would propose to make it possible that a user is able to toggle between two modes: a) accepting all kinds of pointer events and b) accepting only pencil events. 

A student of mine is working on a solution for his.

**Attachment**
Screenshot_2020-12-28_11-53-33

### PR DESCRIPTION
**Pull request by jonathansch1**
### What does this PR do?

That PR fixes unintentionally drawing (with the hand on the whiteboard) while using an active pencil (e.g. Apple Pencil).

As mentioned under the issue #11084 the concept of that fix is to add a new button to switch between:

* accepting all kinds of pointer events (finger and pencil touch allowed)
* accepting only pencil events

Therefore the following changes are needed:

* add a new button to the whiteboard toolbar to switch the palm rejection mode
  * include a new icon to the BBB Font for the button
    * a pull request to the BBB Font Repo is prepared and we can submit it if needed
  * add a message to the button and adapt the `locales/en.json`
    * we also add german translation to `locales/de.json`, that they are directly available after merging that into BBB
* save the state of the palm rejection mode in the session storage
* add new event handler for pencil and shape
  * these handlers are based on the existing event handlers and adapt them to use pointer events. The pointer events are needed to distinguish finger touch, pencil touch and mouse input.
  * the handlers accept finger input only if palm rejection is off (finger touch input is allowed)
* add browser sniffing
  * BBB provides palm rejection only, if the browser has implemented pointer events
  * if not, there is a fallback to the existing event handlers

The mouse input isn't affected by palm rejection but also uses the pointer event handler.
### Closes Issue

closes #11084

### Motivation

Fixing that problem increases the whiteboard user experience significant because the notes aren't impaired by palm and finger artifacts.

### More

* That feature was tested for BBB v2.2.x on Windows, MacOS, Linux, iOS and Android. For the Browsers Chrome, Firefox, Edge, Opera, Yandex, Safari.
* For BBB v2.3 it was tested on Windows, MacOS and iOS with Chrome, Firefox and Safari.

The tests were done by a test protocol and cover using the pencil and the shape tools on the BBB whiteboard with and without palm rejection. At the beginning we developed on BBB v2.2 and switch then to v2.3.

All tests were successfully. In Windows with Firefox it's necessary to set *dom.w3c_pointer_events.dispatch_by_pointer_messages = true* in the Firefox config. By default that parameter is *false*. That is a known bug in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1487509). If that isn't set *true* all touch events are handled as finger touch. So pencils doesn't work with palm rejection enabled.

### CODE REVIEW

**Comment by antobinary** [comment]
@jonathansch1 Thank you for your contribution! Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

**Comment by jonathansch1** [comment]
Hi @antobinary I have filled out and signed the CLA and my boss signed it too and has send it to the mail of Fred.

**Comment by ffdixon** [comment]
CLA received -- thanks!

**Comment by jonathansch1** [comment]
I solve the conflict by updating my branch to v2.3-alpha-8

**Comment by jonathansch1** [comment]
I rebased my changes onto the latest version of the develop branch. Thereby I had to do some manual merges to solve the conflicts.

**Comment by antobinary** [comment]
Thank you, @jonathansch1 !

**Comment by jonathansch1** [comment]
The feature is compatible to BBB 2.3-beta-2.

**Comment by steffen-moser** [comment]
We tested the PR also successfully with BBB 2.3-beta-3.

**Comment by antobinary** [comment]
I tested this locally, it worked quite well :clap: 
I got a hold of a tablet with a pen - Samsung Galaxy Tab S6 Lite (Android 11) with stylus. Chrome 87
Could write legibly, pretty smoothly. Tbh it was not too bad for me even without the pen mode, but probably mileage varies depending on device and pen type or writing style.

I could still draw with my finger (while holding the stylo) with the pen mode enabled, but not a major issue I think.

Something odd happened once during my tests - I had my palm and pen down, writing and the slide toolbar disappeared (could not switch slide, could not zoom in, etc). Not necessarily related to the PR but I am mentioning it as this is the first time I hit it, and also I could not collect logs from it... Will be on the look for this.

Thanks for your contribution! I am merging this in, so others can also try it out, different device types / OS / pens, ...

**Review by antobinary — APPROVED** [review]

**Review by daminebenq — APPROVED** [review]
I couldn't reproduce any problem with this PR.

**Comment by LupoWM** [comment]
The above-mentioned "I had my palm and pen down, writing and the slide toolbar disappeared (could not switch slide, could not zoom in, etc)." happened yesterday to me during drawing a diagram on the presentation. 
There seems to be some kind of a problem.
(I suspect -but only later, so I could not verify it- that I was not presenter any more)

**Pull request merged**
