### PR TITLE
Fix: connection status issues

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?
This PR removes rtt precision and fixes the error log when connecting in audio,  the error was being caused by I function that was being not mere useful for the client, theres other funcitons the monitors the audio health.

### CODE REVIEW

**Comment by antobinary** [comment]
@Tainan404 could you please post before vs after?
Could you paste a log line like `Aug 14 19:58:26 dev30 bbb-apps-akka[2181678]: 2024-08-14T19:58:26.420Z INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"UserConnectionAliveReqMsg","routing":{"meetingId":"6b35740de6631a66eb95050a2257036b7ebe5154-1723663625027","userId":"w_8kjqgqzvmqtn"},"timestamp":1723665506419},"core":{"header":{"name":"UserConnectionAliveReqMsg","meetingId":"6b35740de6631a66eb95050a2257036b7ebe5154-1723663625027","userId":"w_8kjqgqzvmqtn"},"body":{"userId":"w_8kjqgqzvmqtn","networkRttInMs":30.200000047683716}}}`

**Comment by Tainan404** [comment]
@antobinary 
```
bbbAppsAkka 2024-08-14T17:38:22.033-03:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"UserConnectionAliveReqMsg","routing":{"meetingId":"ece0cf41a49c0eeff031fb80fd3961eb3588197f-1723667776727","userId":"w_bm0ihastaacu"},"timestamp":1723667902031},"core":{"header":{"name":"UserConnectionAliveReqMsg","meetingId":"ece0cf41a49c0eeff031fb80fd3961eb3588197f-1723667776727","userId":"w_bm0ihastaacu"},"body":{"userId":"w_bm0ihastaacu","networkRttInMs":12.0}}}
```

**Comment by antobinary** [comment]
Thank you, the format looks fine to me!

**Review by ramonlsouza — APPROVED** [review]

**Comment by ramonlsouza** [comment]
closes #20818

**Pull request merged**
