### PR TITLE
Fix user-sent poll result messages

### LINKED ISSUE #11393: [2.3 Only] if a public/private chat message contains "bbb-published-poll-" tag it will show as a chat poll result message
**Describe the bug**
Sending a private/public chat message with `bbb-published-poll-` will show as a chat poll results message.

**To Reproduce**
1. Go to a bbb23 server
2. Go to public/private chat textarea 
3. Type `bbb-published-poll-`

**Expected behavior**
Any chat message sent by a user should be treated as normal chat message showing the avatar + username + message text.
When a user sends a message containing `bbb-published-poll-` it should show as a normal chat message.
image

**Actual behavior**
Sending a message in private or public chat with `bbb-published-poll-` tag will show as a chat poll results message. Which is a systemChatMessage.
image

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

Prevents user messages containing `bbb-published-poll-` from being displayed as poll results, by changing the way poll result messages are parsed before being displayed on chat.

#### New poll result message
Screenshot from 2021-02-17 17-33-06

#### If a user send a message containing `bbb-published-poll-`  now, it will be displayed as any other user message
Screenshot from 2021-02-17 17-30-40

### Closes Issue(s)

closes #11393

### CODE REVIEW

**Comment by pedrobmarin** [comment]
Hi @ramonlsouza ,

I see how this can avoid the problem right now but it does not solve the bigger issue that is having the poll tag at the chat's message content. This should be at least associated with a new issue to tackle all the changes this feature need to be production ready.

**Comment by daminebenq** [comment]
Hi @ramonlsouza 
I just tested this, and I found the following:

https://user-images.githubusercontent.com/5144311/108422663-9d11c800-7215-11eb-87c4-55cfa5d37000.mp4

in the video recorded above, the polling options don't appear at all after choosing what options to ask in the poll.

expected apparance: 
image

current behavior:
image

**Comment by ramonlsouza** [comment]
Thanks for the review @daminebenq

Looks like another PR related to polls was approved before mine, and changed the way polls work on the back-end...

I'm fixing this and will send a new commit soon

**Comment by ramonlsouza** [comment]
conflicts resolved on #11437

**Pull request closed without merging**
