### PR TITLE
Fix whiteboard toolbar icons not rendering

### LINKED ISSUE #6888: The whiteboard toolbar doesn't display thickness and colour correctly in Edge
When I look at the whiteboard toolbar in Edge the selected line size and colour aren't shown in the toolbar. In the image below I had selected the second biggest line thickness and red for my colour.

image

### PR DESCRIPTION
**Pull request by KDSBrowne**
Closes #6888.

also fixes the loading and audio connecting animations.

### CODE REVIEW

**Comment by capilkey** [comment]
Well that was quick

**Comment by antobinary** [comment]
Tested with Maxim on Microsoft Edge - Remaining items:
 * Edge presenter draws all types of annotations but non-Edge viewers only see straight lines, text and rectangles *** drawing annotations was more successful when Settings-> Animations was disabled
 * in the userlist the audio status does not display properly (icons are outside of their encompassing boxes)
 * `no fonts available for @font-face` repeatedly displayed in Edge's console

**Comment by MaximKhlobystov** [comment]
New shapes are light-colored. When I refresh page, they become darker.

**Comment by KDSBrowne** [comment]
> New shapes are light-colored. When I refresh page, they become darker.

That is related to:
https://github.com/bigbluebutton/bigbluebutton/issues/6858

**Pull request merged**
