### PR TITLE
Sanity step - sort events by timestamp

### PR DESCRIPTION
**Pull request by arapoport**
Workaround for #6035. Sometimes events in the events.xml are not properly sorted which results in arhiving failure at next step. This fix always sorts them.

### CODE REVIEW

**Comment by kepstin** [comment]
The idea is good, but I have some comments:
- The sorting of events should happen at the archive step, not the sanity step.
- The ruby sort_by function is not stable by default, meaning it can switch the order of two events with the same timestamp. This may cause issues with certain types of quickly-received events.
- The events array is already "mostly" sorted - individual events may be no more than a place or two off. For this type of data, a different sort algorithm rather than ruby's default quicksort would be preferable - probably insertion sort would be best here.

**Comment by kepstin** [comment]
In particular, I'd recommend changing the code at https://github.com/bigbluebutton/bigbluebutton/blob/master/record-and-playback/core/lib/recordandplayback/events_archiver.rb#L326 to insert the event into the correct spot in the events list directly, using the algorithm from insertion sort.

**Comment by arapoport** [comment]
> 
> 
> In particular, I'd recommend changing the code at https://github.com/bigbluebutton/bigbluebutton/blob/master/record-and-playback/core/lib/recordandplayback/events_archiver.rb#L326 to insert the event into the correct spot in the events list directly, using the algorithm from insertion sort.

I get your idea and agree with it. The hurdle is that I have very little experience with Ruby and doing changes in the middle of a script is a challenge to me. I cannot promise that I will come to it at all.

**Comment by kepstin** [comment]
I've created a new PR with my fix: #6855

**Pull request closed without merging**
