### PR TITLE
Refactor: user talking indicator using ts and graphql

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?

This PR implements the user talking indicator using TS and Graphql

OBS: This component is awaiting the transcribing data be available in the user_voice table

### CODE REVIEW

**Comment by gustavotrott** [comment]
The talking indicator continues to display indefinitely! However, the intended behavior is for it to hide after a few seconds of silence. Please refer to PR #17758 as a starting point.

https://github.com/bigbluebutton/bigbluebutton/assets/5660191/00188e46-4155-4360-a902-f314c676183c

**Comment by gustavotrott** [comment]
I get an error when I'm speaking (with Automatic Transcription) and I click to mute!
In the video I click on the talking indicator, but the error also occours if I click on the Mic button.

https://github.com/bigbluebutton/bigbluebutton/assets/5660191/93c4d7f7-ee13-49d7-845c-c403d5e1d33c

**Comment by gustavotrott** [comment]
When I just shared my Mic, the "CC" background is transparent.
And after some seconds the background become greeen!
It's different that it used to be in bbb 2.6:

- When I just shared:
image

- After a few secs:
image

**Review by gustavotrott — APPROVED** [review]
It's working properly! Lgtm!

**Review by TiagoJacobs — APPROVED** [review]
LGTM

PS: looking forward for the removal of the old files (in further PR)

**Pull request merged**
