### PR TITLE
remove Button outline

### LINKED ISSUE #11970: Network quality visual indicator not fully dislaying (2.3-beta-3)
image

Tested on FireFox 87.0 (64 bits) Windows 10

### PR DESCRIPTION
**Pull request by mrkeksi**
fixes #11970

tested with Firefox and Chrome (Desktop)

### CODE REVIEW

**Comment by antobinary** [comment]
Thanks @mrkeksi !

**Review by KDSBrowne — COMMENTED** [review]
I'm not sure removing the outline-style is the best solution. Doing so causes some issues for accessibility. Specifically for users who rely on windows High contrast themes, they lose the outlines to indicate where their focus is.

high-contrast-outlines

More investigation might be needed to see why it's an issue for Firefox

**Comment by mrkeksi** [comment]
i do not see significant differences with High contrast theme? Except that it is now dotted?

**Comment by KDSBrowne** [comment]
@mrkeksi , the difference is the loss of the solid focus outline. The gif above illustrates the outline.  The gif below shows navigation with the change in this PR, there is no longer a focus indicator on some of the buttons. The dotted outline remains, which is intended to indicate the hover state.

high-contrast-no-outline

**Comment by KDSBrowne** [comment]
Thanks @MrKeksi for pointing out the area of the issue, I found a slightly different solution which doesn't affect the high contrast themes.  PR coming soon.

**Comment by mrkeksi** [comment]
Also you can set the outline in a media Query. 
```
@media screen and (-ms-high-contrast: active) {
  /* All high contrast styling rules */
}
```
But ok its your turn. ;)

**Pull request closed without merging**
