### PR TITLE
Fix poll panel resize bug

### LINKED ISSUE #11946: presentation screen is distorted when survey is resized
When I test the beta version I get the following error.

sizing in the survey area disrupts the presentation screen

2.3-beta-2
https://test23.bigbluebutton.org/

OS : Linux Mint
Browser : Chrome Version 88.0.4324.150 (Official Build) (64-bit)

Presentation screen sizing does not work properly when the survey area is sized with the mouse

bbb-error

### PR DESCRIPTION
**Pull request by hiroshisuga**
### What does this PR do?

Fixes a bug when resizing poll panel

### Closes Issue(s)

Closes #11946

### Motivation

Fix a problem.

### More

- [ ] Added/updated documentation

### CODE REVIEW

**Comment by hiroshisuga** [comment]
By whatever strange reason I cannot reproduce the issue.

**Comment by hiroshisuga** [comment]
Reopen according to the discussion in #11946 .

**Comment by PhMemmel** [comment]
Can be closed in favor of #11997 I think

**Comment by hiroshisuga** [comment]
yes, once #11997 is merged, this one can be closed. thanks a lot!

**Comment by antobinary** [comment]
Thanks @hiroshisuga and @PhMemmel

**Pull request closed without merging**
