### PR TITLE
refactor: Removed all traces of Red5

### LINKED ISSUE #15051: Remove traces of red5
Red5 has not been part of BBB for a few years. However, we still have some code relating to red5. We should check what portions are obsolete and whether removal is desired

I have dropped a few lines from the block below (.git, comments, raw files)

```
$ grep -irn red5
bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala:52:case class ScreenshareProps(screenshareConf: String, red5ScreenshareIp: String, red5ScreenshareApp: String)
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala:313: * Sent from bbb-apps when user disconnects from Red5.
bbb-common-message/src/main/java/org/bigbluebutton/common2/redis/pubsub/MessageSender.java:52:        log.info("Redis org.bigbluebutton.red5.pubsub.message publisher starting!");
bbb-common-message/src/main/java/org/bigbluebutton/common2/redis/pubsub/MessageSender.java:87:                    log.warn("Cannot publish the org.bigbluebutton.red5.pubsub.message to redis", e);
Binary file akka-bbb-fsesl/project/target/scala-2.12/sbt-1.0/classes/org/bigbluebutton/build/Dependencies$Compile$.class matches
akka-bbb-fsesl/project/Dependencies.scala:50:      ExclusionRule(organization = "org.red5"))
record-and-playback/core/scripts/archive/archive.rb:206:# Red5 media
record-and-playback/core/scripts/archive/archive.rb:221:  # Red5 media
record-and-playback/core/scripts/archive/archive.rb:222:  # TODO: need to figure out how to set permissions used when red5 creates directories
record-and-playback/core/scripts/archive/archive.rb:223:  # does this even matter? we're removing red5 soon...
record-and-playback/core/scripts/sanity/sanity.rb:57:def repair_red5_ser(directory)
record-and-playback/core/scripts/sanity/sanity.rb:58:  cp="/usr/share/red5/red5-server.jar:/usr/share/red5/lib/*"
record-and-playback/core/scripts/sanity/sanity.rb:62:      BigBlueButton.logger.info("Repairing red5 serialized streams")
record-and-playback/core/scripts/sanity/sanity.rb:65:        ret = BigBlueButton.exec_ret('java', '-cp', cp, 'org.red5.io.flv.impl.FLVWriter', ser, '0', '7')
record-and-playback/core/scripts/sanity/sanity.rb:100:  repair_red5_ser("#{raw_archive_dir}/#{meeting_id}/video/#{meeting_id}")
record-and-playback/core/scripts/sanity/sanity.rb:103:  repair_red5_ser("#{raw_archive_dir}/#{meeting_id}/deskshare")
record-and-playback/core/scripts/bigbluebutton.yml:3:raw_video_src: /usr/share/red5/webapps/video/streams
record-and-playback/core/scripts/bigbluebutton.yml:8:raw_screenshare_src: /usr/share/red5/webapps/screenshare/streams
record-and-playback/core/scripts/bigbluebutton.yml:9:raw_webrtc_deskshare_src: /usr/share/red5/webapps/video-broadcast/streams
record-and-playback/core/lib/recordandplayback/edl/video.rb:330:          # Red5 writes video files with the first frame often having a pts
```

### PR DESCRIPTION
**Pull request by GuiLeme**
### What does this PR do?

Removes all remaining traces of Red5 from the project.

### Closes Issue(s)

Closes #15051 

### More

It is important to test the following components: 
 - Camera sharing;
 - Desk sharing;
 - Messages in chat;
 - See if nothing crashes on the process of making a recording;
 - Other than that, feel free to test whatever comes in your mind.

**Important:** There are still some fix to the RAP component due to the newly added whiteboard - TL-draw, until then ping me for some work around.

### CODE REVIEW

**Comment by GuiLeme** [comment]
Hey, @kepstin, I just wanted to loop you into this PR to see if you have any suggestions or so. Thank you in advance!

**Comment by kepstin** [comment]
The updates to the recording archive scripts make sense, but not the recording processing scripts.

Current versions of BigBlueButton recording scripts still need to be able to (re-)process recordings made with older versions of BigBlueButton, so the workarounds in place for handling older recording data must be left.

**Comment by GuiLeme** [comment]
@kepstin, nice, then, the only thing I changed in a process script was to take out some comments related to the red5 processing which is not even there anymore (BTW, it was on `video.rb` this change).

**Comment by antobinary** [comment]
Checked with @kepstin . Merging.

**Pull request merged**
