### PR TITLE
refactor: Remove Hasura database-updates and move them to Gql-Actions

### PR DESCRIPTION
**Pull request by gustavotrott**
This PR aims to standardize the mutation flow across our system by transitioning the remaining mutations from the old flow to the new flow, reducing Hasura's load and improving system performance.

#### Old Mutation Flow:
- Browser -> Graphql-Middleware -> Hasura -> Postgres

#### New Mutation Flow:
- Browser -> Graphql-Middleware -> Graphql-Actions -> Redis -> Akka-Apps -> Postgres

#### Changes Implemented:
**Created Mutations:** Added necessary mutations in Graphql-Actions and updated Hasura metadata accordingly.
**Redis Integration:** Set up Redis messages (bbb-common-message) to communicate with Akka-Apps.
**Akka-Apps Handlers:** Implemented handlers in Akka-Apps to process the new mutations.
**Client Component Update:** Updated the client components to utilize the new mutations.
**Permissions Adjustment:** Removed permissions for direct database updates via Hasura to enforce the new flow.

List of mutations migrated:

| Current mutation           | columns                | New mutation (action)          | Redis Message                        |
|----------------------------|------------------------|--------------------------------|--------------------------------------|
| update_user_clientSettings | userClientSettingsJson | userSetClientSettings          | SetUserClientSettingsReqMsg          |
| update_user_current        | echoTestRunningAt      | userSetEchoTestRunning         | SetUserEchoTestRunningReqMsg         |
| update_chat_user           | lastSeenAt             | chatSetLastSeen                | SetGroupChatLastSeenReqMsg           |
| update_chat_user           | visible                | chatSetVisible                 | SetGroupChatVisibleReqMsg            |
| update_breakoutRoom_user   | inviteDismissedAt      | breakoutRoomSetInviteDismissed | SetBreakoutRoomInviteDismissedReqMsg |

### CODE REVIEW

**Comment by antobinary** [comment]
Great! Should we be updating the architecture diagram in https://docs.bigbluebutton.org/3.0/development/architecture/ ?

**Comment by gustavotrott** [comment]
> Great! Should we be updating the architecture diagram in https://docs.bigbluebutton.org/3.0/development/architecture/ ?

No, the Gql-Middlware still communicates with Hasura...

**Review by TiagoJacobs — CHANGES_REQUESTED** [review]
Hello @gustavotrott - thank you for this PR.

As far as I understood, middleware will not send mutations to Hasura anymore.

If this is correct, please remove the code that does it from middleware.

**Comment by gustavotrott** [comment]
> Hello @gustavotrott - thank you for this PR.
> 
> As far as I understood, middleware will not send mutations to Hasura anymore.
> 
> If this is correct, please remove the code that does it from middleware.

You are right!

Done in the last commit.

**Pull request merged**
