### PR TITLE
Update locales

### PR DESCRIPTION
**Pull request by ritzalam**
- remove ru locale and add to .gitignore
 - download only translated locale strings (tx pull -a --mode=onlytranslated)

### CODE REVIEW

**Comment by ritzalam** [comment]
@capilkey Can you please confirm that this is works as you expected?

**Comment by capilkey** [comment]
After you've built it does it show the strings as empty or does it show the English replacement?

**Comment by ritzalam** [comment]
It shows english.

**Comment by capilkey** [comment]
Then I think it's what we want. Ideally the locales would have the line commented out if the value is empty, but what is here sounds like it works.

**Pull request merged**
