### PR TITLE
chore(client): Add logs for recording notify action

### LINKED ISSUE #21134: Log user's choice for consent to record
When users select Continue after being prompted for consent per https://github.com/bigbluebutton/bigbluebutton/issues/14077, that operation ought to be logged and stored somewhere, in the event any future audit requires a record of the user's choice.

### PR DESCRIPTION
**Pull request by antobinary**
### What does this PR do?
Logs whether the user chose to Continue or Leave when presented with the dialog on notifyRecordingIsOn

### Closes Issue(s)

Closes #21134 

### Motivation
Assist administrator with better traceability

### More

To test you need to add

`notifyRecordingIsOn=true`
in `/etc/bigbluebutton/bbb-web.properties` and restart BBB.

Sample of the log:

```
{
  "logCode": "recording_started_notify_user_hit_continue",
  "logDescription": "The user is reminded that recording commences. The user pressed Continue.",
  "connectionId": "jyY7qEuAikyL88Ecm",
  "extraInfo": {
    "clientURL": "https://anton-droplet-4324.do.blindside-dev.com/html5client/join?sessionToken=jpnotrcinmshoc4j"
  },
  "userInfo": {
    "sessionToken": "jpnotrcinmshoc4j",
    "meetingId": "728d334a030f7296a9e0c10210a30e33b9343198-1726240150047",
    "requesterUserId": "w_jxhw30nz8ezz",
    "fullname": "User 4910954",
    "confname": "random-8658568",
    "externUserID": "w_jxhw30nz8ezz",
    "uniqueClientSession": "jpnotrcinmshoc4j-8f0w26"
  }
}
```

- [ ] Added/updated documentation

### CODE REVIEW

**Review by ramonlsouza — APPROVED** [review]

**Comment by pielonet** [comment]
Hi,
In which file do you find these logs ?

**Comment by pielonet** [comment]
Hi @prlanzarin,

Something seems unclear : you tell me logs aren't sent to the server by default. This is contradictory with what is stated here (https://docs.bigbluebutton.org/administration/configuration-files/#logs-sent-directly-from-the-client):

The default values are:
```
clientLog:
  server: { enabled: true, level: info }
  console: { enabled: true, level: debug }
  external:
    {
      enabled: false,
      level: info,
      url: https://LOG_HOST/html5Log,
      method: POST,
      throttleInterval: 400,
      flushOnClose: true,
    }
```
If I read well : server logs are enabled by default at info level.

If I understand well logs to server are enabled by default... but the associated endpoint on the BBB server has to be created : Is that right ? Why isn't the endpoint on the BBB server also enabled by default ?

**Comment by pielonet** [comment]
@prlanzarin thanks for the explanation !

**Comment by pielonet** [comment]
@prlanzarin  One more question (as this not obvious):

How  much pressure does enabling the external logger put on the client ? And on the server ?
Would you recommend enabling it in production on a large deployment (more than 20 rooms per server) ?

**Pull request merged**
