### PR TITLE
Utilize Meteor session id instead of trusting client side meetingI…

### PR DESCRIPTION
**Pull request by antobinary**
…d, userId

Known bugs:
 ~~1) cannot upload presentation - the requestPresentationUploadToken publish is not resubscribed with valid this.userId~~

### CODE REVIEW

**Comment by capilkey** [comment]
Joined audio, tried to mute from the action bar.
```
Exception while invoking method 'toggleSelfVoice' TypeError: Cannot read property 'split' of undefined
```

User inactivity is triggering from old data, but something doesn't seem correct with it.
```
I20200207-14:55:13.035(-8)? info: Detected inactive user, userId:w_d8i9n1ju7ngb, meetingId:183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1581112708707
I20200207-14:55:13.035(-8)? info: Skipping userLeaving. Could not find hrpS8gxXsK9dpPL5T in [object Object]
I20200207-14:55:13.036(-8)? info: Detected inactive user, userId:w_fvf8c4xrhiyo, meetingId:183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1581112708707
I20200207-14:55:13.036(-8)? info: Skipping userLeaving. Could not find r3pH6LAKRoNmECPnt in [object Object]
```

I started a poll. The other people can vote, but the presenter doesn't see the poll information and the following error is in the console.
```
Warning: Failed prop type: The prop `publishPoll` is marked as required in `LiveResult`, but its value is `undefined`.
    in LiveResult (created by InjectIntl(LiveResult))
    in InjectIntl(LiveResult) (created by Poll)
```

I can't seem to stop sharing an external video. No errors in the client or the server.

**Comment by capilkey** [comment]
Error when kicking a user.
```
I20200207-15:12:56.966(-8)? Exception while invoking method 'removeUser' { Error: Match error: Expected string, got undefined
I20200207-15:12:56.966(-8)?     at check (packages/check/match.js:36:17)
I20200207-15:12:56.966(-8)?     at MethodInvocation.removeUser (imports/api/users/server/methods/removeUser.js:12:3)
```

When a client disconnects it never leaves. All I see is a bunch of printouts with the follow.
```
Skipping userLeaving. Could not find wbgJPTrg6cNuZQpke in 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1581117479079
```

**Comment by capilkey** [comment]
Unsure on the trigger for this one, but saw this in the server logs.
```
I20200207-15:30:16.134(-8)? error: MeetingDestroyedEvtMsg: TypeError: Cannot read property 'split' of undefined
I20200207-15:30:16.134(-8)?     at extractCredentials (imports/api/common/server/helpers.js:80:40)
I20200207-15:30:16.135(-8)?     at destroyExternalVideo (imports/api/external-videos/server/methods/destroyExternalVideo.js:6:25)
I20200207-15:30:16.135(-8)?     at EventEmitter.handleMeetingDestruction (imports/api/meetings/server/handlers/meetingDestruction.js:13:3)
```

Reloaded the client after leaving the meeting.
```
I20200207-15:33:32.888(-8)? Exception while invoking method 'userChangedLocalSettings' TypeError: Cannot read property 'split' of null
I20200207-15:33:32.889(-8)?     at extractCredentials (imports/api/common/server/helpers.js:80:40)
I20200207-15:33:32.890(-8)?     at MethodInvocation.userChangedLocalSettings (imports/api/local-settings/server/methods/userChangedLocalSettings.js:8:42)
```

**Comment by antobinary** [comment]
In https://github.com/bigbluebutton/bigbluebutton/pull/8613/commits/1fa426058fcd3af13d470aa6c864512e65ef90ad and https://github.com/bigbluebutton/bigbluebutton/pull/8613/commits/0834f4bdcc9d53ac003a9c5f9cd87729ffd1fd91 I corrected multiple issues:

- [x] mute functionality is recovered
- [x] receiving poll votes functionality is recovered
- [x] kicking a user functionality is recovered
- [x] end meeting functionality is recovered
- [x] the detection for inactive users and their removal is recovered/improved?
- [x] I did not spot issues with external video starting/stopping

I am not aware of any remaining issues, so reviewers are encouraged to re-test.

**Pull request merged**
