### PR TITLE
Hide slide controls of presentation has only one slide

### PR DESCRIPTION
**Pull request by Tainan404**
Hide the slide controls when the presentation has only one slide

### CODE REVIEW

**Comment by capilkey** [comment]
Why hide them? Seems like a strange choice rather than just having the buttons disabled.

**Comment by Tainan404** [comment]
This was a design request from Tyler

**Comment by capilkey** [comment]
At the moment the HTML5 client has half of the presentation controls, but once it's finished it's going to look very strange with just zoom, fit-to-page, and fit-to-width. Having the slide change buttons disabled, but shown also reinforces that there's only one slide available rather than giving the impression that the UI is broken or malfunctioning. @tylercopeland

**Comment by tylercopeland** [comment]
@Tainan404 Based on updated designs I've been working on (includes all the presentation controls), we can remove this request.

**Comment by antobinary** [comment]
Following the conversation in the thread I am closing the PR as the requirements have changed

**Pull request closed without merging**
