### PR TITLE
Web notification

### LINKED ISSUE #3587: Add desktop notifications to the Flash/HTML5 clients
Potential feature, it would be great to have desktop notifications, similar to the ones you can see in Slack or Youtube:

notification_final_2

Desktop notifications usually appear when the browser tab is not active.

I can think of a few cases where they can be useful for us, for example:
- for presenters:
  - a presenter is sharing their desktop (assuming they use only 1 screen). They will be able to see who raised the hand or even follow the chat messages while sharing the screen
  - a presenter has office hours and he might want to use them to see who joins the meeting or asks questions in the chat, without having to constantly check the meeting
  - potentially we can give presenters a way of how they can notify everybody of a start of a lecture (notifications will appear just for non-active users)

- for users
  - users receive new private/public chat messages when the client tab is not active (can be also useful for moderators)
  - users were invited to a breakout room while the tab is not active

We can ask users to turn desktop notifications on right after logging in, and provide a way to disable notifications from the Settings menu.

### PR DESCRIPTION
**Pull request by mojtaba82**
### What does this PR do?

This PR push web notification desktop when someone send message and browser is not focused or page is not active.

### Closes Issue(s)
Closes #3587

### CODE REVIEW

**Comment by antobinary** [comment]
Thank you for your work @mojtaba82 
I see you sent essentially the same work to both 2.2 and 2.3 (develop) branches. I will close this (2.2.x) pull request as we have fully moved the development to 2.3 and are only sending patches on 2.2.
On 2.3 ( #11851 ) we're happy to review and test this work.
Thanks again!

**Comment by mojtaba82** [comment]
Hi @antobinary 
I develop this for 2.2 version and wrongly sent it for 2.3 version.
Please close 2.3 pull request and if it is possible review this for 2.2 version.
Thanks

**Comment by antobinary** [comment]
Hi @mojtaba82 ,
I do not really anticipate more 2.2.x releases (see https://github.com/bigbluebutton/bigbluebutton/issues/8937 and https://github.com/bigbluebutton/bigbluebutton/issues/8474)
BBB 2.3 has already seen a few beta iterations, another one coming this week. I hope you'd be ok with targeting 2.3 for this good work!

**Comment by mojtaba82** [comment]
> I hope you'd be ok with targeting 2.3 for this good work!

Sure.
You are a great team. thanks all of you.

**Pull request closed without merging**
