### PR TITLE
Fix layout bug when using poll

### PR DESCRIPTION
**Pull request by vitormateusalmeida**
This PR is a work around to broken layout when open/close panels. Added a small delay to dispatch event to update de context.

### CODE REVIEW

**Comment by antobinary** [comment]
We are discussing this, let's not test yet

**Review by daminebenq — APPROVED** [review]

**Review by antobinary — CHANGES_REQUESTED** [review]
Thanks for the test, Amine but I really would prefer to hold on with this. Hopefully we ship the Layout manager on 2.4 rather than including these timeouts...

**Comment by pedrobmarin** [comment]
Hi @vitormateusalmeida , is this work still valid?

**Comment by vitormateusalmeida** [comment]
> Hi @vitormateusalmeida , is this work still valid?

No, it can be closed.

**Pull request closed without merging**
