### PR TITLE
Fix for random user picking: presenter is notified when there's no viewers to randomly pick from

### PR DESCRIPTION
**Pull request by MaximKhlobystov**
### What does this PR do?

This PR introduces a small fix for random user picking. The modal that says there's no viewers to pick from didn't work properly. This PR makes sure presenter sees such modal when the meeting consists of moderators only.

### CODE REVIEW

**Comment by hiroshisuga** [comment]
Nice PR! This will fix #11209. Thanks a lot!

However, in my server, bbb-html5 still gives persistent errors that userId is undefined in api/meetings/server/handlers/selectRandomViewer.js and api/meetings/server/modifiers/updateRandomViewer.js. 

One solution is to remove checking (userId is string) in both codes, although there will still be another error happening when updating MongoDB.

I would humbly suggest that we should emit a message with moderator's ID from akka-bbb-apps even without a viewer. My solution is #11210, which I do neither feel the best one..

**Review by antobinary — APPROVED** [review]
Looks good to me!
Appreciated the restructuring with comments!

**Comment by antobinary** [comment]
@MaximKhlobystov 

Could you say anything more about

>However, in my server, bbb-html5 still gives persistent errors complaining userId is undefined in api/meetings/server/handlers/selectRandomViewer.js and api/meetings/server/modifiers/updateRandomViewer.js.
>One solution is to remove checking [userId is string] in both codes, although there will still be another error happening when updating MongoDB.

and

> emit a message with moderator's ID from akka-bbb-apps even without a viewer. My solution is #11210, which I do neither feel the best one..

**Comment by hiroshisuga** [comment]
by whatever magic (or just im stupid), i do not see the errors anymore. Sorry for the confusion.

**Pull request merged**
