### PR TITLE
Detach libreoffice from bbb-web ( running as a docker container )

### PR DESCRIPTION
**Pull request by tdjac0bs**
This PR turns libreoffice into a systemd service that runs inside a docker container.

# 1 - Rebuild bbb-web
https://docs.bigbluebutton.org/2.2/dev.html#developing-bbb-web

# 2 - Install the libreoffice container/scripts
## Install
```
cd bbb-libreoffice
sudo ./install.sh
```

To test, run:
``` 
telnet 127.0.0.1 8201 
```

## Uninstall

```
cd bbb-libreoffice
sudo ./uninstall.sh
```

### CODE REVIEW

**Comment by tdjac0bs** [comment]
It would be good to integrate this patch as a subsequent PR: https://github.com/bigbluebutton/bigbluebutton/pull/9763#issuecomment-643781637

**Comment by ffdixon** [comment]
Merging this now so we can start testing it in BigBlueButton 2.3.

**Comment by dasJ** [comment]
I want to repeat my previous statement: Why prefix every number with `0` when the `0` is hard-coded? This would mean my 10th process would be `010` which makes no sense at all. This makes the ugly ` if (($INSTANCE_NUMBER >= 1 && $INSTANCE_NUMBER <= 10)); then` completely unnecessary.

Also I'd like to point out the existence of [template unit files](https://fedoramagazine.org/systemd-template-unit-files/), making the ugly `sed` thing for the systemd units completely unnecessary.

Also (it's weird I have to point that out), there is `set -e` in bash which exits the shell script if an error occurs, instead of just continuing. It's not just good practice, it also makes the system more resilient since systemd is able to spot more failure conditions.

**Comment by tdjac0bs** [comment]
Hello @dasJ, thank you for the feedback ( welcome to send more! )

We're validating the concept of using docker for this. Once this usage is validated we'll have a round of refactoring in this code and we're probably going to:

- remove the hard coded `0` prefix ( using a proper lpad method ) ;
- simplify the systemd config by using [template unit files](https://fedoramagazine.org/systemd-template-unit-files/) ;
- add the number of converters in a config file ( this is something that we need to think how to do - as we'll need as many systemd units as defined in config file );

However, I don't agree with you that having a `set -e` is a bad practice, because it ensures that any unexpected error will make the unit to fail ( sysadmin will be aware of that ). And it seems I'm not alone:

image

**Comment by tdjac0bs** [comment]
Hello @basisbit, thank you for this feedback, however this docker is already using an unprivileged user, please see this line: https://github.com/bigbluebutton/bigbluebutton/pull/9977/files#diff-4192fd233ff7b3c6d2c0a00ea48662bdR24

If I'm missing something, please let me know.

**Comment by dasJ** [comment]
@tdjac0bs I think you got me wrong here. It's bad practice to **not** have it (like the scripts in this PR and most of this repo).

**Comment by tdjac0bs** [comment]
@dasJ you're right, it should be there!

So our final turns into:
1. remove the hard coded `0` prefix ( using a proper lpad method ) ;
2. simplify the systemd config by using [template unit files](https://fedoramagazine.org/systemd-template-unit-files/) ;
3. add the number of converters in a config file ( this is something that we need to think how to do - as we'll need as many systemd units as defined in config file );
4. add `set -e` in scripts to make it fail on first failure inside the script;


Any idea for the item 3? How we can make the number of systemd processes dynamic?

**Comment by tdjac0bs** [comment]
This PR covers the discussed items here: https://github.com/bigbluebutton/bigbluebutton/pull/10117

**Pull request merged**
