### PR TITLE
Isolated access to multiuser whiteboard by lock-user setting

### LINKED ISSUE #10088: Whiteboard: show/hide works by participants
**Is your feature request related to a problem? Please describe.**
Sometimes in the multi-user whiteboard, a teacher wants to hide the drawings of students during they work, and then show them all at once. By this, the teacher can let students work without seeing the answers from the other students.

**Describe the solution you'd like**
To implement a button in the room owner's whiteboard controller, which can toggle show/hide the drawings of the students in the client's screen while each student can draw whatever within his screen. This toggle should not affect the screen of the teacher, who should see the works of students irrespective of this show/hide mode.

**Additional context**
In the Flash client there seems to have been a setting to show/hide the controller in the client. If there is something like a "single-user whiteboard" mode where each user can draw whatever he wants, which will be send to the server only when the multi-user mode is on, it would also be OK.

### PR DESCRIPTION
**Pull request by hiroshisuga**
### What does this PR do?

Adds an "isolated" multiuser whiteboard mode, in which annotations of the other annotators are invisible to non-presenter annotators. The annotations of the presenter can be seen from everybody. Non-annotators can also see every annotation by anybody.

The isolated multiuser mode and the normal multiuser mode can be switched in the lock-user modal. When you turn off the isolated multiuser mode, all the annotations will be visible to everybody. 

This PR is an updated version of  #10634, #10830, and #10975, but completely rewritten (and much simplified - I am learning slowly how BBB works;-) upon the latest code. This does not use the DOM, so any skilled students can not peep the others using the developer tool. 

### Closes Issue(s)

closes #10088 #10634 #10830 #10975 .

### Motivation

In a class you may want to ask all (or selected) students to work on the whiteboard, preventing them from seeing the others' answers. After finishing the work, you will disclose all the answers.

### More

This PR basically add one lock-user setting. Without toggling it, it is just the individual multiuser whiteboard already implemented since 2.3b1.

multiuser

### CODE REVIEW

**Comment by hiroshisuga** [comment]
Confirmed that it works on 2.3b1.

**Comment by hiroshisuga** [comment]
confirmed it is working on 2.4rc1

**Comment by antobinary** [comment]
Hi @hiroshisuga 

Do you have any mechanism in place so that Student A, B and C don't draw/write on the same spot? Given that they won't see each other's annotations and the moderator(s)/instructor will see something hard to read

**Comment by hiroshisuga** [comment]
Hi @antobinary , no I didn't implement any such mechanism. I remember now somebody pointed it out somewhere. I try to consider it more seriously. Any idea for the UI?
BTW in the BBB conference in last year @ffdixon presented a plan to implement a function to survey the individual (and isolated) whiteboards on a screen (whiteboard vision or something like that). How is that plan going?

**Comment by ffdixon** [comment]
> BTW in the BBB conference in last year @ffdixon presented a plan to implement a function to survey the individual (and isolated) whiteboards on a screen (whiteboard vision or something like that). How is that plan going?

It's still planned -- we're working on figuring out the near-term updates for the whiteboard.  We haven't started on Whiteboard vision yet, this pull request is a step towards that goal.  

Look for some more updates in the coming weeks on the plans for the whiteboard.

We appreciate @hiroshisuga all the pull requests you have sent us.

**Comment by antobinary** [comment]
Hi @hiroshisuga

Thank you for this contribution! However, this pull request is targeting BigBlueButton 2.3 which is no longer supported - https://groups.google.com/g/bigbluebutton-dev/c/jzGiM3kjwzk

As an aside #14976 in BBB 2.6 is using a really different code base for the whiteboard, so I am not sure if this work could be easily ported. Also, the cursor porion of this PR has been implemented in 2.5 as far as I know (via new lock setting), so only the annotation propagation should be missing

**Pull request closed without merging**
