### PR TITLE
Change abs paths to use baseName config 

### PR DESCRIPTION
**Pull request by musickiper**
Fix for #5234

### CODE REVIEW

**Comment by Tainan404** [comment]
Why did you change the file permission?

**Comment by musickiper** [comment]
Ok thanks. I will fix it and push it again

**Comment by capilkey** [comment]
The file permission changes are from the samba configuration https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-config/bin/bbb-conf#L741-L750.

**Comment by musickiper** [comment]
I fixed the cursor image problem but I have no idea of changing font links...

**Comment by oswaldoacauan** [comment]
To fix the relative stuff inside CSS you need to do one of the following:
 - Load the fonts via Javascript. See [WebFontLoader](https://github.com/typekit/webfontloader#readme)
 - Add a `<base>` tag and change everything else to relative. See [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)

**Pull request merged**
