### PR TITLE
Add Afrikaans language af.json to BBB

### PR DESCRIPTION
**Pull request by victorcorreia1984**
Created afrikaans json file from Dutch base and started translation.

### Closes Issue(s)

Closes #

### More

- [x] Added/updated documentation

### CODE REVIEW

**Comment by antobinary** [comment]
Update - I saw you requested to translate BBB 2.2 html5. Instead I invited you to translate 2.3

**Comment by victorcorreia1984** [comment]
Hi Anton

Thanks for your reply. Yes, I have a transifex account. 

I am victorcorreia1984 on transifex.

Would appreciate it if you can add me to the transifex Afrikaans project. 

Regards. Victor.

**Comment by victorcorreia1984** [comment]
Ok, I wil translate 2.3. 

Thank you. V

**Comment by victorcorreia1984** [comment]
Hi, thank you for adding me to transifex. Problem solved.

**Comment by victorcorreia1984** [comment]
I completed the translation of Afrikaans on Transifex. Can these changes please be pushed to github?

**Pull request closed without merging**
