### PR TITLE
Fix: External video skipping

### PR DESCRIPTION
**Pull request by Scroody**
### What does this PR do?

This PR fixes the external video skipping

### CODE REVIEW

**Comment by gustavotrott** [comment]
I was curious about this url:
image

But looks like it is official https://support.google.com/youtube/answer/171780

image

**Comment by antobinary** [comment]
I was curious too -- seems legitimate and loooots of people online seem to question the legitimacy indeed.

**Comment by antonbsa** [comment]
I'm still able to reproduce the video skipping. Right before commenting here, I could only face it in a remote server (higher latency), however, I could have it in a local environment:

image

with the video playing, I changed the presenter and the duration time differed for both.

I thought it could happen for videos I've already shared in another moment/meeting in the same browser (cache, cookies ?) but with random videos never shared I could see the same

**Review by antonbsa — APPROVED** [review]
I can still reproduce the video skipping but only in certain cases. I feel that successive presenter changes make it easier to hit it. In most of the attempts I started sharing random videos, I couldn't see any difference between the playback time for the users. This difference is more noticeable when sharing a long video (e.g. 10 hr). I believe we can merge it and check later these edge cases

**Pull request merged**
