### PR TITLE
Disable libreoffice document update ( speed up the conversion )

### PR DESCRIPTION
**Pull request by tdjac0bs**
Speedup the conversion of office documents by disabling the document update feature

### CODE REVIEW

**Comment by bwildenhain** [comment]
Shouldn't this be tagged with the label "Security" as this seems to be not a speed improvement, but also a security risk (also the title is misleading)?

**Comment by ffdixon** [comment]
Updated the title and tagged with security.

**Comment by rugk** [comment]
Backref to the [Golem.de article about the BigBlueButton security management](https://www.golem.de/news/big-blue-button-das-grosse-blaue-sicherheitsrisiko-2010-151610-2.html) (German)

**Comment by Commifreak** [comment]
So, it is assumed to be "safe" currently?

**Comment by bwildenhain** [comment]
> So, it is assumed to be "safe" currently?

This patch has been merged into BBB 2.2.27. If you are using a current stable release (2.2.27 or 2.2.28), you are using a release which isn't affected by this issue anymore.

**Pull request merged**
