### PR TITLE
refactor(guest-wait): turn guest wait page into a React component

### LINKED ISSUE #20000: Users get 'lost' when allowing entry to meeting
**Describe the bug**

I am not 100% certain if this is server core or greenlight.
I am staging out the new v3.0.0-alpha.5.
If i put a 'large' number of users into the waiting to enter state, and then allow them in, some will get stuck and not enter the meeting. The user still sees the 'waiting, X in queue'.

**To Reproduce**
1. Start a meeting
2. In ~30 browser tabs on one or more machines with enough horsepower, join the meeting as a guest
3. In the moderator part of the meeting, select 'allow everyone' under waiting users
4. Observe the number of users in the left does not equal the number you had waiting, and, some are still waiting
these users are now stuck, you cannot manually allow them, if they refresh they still show as waiting. they must create a new session.

**Expected behavior**
All waiting users enter the meeting.

**Actual behavior**
about 10-20% of the users, randomly, are still in waiting.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 and 24.04 destop
 - Browser Chrome, FIrefox

**Smartphone (please complete the following information):**
did not try

**Additional context**
I am not sure what logs to look in or where to diagnose it.
is it a problem in e.g. redis?  is a message getting dropped? How may i provide more info here.

Above, i said i was uncertain as to whether it was greenlight or core, i am not sure which manages these sessions.

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

Turns the guest wait page into a React component.

### Closes Issue(s)

Closes #20000

### CODE REVIEW

**Comment by antobinary** [comment]
May we remove these 400 lines? https://github.com/bigbluebutton/bigbluebutton/blob/v3.0.0-alpha.6/bigbluebutton-html5/private/static/guest-wait/guest-wait.html

**Comment by JoVictorNunes** [comment]
I think the API is not redirecting `/join` calls to `/html5/join` yet, it is still redirecting to `/html5/guestWait`.

Is that right, @gustavotrott?

**Comment by gustavotrott** [comment]
> I think the API is not redirecting `/join` calls to `/html5/join` yet, it is still redirecting to `/html5/guestWait`.
> 
> Is that right, @gustavotrott?

Is, but I will change it as soon as this PR be merged!
API just need to redirect to the client, and the client will manage the flow.

**Comment by gustavotrott** [comment]
Actually I will remove `/guestWait` from the API and send a PR to your branch @JoVictorNunes .

This way we use this PR to change all necessary parts.

**Comment by JoVictorNunes** [comment]
Sounds like a plan!

**Comment by gustavotrott** [comment]
Could you check if the meeting is running in a higher level in the presence manager?

[Screencast from 2024-05-30 19-22-21.webm](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/409efe6f-2981-492a-bba5-146aeb3ce55f)

**Comment by gustavotrott** [comment]
I'm sending a PR (https://github.com/JoVictorNunes/bigbluebutton/pull/7) that will:

- Remove the config `defaultGuestWaitURL`
- Remove API endpoint `/guestWait` (now the Client will handle it)
- Move rountine `WaitingGuestCleanupTimerTask` from bbb-web to akka-apps

**Comment by gustavotrott** [comment]
It will close #20000

**Review by ramonlsouza — APPROVED** [review]

**Pull request merged**
