### PR TITLE
fix(connection-status): add messages for critical connections

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

Adds two more notification bar messages for critical connections.
Adds warning codes for each message.

**Connection is unstable. Please check your internet connection (code 3004)**:

1. User is still connected to graphql server.
2. User is not receiving data from graphql server **OR** user is not receiving ping messages from graphql server.
3. The RTT status is `critical`.

Screenshot from 2024-07-15 13-25-25

---

**Unable to connect. Please check your internet connection (code 3002)**:

1. User lost connection to graphql server.
2. The RTT status is `critical`.

Screenshot from 2024-07-15 13-26-45

### CODE REVIEW

**Comment by gustavotrott** [comment]
I suggest to inform the reason why the user should "Check your connection.".

e.g: "Data is slow to load. Please check your internet.".

**Comment by gustavotrott** [comment]
I'm trying to organize all possible error messages based on [this PR](https://github.com/bigbluebutton/bigbluebutton/pull/20630) and incorporating the message you are adding in this PR (which would be the 3rd line). Could you please confirm if these are the possible messages?

| Situation                          | Error message |
|---------------------------------------------------------------------|---------------------------------------------|
| Graphql disconnected (trying to reconnect)                          | Lost connection. Please check your internet |
| Graphql connected but not receiving data                            | Server not responding. Please wait          |
| **Graphql connected but not receiving data + RTT critical**             |                                             |
| Graphql connected and receiving data, but not receiving Hasura PING | Data is slow to load. Please wait           |

Once you confirm, we can decide on the best message for each situation.

**Comment by antobinary** [comment]
If we're able to distinguish these cases, I'm considering adding some code, like 7001, 7002 etc and documenting what that means. What do you think?

**Comment by gustavotrott** [comment]
> If we're able to distinguish these cases, I'm considering adding some code, like 7001, 7002 etc and documenting what that means. What do you think?

I think it would be really helpful!

**Comment by JoVictorNunes** [comment]
> I suggest to inform the reason why the user should "Check your connection.".
> 
> e.g: "Connection unstable. Please check your internet.".
> 
> Or maybe use the message that was designed for a similar situation: "Server not responding. Please wait."

Agreed!

**Comment by JoVictorNunes** [comment]
> I'm trying to organize all possible error messages based on [this PR](https://github.com/bigbluebutton/bigbluebutton/pull/20630) and incorporating the message you are adding in this PR (which would be the 3rd line). Could you please confirm if these are the possible messages?

That's right. The first table shows all possible messages (including the one added by this PR).

**Comment by JoVictorNunes** [comment]
> It would be great to add one more status (2nd line), and use the following messages:

I have no objections to the messages presented in the second table, they're pretty clear messages in my opinion.

**Comment by gustavotrott** [comment]
New proposal of messages defined in a talk with @JoVictorNunes @antobinary:

| Situation                          | Error message |
|---------------------------------------------------------------------|---------------------------------------------|
| Graphql disconnected (trying to reconnect)              | Reconnection in progress (error 3001) |
| **Graphql disconnected (trying to reconnect) + RTT critical**  | Unable to connect. Please check your internet connection (error 3002) |
| Graphql connected but not receiving data             | Server is currently not responding. Reconnection in progress (error 3003)  |
| **Graphql connected but not receiving data + RTT critical**  |   Connection unstable. Please check your internet connection (error 3004)  |
| Graphql connected and receiving data, but not receiving Hasura PING | Data is loading slowly. Reconnection in progress (error 3005)  |

**Review by ramonlsouza — APPROVED** [review]

**Pull request merged**
