### PR TITLE
auto-reconnect

### PR DESCRIPTION
**Pull request by pedrobmarin**
I made some fixes and merged Felipe's work.

### CODE REVIEW

**Comment by capilkey** [comment]
Should this be sent to bbb/master or bbb/development? I think the bbb-apps parts will be in conflict with the changes made to split bbb-apps up.

**Comment by pedrobmarin** [comment]
Hi Chad. I don't know. Felipe told me to merge with master. If you guys want this on development we can do it too.

**Comment by pedrobmarin** [comment]
Leave it open, I guess. Tomorrow I'll check up with him and we get back to you guys.

**Comment by ritzalam** [comment]
Closing. I am just testing against master.

**Pull request closed without merging**
