### PR TITLE
Fix create meeting with multi presentations will set all of them to current

### PR DESCRIPTION
**Pull request by zhu**
The system seems that can only process with only one current presentation.
But create meeting with multi pre-upload presentations will set all of them to current.

### CODE REVIEW

**Comment by ffdixon** [comment]
Thanks!  Could you to send us a signed contributor agreement so we can review/merge in these fixes to BigBlueButton code base.  See

   http://docs.bigbluebutton.org/support/faq.html#contributing-to-bigbluebutton

**Comment by antobinary** [comment]
Note resemblance to another PR still not merged #6043  https://github.com/bigbluebutton/bigbluebutton/pull/6043/commits/1cef436037405e78bca11fa696f5f6cf12615a73

**Comment by ffdixon** [comment]
Thanks for signing the contributor agreement!

**Comment by GhaziTriki** [comment]
When I use this request body

```xml
<?xml version="1.0" encoding="UTF-8"?>
<modules><module name="presentation"><document url="https://placeholdit.imgix.net/~text?txtsize=96&amp;bg=30406B&amp;txtclr=ffffff&amp;txt=BigBlueButton&amp;w=800&amp;h=600"/></module></modules>
```

or

```xml
<?xml version="1.0" encoding="UTF-8"?>
<modules><module name="presentation"><document url="https://placeholdit.imgix.net/~text?txtsize=96&amp;bg=30406B&amp;txtclr=ffffff&amp;txt=BigBlueButton&amp;w=800&amp;h=600" filename="placeholder.png"/></module></modules>
```

I get the following error in logs
```
2018-10-16T16:42:37.849Z ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver  - MissingMethodException occurred when processing request: [POST] /bigbluebutton/api/create
No signature of method: org.bigbluebutton.web.controllers.ApiController.downloadAndProcessDocument() is applicable for argument types: (java.lang.String, java.lang.String, java.lang.Boolean) values: [https://placeholdit.imgix.net/~text?txtsize=96&bg=30406B&txtclr=ffffff&txt=BigBlueButton&w=800&h=600, ...]
Possible solutions: downloadAndProcessDocument(), downloadAndProcessDocument(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object). Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: org.bigbluebutton.web.controllers.ApiController.downloadAndProcessDocument() is applicable for argument types: (java.lang.String, java.lang.String, java.lang.Boolean) values: [https://placeholdit.imgix.net/~text?txtsize=96&bg=30406B&txtclr=ffffff&txt=BigBlueButton&w=800&h=600, ...]
Possible solutions: downloadAndProcessDocument(), downloadAndProcessDocument(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)
	at org.bigbluebutton.web.controllers.ApiController$_uploadDocuments_closure22$_closure135.doCall(ApiController.groovy:1858)
	at org.bigbluebutton.web.controllers.ApiController$_uploadDocuments_closure22.doCall(ApiController.groovy:1851)
	at org.bigbluebutton.web.controllers.ApiController.uploadDocuments(ApiController.groovy:1845)
	at org.bigbluebutton.web.controllers.ApiController$_closure3.doCall(ApiController.groovy:167)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

@zhu Could you please fix it?

**Pull request merged**
