### PR TITLE
Add why did you render lib

### PR DESCRIPTION
**Pull request by vitormateusalmeida**
Add the Why did you render library. ([https://github.com/welldone-software/why-did-you-render](https://github.com/welldone-software/why-did-you-render))

### CODE REVIEW

**Comment by pedrobmarin** [comment]
Hey @vitormateusalmeida ,

Could you provide an example of this lib output and CPU consumption with and without it?

**Comment by vitormateusalmeida** [comment]
By default this library doesn't affect performance, it will only cause performance impact when you enable it for a component, for instance, running this on browser's console:
```
require('/imports/ui/components/nav-bar/component.jsx').default.whyDidYouRender = {
    logOnDifferentValues: true,
    customName: 'Navbar',
  }
```
Here goes a recording of CPU consumption with develop ( 1.000 chat messages ):

https://user-images.githubusercontent.com/9675166/129786590-d2daf734-8119-4a05-be00-c0c4df6e3c65.mp4

Here goes a recording of CPU consumption with this PR ( 1.000 chat messages ):

https://user-images.githubusercontent.com/9675166/129786542-245a3530-e640-4831-b21c-d4833636a413.mp4

**Comment by TiagoJacobs** [comment]
It would be good to merge, so @antonbsa can create some tests using this info.

To be noted, the library is only required in development, so we should not have any impact in packaged version.

**Comment by antobinary** [comment]
If the package is not used in production we should move the package.json line to `devDependencies` @vitormateusalmeida

**Pull request merged**
