### PR TITLE
Update rap-process-worker.rb to handle timestamps

### PR DESCRIPTION
**Pull request by dseral**
This commit fix process_archived_meetings random file picking. So after that this script care with processed file according to their timestamps.

### CODE REVIEW

**Comment by antobinary** [comment]
@dseral  Thank you for your contribution! Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

**Comment by dseral** [comment]
Hello Anton,
Actually I have send that agreement about 20 days ago to Fred..
But i can send again if you want!

 IMG-6141.jpg
<https://drive.google.com/file/d/1FLyBHCChPszOR7gPzUHFEgxjJ0lmQ6UD/view?usp=drive_web>

 IMG-6139.jpg
<https://drive.google.com/file/d/16TOJn0WQMEfI2EFDset4dWJTrKYqGrP-/view?usp=drive_web>

**Comment by dseral** [comment]
> @dseral Thank you for your contribution! Could you please confirm you have filled out a CLA? https://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code ?

Dear @antobinary I have already send CLA to @ffdixon  Could you check out from him please?

**Comment by antobinary** [comment]
Implemented in #9649
Thank you for your contribution!

**Pull request closed without merging**
