### PR TITLE
Patching playback updates for iOS

### PR DESCRIPTION
**Pull request by pedrobmarin**
#5986

Some changes we made for `mp4` media recordings to work with iOS and extra adjustments we have on our playback

### CODE REVIEW

**Comment by dahalday** [comment]
@ffdixon. I am getting mixed results. On my test server it works. Upgraded from beta 19 - 23. with each release. On the main server though I upgrade from 19 to 23 without the other release in between and the iOS playback as you noted did not work.

**Comment by ffdixon** [comment]
Did you try it with a new recording on your main server?  How did you upgrade your main server (step-by-step or bbb-install.sh)?

**Comment by ffdixon** [comment]
> I manually upgraded with "apt get update and upgrade" 

That's insufficient to upgrade a server.  See

   http://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

Also, if you have not made any custom configuration changes (outside of `bbb-donf`) we would checking out the [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) script as it does the above steps along with some additional commands.

**Comment by dahalday** [comment]
@ffdixon I will try and let you know. Thank you

**Pull request merged**
