### PR TITLE
fix: In Android Screen share and Share external video not showing to newly joined

### LINKED ISSUE #15453: In Android Screen share and Share external video  not showing to newly joined
**Describe the bug**
In 2.5 and 2.6 
In a Session when Moderator  1) share screen or
2) share an external video.
A. These screenshare and shared external video are not visible to those who join after the screen share/share external video started User is using android
B. But audio is heard by newly joined guests for both shared external video as well as shared screen

**To Reproduce**

**Expected behavior**
Screenshare and Share external video should ALSO be  visible to newly joined 

**Actual behavior**
Screenshare and Share external video is not  visible to newly joined 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Device:  Samsung S21 ultra
 - OS:  Android
 - Browser  chrome
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

Sets initial values for external video/screnshare for mobile devices.

### Closes Issue(s)
Closes #15453

### CODE REVIEW

**Review by JoVictorNunes — APPROVED** [review]
Working as expected!

**Comment by erpsolns** [comment]
Hi I tried reinstalling several time still the issue not resolved. 
Can you please tell me  the path in an installation with install.sh so that I can find and correct.  I tried to find the bigbluebutton-html5 in etc, usr, var etc. folders and I cant find them  [bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx]

**Comment by erpsolns** [comment]
I am used this wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh. or 2.6sh - any many times I run the script the issue not resolved.

**Comment by ramonlsouza** [comment]
> Hi I tried reinstalling several time still the issue not resolved.

Hello @erpsolns! 

This pull request has already been merged to the project (and ported to 2.5!), but changes made here are not in the current 2.5/2.6 releases.

The issue should be part of the next 2.5 (in pre-release, should be released later this week) and 2.6 releases (soon).

**Pull request merged**
