### PR TITLE
Bbb lock settings

### PR DESCRIPTION
**Pull request by tdj-br**
Added lockOnJoinConfigurable property to lock config

### CODE REVIEW

**Comment by capilkey** [comment]
Why not add the the setting to config.xml? It seems like overkill to make all of those changes to apps.

Also, where is "lockOnJoinConfigurable" actually configured?

**Comment by tdj-br** [comment]
Chad, the setting is in the config.xml, and the property is using same flow as other lock settings (it goes to server and back to client), i'll send a new pull request because the label was missing.

**Comment by fcecagno** [comment]
If it's on config.xml, why send it to the server and then get it back
instead of just read it locally?

--
   Felipe Cecagno

(Sent from my Nexus 5)
Em 12/03/2015 18:04, "Tiago Daniel Jacobs" <notifications@github.com>
escreveu:

**Comment by tdj-br** [comment]
The configs can change on the fly, it's why all configs are sent to server. This specific property don't change on the fly, but as we have a flow for the lock settings configurations, it make sense to keep all together

**Pull request closed without merging**
