### PR TITLE
Add Push-to-talk to HTML5 Client

### PR DESCRIPTION
**Pull request by ubahnverleih**
Push-to-talk while pressing `T`-key.
In #2045 Spacebar is mentioned as favorite key for Push-to-talk, but this key is occupied by the Pan tool for the presenter.

### CODE REVIEW

**Comment by MaxouCH** [comment]
very good ! it's possible to contact me please. I have work for you ;)

**Comment by basisbit** [comment]
I guess this PR should better target develop branch instead of v2.2.x - only bugfixes should target 2.2.x  branch. Also, instead of providing the translation in code, it should be added to the Transifex project?

**Comment by basisbit** [comment]
If you have not done so already, please also read and sign the [Contributor License Agreement](http://docs.bigbluebutton.org/support/faq.html#why-do-i-need-to-sign-a-contributor-license-agreement-to-contribute-source-code).

**Comment by antobinary** [comment]
Thank you, we have received your signed CLA!

**Comment by ubahnverleih** [comment]
1. Are there any suggestions for better keys?
2. maybe related: https://github.com/bigbluebutton/bigbluebutton/issues/9329
The 'you are now muted' sound is not generated in client, so i don't see any easy way to surpress this sound message.

**Comment by KDSBrowne** [comment]
@ubahnverleih 

1) Due to the limited number of shortcut keys that aren't already in use, I think
it might be a good option to add a push-to-talk input field to the settings modal. 
This would allow a user to pick what ever key works best for their situation.

2) I'm not sure #9329 is completely related. the loop / flickering issue happens if you are muted via
the userlist item menu as well.

**Comment by rasos** [comment]
We think about replacing some phrases like the  'you are now muted' and 'you are now unmuted' with audio - icons. If they would get repeated because of holding the `t` too long this effect would just say: you pushed the key too long.

**Comment by keunes** [comment]
As for the shortcut keys: not sure if this is correct, but if we assume that the presenter is always unmuted, the spacebar could work for non-presenters as a talking button. If that assumption i not correct, I would vouch for changing things around. Users would most likely much more often speak than they would use the pen tool - I think therefore there's something to say for using the prominent & easy-to-use space bar for talking, and giving the pen tool a lower priority by assigning it a physically smaller (and harder-to-find) key. Sure this would disrupt the current users of the pen tool shortcut, but it'd benefit the larger group of users benefiting from this new tap to speak feature.

**Comment by iSamof** [comment]
@keunes - agreed. Based on our more than 10 years of experience with the likes of GoToWebinar/GoToMeeting, WebX and other virtual conferencing systems, the vast majority of interactive participations are for voice rather than drawing tools. 

Therefore, using the space bar for push-to.talk - which is not language dependent and therefore more universal - seems like a good idea. I wonder what other colleagues think.

**Comment by bitclick** [comment]
From my experience with online seminars, PTT on spacebar would make thins way easier for a lot of users. I would say, even presenters could benefit from this. especially with a noisy setup!

another idea:
there could also be a button that must be pressed for mouse/touch use  - or just klick/touch the video area?

**Comment by keunes** [comment]
Any progress on this? Would be great if the team could agree on the allocation of buttons.

**Comment by keunes** [comment]
Sush bot. Go away

**Comment by ffdixon** [comment]
Yes, go away.  We want this feature too!

**Comment by hex-m** [comment]
@ffdixon If the bot should not mark things as stale you should add one of the `exemptLabels` mentioned in the [bot config](https://github.com/bigbluebutton/bigbluebutton/blob/develop/.github/stale.yml).

**Comment by antobinary** [comment]
This work was redone into #18601 and later into #21032 looking positive to go into BBB 3.0.
Thanks again for the idea, the contributions and for the patience!

**Pull request closed without merging**
