### PR TITLE
packaging: renamed bbb-activity-report to bbb-learning-dashboard

### PR DESCRIPTION
**Pull request by antobinary**
### What does this PR do?
Renamed bbb-activity-report to bbb-learning-dashboard

### Closes Issue(s)

Closes #

### Motivation
In the client and core we already renamed everything to match the Dashboard naming
Related to #13084 

### More

- [ ] I need to test this (I copied over most of the changes that I just made for the 2.4 packaging)

### CODE REVIEW

**Comment by zfgrnzfsberire** [comment]
Hi @antobinary, thank you for adding the changes in the public build system! Could you please also change the name in `.gitlab-ci.yml`, that's currently still breaking the build (see below)? We started mirroring some PRs to our gitlab, so you can see there wheter it works: https://gitlab.senfcall.de/senfcall-public/bigbluebutton/-/tree/pr-13110

```patch
diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
index c18a040dc1..b1997be9f4 100644
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -62,10 +62,10 @@ get_external_dependencies:
       - cache/.gradle
 
 # jobs for all packages in the "build" stage (templated from above)
-bbb-activity-report:
+bbb-learning-dashboard:
   extends: .build_job
   script:
-    - build/setup-inside-docker.sh bbb-activity-report
+    - build/setup-inside-docker.sh bbb-learning-dashboard
 
 bbb-apps-akka-build:
   extends: .build_job
```

**Comment by antobinary** [comment]
Thanks for the review and notice @zfgrnzfsberire 
I see the build failed again, so I will need to look deeper into this...

**Comment by zfgrnzfsberire** [comment]
Hi @antobinary, the problem was on our end, the branch wasn't synced properly. It's now building correctly:

CI: https://gitlab.senfcall.de/senfcall-public/bigbluebutton/-/pipelines/6011
Packages: https://bbb-builds.senfcall.de/branches/pr-13110/

Sorry for the confusion

**Comment by antobinary** [comment]
Excellent! Thank you very much!
May I merge this PR?

**Pull request merged**
