### PR TITLE
Restore minimized presentation for viewer on (slide or zoom change / pub…

### PR DESCRIPTION
**Pull request by KDSBrowne**
This PR adds a new config prop `restoreOnUpdate` when enabled the presentation area will be forcefully restored if it is minimized (Viewers only) for actions:
* presentation / slide / zoom change
* published poll
* added annotation

this can also be enabled via the userData `userdata-bbb_force_restore_presentation_on_new_events=true`

### CODE REVIEW

**Comment by antobinary** [comment]
Please include presentation change to the list of trigger events. Make sure presentation removal does not cause issues.

**Comment by pbdco** [comment]
Hi there @KDSBrowne we found a bug with this on 2.2.17

The presentation is not minimized for viewers, and when the moderator clicks on restore presentation, it just "blinks" on viewers screen. Details on: https://github.com/bigbluebutton/bigbluebutton/issues/9866

Screen: https://tenor.com/view/gif-17536161

**Comment by pbdco** [comment]
@antobinary any guess on this?

**Comment by KDSBrowne** [comment]
@pbdco  The issue you created #9866 seems to have been an issue before merging #9517 so I'm not sure it's exactly related.  After doing some tests on 2.3 this issue does not seem to be present there, have to dig deeper to see what's changed between the two versions that's fixed it.

**Comment by pbdco** [comment]
Do you have an estimated launch time for 2.3? Thank you @KDSBrowne

**Comment by matiasilva** [comment]
@pbdco The BigBlueButton project does not set any hard dates for release, they prioritize quality over quantity. That said, I've seen elsewhere on the issue tracker that a beta may come out this summer. Even then, it'll only be a beta so not everything will work perfectly.

**Comment by pbdco** [comment]
Thanks @matiasilva we hope to see 2.3 out soon.

@KDSBrowne if you have any clue for fixing this on 2.2 it will be much appreciated.

Regards

**Comment by alialic** [comment]
How to delete a presentation frame?

**Comment by matiasilva** [comment]
Hi @alialic, please post your question to https://groups.google.com/forum/#!forum/bigbluebutton-users as it seems like you're requesting support with using BigBlueButton.

**Comment by Jossef-767** [comment]
#10242  minimize presentation for viewer Crushing the presentation

**Pull request merged**
